### ISSUE TITLE
Jupyter Kernel dies/Spyder console stops while training custom NER model in Spacy 2.0.11

### ISSUE THREAD

**Issue by arindam77** [explosion/spaCy#5296] opened 2020-04-12 10:18 UTC
@ines @honnibal I was trying to train a custom NER model in spacy. Initially I had installed the latest spacy version but was getting the following error during the training
 `ValueError: [E103] Trying to set conflicting doc.ents: A token can only be part of one entity, so make sure the entities you're setting don't overlap.`

After that I installed spacy version `spacy==2.0.11` and tried running my code. When I am having around 10 rows of data to train, the model is working fine and it's saving to my output directory. But when there is more data(5K rows) which is the original training data, my jupyter kernel dies or when I run in spyder, the console just exists!!

I understand that the deprecated version of spacy is not throwing the value error but still it's of no use as I am unable to train my model.

Sample data:

    CarryBag	09038820815c.txt
    Stopperneedle	0903882080f4.txt
    Foilbags	09038820819.txt

I have around 700 files like this with data to be tagged and in each file multiple entities need tagging.
Code for reference:

    import spacy
    # import en_core_web_sm
    import re
    import csv
    from spacy.matcher import PhraseMatcher
    import plac
    from pathlib import Path
    import random
    
    #Function to convert PhraseMatcher return value to string indexes 
    def str_index_conversion(lbl, doc, matchitem):
        o_one = len(str(doc[0:matchitem[1]]))
        subdoc = doc[matchitem[1]:matchitem[2]]
        o_two = o_one + len(str(subdoc))
        return (o_one, o_two, lbl)
    
    # nlp = spacy.load('en')
    nlp = spacy.load('en_core_web_sm')
    
    if 'ner' not in nlp.pipe_names:
        ner = nlp.create_pipe('ner')
        nlp.add_pipe(ner)
    else:
        ner = nlp.get_pipe('ner')
    
    ner.add_label('PRODUCT')     
    
    DIR = 'D:/Docs/'
    matcher = PhraseMatcher(nlp.vocab)
    
    
    list_str_index = []
    to_train_ents = []
    with open(r'D:\ner_dummy_pack.csv', newline='', encoding ='utf-8') as myFile:
        
        reader = csv.reader(myFile)
        for row in reader:
            try:
                product = row[0].lower()
                #print('K---'+ product)
                filename = row[1]
                file = open(DIR+filename, "r", encoding ='utf-8')
                print(file)
                filecontents = file.read()
                for s in filecontents:
                    filecontents = re.sub(r'\s+', ' ', filecontents)
                    filecontents = re.sub(r'^https?:\/\/.*[\r\n]*', '', filecontents, flags=re.MULTILINE)
                    filecontents = re.sub(r"http\S+", "", filecontents)
                    filecontents = re.sub(r"[-\"#/@;:<>?{}*`• ?+=~|$.!‘?“”?,_]", " ", filecontents)
                    filecontents = re.sub(r'\d+', '', filecontents)#removing all numbers
                    filecontents = re.sub(' +', ' ',filecontents)
                    #filecontents = filecontents.encode().decode('unicode-escape')
                    filecontents = ''.join([line.lower() for line in filecontents])
                    if "," in product:
                        product_patterns = product.split(',')
                        product_patterns = [i.strip() for i in product_patterns]
    
                        for elem in product_patterns:
                            matcher.add('PRODUCT', None, nlp(elem)) 
                            
                    else:
                        matcher.add('PRODUCT', None, nlp(product))                
                    print(filecontents)
                    doc = nlp(filecontents)
                    matches = matcher(doc)
                            #print(matches)
                    list_str_index = [str_index_conversion('PRODUCT', doc, x) for x in matches]
                    to_train_ents.append((filecontents, dict(entities=list_str_index)))
                    break
                
                
            except Exception as e:
                print(e)
                pass
            
    to_train_entsfinal=to_train_ents      
    
          
    
    
    def main(model=None, output_dir=None, n_iter=100):
        # nlp.vocab.vectors.name = 'spacy_pretrained_vectors'
        optimizer = nlp.begin_training()
        other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
        
        with nlp.disable_pipes(*other_pipes):  # only train NER
            for itn in range(10):
                losses = {}
                random.shuffle(to_train_entsfinal)
                for item in to_train_entsfinal:
                    nlp.update([item[0]],
                               [item[1]],
                               sgd=optimizer,
                               drop=0.50,
                               losses=losses)
                print(losses)
                print("OUTTTTT")
    
    
        if output_dir is None:
            output_dir = "C:\\Users\\APRIL"
    
    
        noutput_dir = Path(output_dir)
        if not noutput_dir.exists():
            noutput_dir.mkdir()
    
        #nlp.meta['name'] = new_model_name
        nlp.to_disk(output_dir)
    
    
        random.shuffle(to_train_entsfinal)
    
    if __name__ == '__main__':
        main()   
 Can anyone help me solve this. Even when I removed conflicting entities in a sample of 10+ rows, example:

    Blister       abc.txt
    Blisterpack   abc.txt
    Blisters      abc.txt   

the same issue is happening and the model is not training
     

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.6.5

**Comment by svlandeg** [comment] 2020-04-13 22:31
I think there may be a few different things going on here, but first things first. You got that ValueError about conflicting entities in `doc.ents`: I think it's important to understand why you got it, and resolve that issue. Reverting to an older version of spaCy won't help (unless you had a different reason for that? That wasn't entirely clear to me).

In general, you're better off with the latest version, currently 2.2.4, because it will include many bug fixes that are not in older version. It will also help us debug issues.

So, what is causing the conflict? Note that in spaCy, one token can never have two different NER annotations. Is your code perhaps trying to do that? Where exactly is the `ValueError` thrown?

**Comment by arindam77** [comment] 2020-04-14 02:20
Hi @svlandeg, thanks for the comment. I have reinstalled spacy 2.2.4 and was debugging my code. 
So, the issue is when I am trying to tag an entity called **'lidding foil'** in my text. **What it is doing, which I really don't understand why it is doing is that, it's tagging **foil** and **lidding foil** as two separate entities in my input text, when only it was supposed to tag **lidding foil** as mentioned in my csv. This is when my input csv file had around 20 files, each having an entity to tag in it** The tagged entity looks something like this which is throwing the error.. 
`{'entities': [(969, 981, 'PRODUCT'), (977, 981, 'PRODUCT'), (1154, 1158, 'PRODUCT'), (1331, 1343, 'PRODUCT'), (1339, 1343, 'PRODUCT'), (1750, 1754, 'PRODUCT'), (2203, 2207, 'PRODUCT'), (3536, 3548, 'PRODUCT'), (3544, 3548, 'PRODUCT'), (3586, 3590, 'PRODUCT'), (4195, 4207, 'PRODUCT'), (4203, 4207, 'PRODUCT'), (4340, 4352, 'PRODUCT'), (4348, 4352, 'PRODUCT'), (4909, 4921, 'PRODUCT'), (4917, 4921, 'PRODUCT'), (5008, 5012, 'PRODUCT'), (5627, 5631, 'PRODUCT'), (5666, 5670, 'PRODUCT'), (6008, 6012, 'PRODUCT'), (7014, 7018, 'PRODUCT'), (7107, 7111, 'PRODUCT'), (7714, 7718, 'PRODUCT'), (7785, 7789, 'PRODUCT'), (7946, 7950, 'PRODUCT'), (8616, 8628, 'PRODUCT'), (8624, 8628, 'PRODUCT'), (8801, 8805, 'PRODUCT'), (8978, 8990, 'PRODUCT'), (8986, 8990, 'PRODUCT')]})`
and the error is as follows:

`ValueError: [E103] Trying to set conflicting doc.ents: '(969, 981, 'PRODUCT')' and '(977, 981, 'PRODUCT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.`

If I debug deeper, I am getting such results:

```
n
ValueError: [E103] Trying to set conflicting doc.ents: '(969, 981, 'PRODUCT')' and '(977, 981, 'PRODUCT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3331)run_code()
   3329                     await eval(code_obj, self.user_global_ns, self.user_ns)
   3330                 else:
-> 3331                     exec(code_obj, self.user_global_ns, self.user_ns)
   3332             finally:
   3333                 # Reset our crash handler in place


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3334)run_code()
   3332             finally:
   3333                 # Reset our crash handler in place
-> 3334                 sys.excepthook = old_excepthook
   3335         except SystemExit as e:
   3336             if result is not None:


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3335)run_code()
   3333                 # Reset our crash handler in place
   3334                 sys.excepthook = old_excepthook
-> 3335         except SystemExit as e:
   3336             if result is not None:
   3337                 result.error_in_exec = e


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3340)run_code()
   3338             self.showtraceback(exception_only=True)
   3339             warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
-> 3340         except self.custom_exceptions:
   3341             etype, value, tb = sys.exc_info()
   3342             if result is not None:


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3345)run_code()
   3343                 result.error_in_exec = value
   3344             self.CustomTB(etype, value, tb)
-> 3345         except:
   3346             if result is not None:
   3347                 result.error_in_exec = sys.exc_info()[1]


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3346)run_code()
   3344             self.CustomTB(etype, value, tb)
   3345         except:
-> 3346             if result is not None:
   3347                 result.error_in_exec = sys.exc_info()[1]
           self.showtraceback(running_compiled_code=True)


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3347)run_code()
   3345         except:
   3346             if result is not None:
-> 3347                 result.error_in_exec = sys.exc_info()[1]
   3348             self.showtraceback(running_compiled_code=True)
   3349         else:


n
> c:\users\delt\anaconda3\lib\site-packages\ipython\core\interactiveshell.py(3348)run_code()
   3346             if result is not None:
   3347                 result.error_in_exec = sys.exc_info()[1]
-> 3348             self.showtraceback(running_compiled_code=True)
   3349         else:
   3350             outflag = False
```


BUT...

When I created a new csv file, which only contained 1 file, i.e. the file which needed to tag the entity **lidding foil** in it, it's running fine and training an NER model for the same. The tagged entities for the same file looks something like this now:

**`{'entities': [(969, 981, 'PRODUCT'), (1331, 1343, 'PRODUCT'), (3536, 3548, 'PRODUCT'), (4195, 4207, 'PRODUCT'), (4340, 4352, 'PRODUCT'), (4909, 4921, 'PRODUCT'), (8616, 8628, 'PRODUCT'), (8978, 8990, 'PRODUCT')]})`**
`{'ner': 374.5804672241211}`

One thing to note is that, it's a very large file and maybe there's some memory issues that causing such unprecedented errors. How can I handle such a scenario as I have a huge list of entities and files to tag. Any idea?

**Comment by svlandeg** [comment] 2020-04-24 08:37
> So, the issue is when I am trying to tag an entity called 'lidding foil' in my text. What it is doing, which I really don't understand why it is doing is that, it's tagging foil and lidding foil as two separate entities in my input text, when only it was supposed to tag lidding foil as mentioned in my csv. 

It definitely looks like you either have a bug in your preprocessing code, or your match patterns are too generic, and are matching many different, possibly overlapping, entities. I can't comment on your specific use-case because there's no reproducible example I can run, but here's the general idea:

Suppose you want to match any sequence of nouns, one or more `NOUN` tags:

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_lg")

matcher = Matcher(nlp.vocab)
pattern = [{"POS": "NOUN", "OP": "+"}]
matcher.add("MyPattern", None, pattern)

doc = nlp("I want to buy lidding foil.")
matches = matcher(doc)
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]  # Get string representation
    span = doc[start:end]  # The matched span
    print(match_id, string_id, start, end, span.text)
```
you'll get:
```
15181006293565190857 MyPattern 4 5 lidding
15181006293565190857 MyPattern 4 6 lidding foil
15181006293565190857 MyPattern 5 6 foil
```

You can't feed all three of these entities into the NER training algorithm for the sentence "I want to buy lidding foil.", because, as the error message states, there can not be overlapping entities. You'll need to
- either make sure your match patterns don't produce overlapping matches. This depends on your text, your patterns and your use-case
- or post-process the retrieved matches to filter them down to a non-overlapping set. This also depends on your use-case. You can use the `start` and `end` information to do so automatically. In the case above, you either need to keep "lidding [4-5]" and "foil [5-6]", or only keep "lidding foil [4-6]" and remove the other two.

Either way, it doesn't look like this is a bug in spaCy. As we try to keep this issue tracker focused on bugs and feature requests, and we don't have the bandwidth to help debug specific use-cases, I will close this for now. If you can share a reproducible code snippet that shows the issue is in spaCy, please feel free to open a new issue. Otherwise, these kind of generic usage questions are probably better on StackOverflow (but also for SO, a reproducible code snippet is generally required).

**Closed by svlandeg** 2020-04-24 08:37 UTC
Labels: feat / matcher, feat / ner, training, usage

**Comment by arindam77** [comment] 2020-04-27 08:19
How do I filter out my matches, so that only the match with the largest length of string remains?

**Comment by arindam77** [comment] 2020-04-27 15:56
I tried creating a new PhraseMatcher object inside the loop while tagging the data but the code editor crashes..
