### ISSUE TITLE
torch.embedding IndexError when applying en_core_web_trf 3.0.0a0

### ISSUE THREAD

**Issue by thomasbird** [explosion/spaCy#6709] opened 2021-01-11 16:43 UTC
## How to reproduce the behaviour

When using en_core_web_trf 3.0.0a0 and spacy 3.0.0rc2, I have found some text that causes `nlp(text)` to raise an IndexError from `torch.embedding`.

The script below reproduces the error in combination with the attached text: [out_of_range_error_utf8.txt](https://github.com/explosion/spaCy/files/5797059/out_of_range_error_utf8.txt)

```python
import spacy

with open("out_of_range_error_utf8.txt", 'rt') as f:
    text = f.read()

nlp = spacy.load('en_core_web_trf')
doc = nlp(text)
```

The traceback produced is below.

```
Traceback (most recent call last):
  File "./script.py", line 12, in <module>
    doc = nlp(text)
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy/language.py", line 984, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 154, in __call__
    outputs = self.predict([doc])
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 189, in predict
    activations = self.model.predict(docs)
  File "/home/thomas/.local/lib/python3.8/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy_transformers/layers/transformer_model.py", line 111, in forward
    tensors, bp_tensors = transformer(token_data, is_train)
  File "/home/thomas/.local/lib/python3.8/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/thomas/.local/lib/python3.8/site-packages/thinc/layers/pytorchwrapper.py", line 79, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/thomas/.local/lib/python3.8/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/thomas/.local/lib/python3.8/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/transformers/modeling_bert.py", line 752, in forward
    embedding_output = self.embeddings(
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/transformers/modeling_roberta.py", line 67, in forward
    return super().forward(
  File "/home/thomas/.local/lib/python3.8/site-packages/transformers/modeling_bert.py", line 179, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 124, in forward
    return F.embedding(
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

Thanks for the great package! Let me know if you need any more details.

## Your Environment

- **spaCy version:** 3.0.0rc2
- **Platform:** Linux-5.4.0-58-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_md (3.0.0a0), en_core_web_trf (3.0.0a0), en_core_web_lg (3.0.0a0), en_core_web_sm (3.0.0a0), fr_dep_news_trf (3.0.0a0)

**Comment by adrianeboyd** [comment] 2021-01-11 16:47
This is a duplicate of #6692 (and others mentioned in that issue).

See also https://github.com/explosion/spacy-transformers/pull/246, which isn't a fix, just a better error message for now.

**Closed by adrianeboyd** 2021-01-11 16:47 UTC
Labels: duplicate, feat / transformer
