### ISSUE TITLE
Memory leak using en_core_web_sm nlp

### ISSUE THREAD

**Issue by emarcey** [explosion/spaCy#3013] opened 2018-12-05 23:12 UTC
## How to reproduce the behaviour
Using the en_core_web_sm model to tokenize text and we noticed our memory was climbing and led to OOM errors. 

Below is a script that performs the following steps:
1. Loads en_core_web_sm
2. Then runs a subprocess 10 times
3. First, creates a deep copy of the nlp model
4. Then, processes 1000 randomly created words
5. At the end of the subprocess, the deep copy is deleted and garbage is collected
6. Finally, at the end of the file, the nlp model is manually deleted and garbage is collected.

The results show that, despite the efforts to clean up the environment, the memory still rises.

### Info about spaCy

* *spaCy version:* 2.0.16
* *Platform:* Darwin-18.0.0-x86_64-i386-64bit
    * Issue has also occurred on Alpine 3.6
* *Python version:* 3.6.5
* *Models:* en_core_web_sm, en

## Code:
```python
from copy import deepcopy
import gc
import os
import psutil
import random
import spacy
import string

num_runs = 10
num_words = 1000


def randomword(length):
   letters = string.ascii_lowercase
   return ''.join(random.choice(letters) for i in range(length))

def get_memory(process):
    return f"{round(process.memory_info()[0] / float(2 ** 20), 6)} MB"

if __name__ == '__main__':
    process = psutil.Process(os.getpid())

    print("Loading model.")
    print(f"Pre-load memory: {get_memory(process)}")
    nlp = spacy.load('en_core_web_sm', disable=['ner', 'parser'])
    print(f"Post-load memory: {get_memory(process)}")
    print("")

    for i in range(num_runs):
        print(f"Run {i}.")
        print(f"\tPre-copy memory: {get_memory(process)}")
        nlp_deep_copy = deepcopy(nlp)
        print(f"\tPost-copy memory: {get_memory(process)}")

        for j in range(num_words):
            word = randomword(j)
            nlp_deep_copy(word)
        print(f"\tPost-execution memory: {get_memory(process)}")
        del nlp_deep_copy
        gc.collect()
        print(f"\tPost-copy-delete memory: {get_memory(process)}")

    print("")
    print(f"Post-process memory: {get_memory(process)}")
    del nlp
    gc.collect()
    print(f"Post-delete memory: {get_memory(process)}")
```

## Results
> Loading model.
> Pre-load memory: 49.285156 MB
> Post-load memory: 157.777344 MB
>
> Run 0.
> 	Pre-copy memory: 157.777344 MB
> 	Post-copy memory: 246.890625 MB
> 	Post-execution memory: 248.726562 MB
> 	Post-copy-delete memory: 208.40625 MB
> Run 1.
> 	Pre-copy memory: 208.40625 MB
> 	Post-copy memory: 254.191406 MB
> 	Post-execution memory: 254.535156 MB
> 	Post-copy-delete memory: 211.253906 MB
> Run 2.
> 	Pre-copy memory: 211.253906 MB
> 	Post-copy memory: 257.320312 MB
> 	Post-execution memory: 257.628906 MB
> 	Post-copy-delete memory: 213.441406 MB
> Run 3.
> 	Pre-copy memory: 213.441406 MB
> 	Post-copy memory: 258.066406 MB
> 	Post-execution memory: 258.070312 MB
> 	Post-copy-delete memory: 213.417969 MB
> Run 4.
> 	Pre-copy memory: 213.417969 MB
> 	Post-copy memory: 258.003906 MB
> 	Post-execution memory: 258.011719 MB
> 	Post-copy-delete memory: 215.285156 MB
> Run 5.
> 	Pre-copy memory: 215.285156 MB
> 	Post-copy memory: 257.511719 MB
> 	Post-execution memory: 257.523438 MB
> 	Post-copy-delete memory: 213.511719 MB
> Run 6.
> 	Pre-copy memory: 213.511719 MB
> 	Post-copy memory: 257.988281 MB
> 	Post-execution memory: 257.988281 MB
> 	Post-copy-delete memory: 213.296875 MB
> Run 7.
> 	Pre-copy memory: 213.296875 MB
> 	Post-copy memory: 257.523438 MB
> 	Post-execution memory: 257.523438 MB
> 	Post-copy-delete memory: 213.511719 MB
> Run 8.
> 	Pre-copy memory: 213.511719 MB
> 	Post-copy memory: 258.121094 MB
> 	Post-execution memory: 258.121094 MB
> 	Post-copy-delete memory: 213.679688 MB
> Run 9.
> 	Pre-copy memory: 213.679688 MB
> 	Post-copy memory: 258.15625 MB
> 	Post-execution memory: 258.15625 MB
> 	Post-copy-delete memory: 213.679688 MB
> 
> Post-process memory: 213.679688 MB
> Post-delete memory: 137.910156 MB

**Comment by honnibal** [comment] 2018-12-06 14:20
Thanks for the script. If you give this many many more runs, does it keep rising? The problem is Python is pretty notorious for fragmenting its memory and having memory slowly rise in its internal allocation pools, so it's really hard to tell from a small test whether there's an actual leak, or whether it's just Python being Python. If you run this for like 1000 runs, do you eventually end up with gigs of memory lost?

**Comment by emarcey** [comment] 2018-12-07 15:40
I ran three tests:
1. The same script with 1000 runs
2. 1000 runs without manual garbage collection
3. 1000 runs with a single instance of nlp (no deep copies)

To a degree, I think you're right: over 1000 runs the change in memory was less significant for tests 1 and 2. 

## For 1:
> Pre-load memory: 49.382812 MB
> Post-load memory: 157.59375 MB
> Post-process memory: 182.167969 MB
> Post-delete memory: 129.457031 MB

## For 2: 
> Pre-load memory: 49.292969 MB
> Post-load memory: 157.671875 MB
> Post-process memory: 298.347656 MB

## For 3:
However, I noticed that when I didn't use the deep copies, the original memory began to scale considerably:

> Pre-load memory: 49.246094 MB
> Post-load memory: 157.644531 MB
> Post-process memory: 634.773438 MB

Over the course of the run, I increased about half a GB in memory. Is the model expected to grow in size as it parses text? I believe this is the source of the OOM error on our job.

**Comment by honnibal** [comment] 2018-12-07 19:30
There are a few internal caches which are expected to grow, yes. In your tests you're parsing with entirely random words, which is extremely unlike linguistic workloads, where most tokens are of a limited number of types. If you parse actual text, I expect you'll see a fairly modest increase in memory use, that should level off once the vocab cache is full (from memory, at 100,000 entries).

**Comment by emarcey** [comment] 2018-12-07 21:33
The job we are using is parsing complete news articles, however, and the cache continues to grow well past 100,000 articles, let alone words

**Comment by honnibal** [comment] 2018-12-07 23:41
Well it does take more than 100,000 articles to see 100,000 unique word types.

**Comment by emarcey** [comment] 2018-12-13 15:16
I see, is the vocab cache size configurable?

**Comment by honnibal** [comment] 2018-12-18 23:35
It's currently hard-coded, unfortunately. That's definitely something we can change though.

I'll close this thread for now though, as I think it seems like this isn't actually a memory leak.

**Closed by honnibal** 2018-12-18 23:35 UTC
Labels: bug, perf / memory

**Comment by jcapobianco-cbi** [comment] 2019-01-17 21:12
@honnibal Is there a separate issue for configurable vocab cache size?
