### ISSUE TITLE
v2.1 launching multiple threads when numpy installed via conda

### ISSUE THREAD

**Issue by f11r** [explosion/spaCy#3820] opened 2019-06-04 12:27 UTC
It looks like spaCy v2.1 is launching multiple threads when using numpy installed via conda (and thus with mkl). This does not happen when installing numpy via pip. Is this expected behavior? From the v2.1 release blog post it sounded like this shouldn't happen.

## How to reproduce the behaviour

single-threaded:

`docker run -t --entrypoint bash continuumio/miniconda3:4.6.14 -c "pip install numpy==1.16.2 spacy==2.1.4 https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz && python -c 'import de_core_news_sm; nlp = de_core_news_sm.load(); print(\"start\"); docs = [nlp(100*\"This is a test text. \") for _ in range(10000)]'"`

multi-threaded:

`docker run -t --entrypoint bash continuumio/miniconda3:4.6.14 -c "conda install -y numpy==1.16.2 && pip install spacy==2.1.4 https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz && python -c 'import de_core_news_sm; nlp = de_core_news_sm.load(); print(\"start\"); docs = [nlp(100*\"This is a test text. \") for _ in range(10000)]'"`

**Comment by honnibal** [comment] 2019-06-05 20:11
It's not expected behaviour, no. That means there must be some numpy op that's multi-threaded on mkl but not on OpenBLAS. Damn.

We need to find out which op that is, and replace the calls to it with calls to `blis`. I suspect the change will mostly be in Thinc. Could you have a look at `perf top` and see what MKL functions it seems to be spending time in?

**Comment by f11r** [comment] 2019-06-06 12:20
These are the first output lines of `perf top`:

```
  85.51%  libiomp5.so                                        [.] _INTERNAL_25_______src_kmp_barrier_cpp_ddfed41b::__kmp_wait_template<kmp_flag_64, 1, false, true>
   4.07%  cy.cpython-37m-x86_64-linux-gnu.so                 [.] bli_sgemm_haswell_asm_6x16
   1.20%  cy.cpython-37m-x86_64-linux-gnu.so                 [.] bli_spackm_16xk_haswell_ref
```

and these seem to be the MKL related lines:

```
   0.07%  libmkl_avx512.so                                   [.] mkl_blas_avx512_xdcopy
   0.02%  _multiarray_umath.cpython-37m-x86_64-linux-gnu.so  [.] call_mkl_mv
   0.00%  libmkl_vml_avx512.so                               [.] mkl_vml_kernel_sExp_Z0HAynn
   0.00%  libmkl_vml_avx512.so                               [.] mkl_vml_kernel_sDiv_Z0HAynn
   0.00%  _multiarray_umath.cpython-37m-x86_64-linux-gnu.so  [.] call_mkl_cpy
   0.00%  libmkl_intel_thread.so                             [.] mkl_blas_dcopy
   0.00%  libmkl_intel_thread.so                             [.] mkl_serv_domain_get_max_threads
   0.00%  libmkl_intel_thread.so                             [.] mkl_serv_get_dynamic@plt
   0.00%  libmkl_intel_thread.so                             [.] mkl_vml_serv_threader_s_1i_1o
   0.00%  libmkl_intel_lp64.so                               [.] mkl_blas__dcopy
   0.00%  libmkl_intel_lp64.so                               [.] mkl_vml_serv_load_vml_dll@plt
   0.00%  libmkl_intel_thread.so                             [.] mkl_vml_serv_GetMinN
   0.00%  libmkl_intel_thread.so                             [.] mkl_blas_xdcopy@plt
   0.00%  libmkl_intel_thread.so                             [.] mkl_serv_cpu_detect@plt
   0.00%  libmkl_core.so                                     [.] mkl_blas_xdcopy
   0.00%  libmkl_vml_avx512.so                               [.] mkl_vml_kernel_GetMode@pl
```

**Comment by honnibal** [comment] 2019-07-10 12:12
Hmm I wonder whether I'm misreading this. It looks to me like all the time is spent waiting at the barrier, but then all the MKL calls are just copy operations? If so, that will be hard to avoid -- we can't easily avoid the *copy* operations being delegated to MKL, as far as I can see.

In the meantime, definitely the best solution should be to make sure the environment variable `export MKL_NUM_THREADS=1` is set. Hopefully this will avoid the problem.

**Comment by polm** [comment] 2021-06-07 08:56
Going to close this ticket because it's for a pretty old version at this point and we haven't had any other reports of this behavior, but if it's still an issue feel free to reopen it.

**Closed by polm** 2021-06-07 08:56 UTC
Labels: bug, third-party, 🔮 thinc
