### ISSUE TITLE
Saving and loading Vocab

### ISSUE THREAD

**Issue by fortuin** [explosion/spaCy#1141] opened 2017-06-21 08:27 UTC
I am parsing a number of documents and encoding them as integer sequences using the standard Vocab. Since some of the words are OOV, new entries for them get generated dynamically. When I try to decode the documents again with the standard Vocab, these words are missing of course and give me IndexErrors.
So I am looking for a way to save the Vocab object after encoding all the documents, such that I can reload it for decoding later. I tried pickle and Vocab.dump, but neither seems to work. Pickle just crashes the Python kernel when unpickling and the other gives me an IndexError when loading the lexemes for the first index that is not part of the standard Vocab.
Is there a canonical way of doing this?

**Comment by honnibal** [comment] 2017-07-03 15:01
Sorry for the delay getting back to you on this.

The problem is fixed in v2, since the integer IDs are hash values, rather than the dynamic IDs in v1.

In v1 you can save all the models with `nlp.save_to_disk(path)`. To just save the vocab, do:

```python
nlp.vocab.dump(path / 'lexemes.bin')
with (path / 'strings.json').open('wb') as file_:
    nlp.vocab.strings.dump(file_)
```

**Closed** 2017-10-16 18:14 UTC
Labels: usage
