### ISSUE TITLE
spark does not utilize all cores when running a spacy parse or dies in serialization code

### ISSUE THREAD

**Issue by aliabbasjp** [explosion/spaCy#413] opened 2016-06-07 11:12 UTC
I have some worker function which use spacy to parse the documents sent to them, on using spacy it only uses a single core of the system , without spacy all cores are utilized?
It means that only one worker is being run at a time.

**Comment by aliabbasjp** [comment] 2016-06-08 05:41
@honnibal  Also at times I get following error:
```

Traceback (most recent call last):
  File "/opt/conda/envs/python2/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/conda/envs/python2/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/conda/envs/python2/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/conda/envs/python2/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/spark/python/pyspark/accumulators.py", line 235, in handle
    num_updates = read_int(self.rfile)
  File "/usr/local/spark/python/pyspark/serializers.py", line 545, in read_int
    raise EOFError
EOFError
```

**Comment by honnibal** [comment] 2016-10-23 23:36
I'm going to close this for now because the issue is old, and this type of error is very tough to reproduce. If it's still occurring, please reopen and we'll try to figure out what's up.

**Closed by honnibal** 2016-10-23 23:36 UTC
Labels: bug
