### ISSUE TITLE
Texcat model predictions are random for every-time I call prediction.

### ISSUE THREAD

**Issue by NaveenKumarStark** [explosion/spaCy#10968] opened 2022-06-15 13:12 UTC
## Your Environment

* Operating System:Mac OS
* Python Version Used:3.7
* spaCy Version Used:3.3.0
* Environment Information:

**Comment by svlandeg** [comment] 2022-06-16 11:12
Duplicate of https://github.com/explosion/spaCy/discussions/10969

**Closed by svlandeg** 2022-06-16 11:12 UTC
