### ISSUE TITLE
Vector lookup via vocab and lexeme doesn't work

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#1310] opened 2017-09-07 14:20 UTC
There is no problem getting the vector of a token, but when accessing it from the token entry in the `vocab` it returns a vector of zeros. See the following example:

```python
tok = nlp(u"Natural")[0]

tok.vector
# array([ 10.97093678,   9.08803749,  -1.35087729,  -5.2099762 ...]
tok.vocab[tok.orth].vector
# array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., ...]

tok.rank # > 8320L
tok.vocab[tok.orth].rank # > 8320L
```

## Your Environment

* Operating System: macOs
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.0a13 
* Environment Information:

**Comment by bittlingmayer** [comment] 2017-09-08 10:19
Duplicate of #1191?

**Closed** 2017-10-16 18:37 UTC
Labels: usage
