### ISSUE TITLE
We cannot access the extension attributes during parallelisation?

### ISSUE THREAD

**Issue by ali3assi** [explosion/spaCy#11213] opened 2022-07-26 16:51 UTC
We define and add the following extratcor to spacy pipeline:

```
from spacy.matcher import PhraseMatcher
from spacy.util import filter_spans
from spacy.language import Language

@Language.factory("doid_extractor") 
class DOIDExtractorComponent(object):
    # name of the component
   

    def __init__(self, nlp, label="DOID",  name = "doid_extractor"):
        # label that is applied to the matches
        self.label = label

        # load ontology
        print("Loading DOID ontology")
        doid = Ontology("http://purl.obolibrary.org/obo/doid.obo")
        
        # init terms and patterns
        self.terms = {}
        patterns = []

        i = 0
        nr_terms = len(doid.terms())
        # init progress bar as loading terms takes long
        print("Importing terms")
        bar = progressbar.ProgressBar(maxval=nr_terms, 
                                      widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
        bar.start()

        # iterate over terms in ontology
        for term in doid.terms():
          # if term has a name
          if term.name is not None:
            self.terms[term.name.lower()] = {'id': term.id}
            patterns.append(nlp(term.name))
          i += 1
          bar.update(i)
            
        bar.finish()
        
        # initialize matcher and add patterns
        self.matcher = PhraseMatcher(nlp.vocab, attr='LOWER')
        self.matcher.add(label, None, *patterns)
        
        # set extensions to tokens, spans and docs
        Token.set_extension("is_doid_term", default=False, force=True)
        Token.set_extension("doid_id", default=False, force=True)
        Token.set_extension("merged_concept", default=False, force=True)
        Doc.set_extension("has_doids", getter=self.has_doids, force=True)
        Doc.set_extension("doids", default=[], force=True)
        Span.set_extension("has_doids", getter=self.has_doids, force=True)
        
    def __call__(self, doc):
        matches = self.matcher(doc)
        spans = [Span(doc, match[1], match[2], label=self.label) for match in matches]
        for i, span in enumerate(spans):
          span._.set("has_doids", True)
          for token in span:
               token._.set("is_doid_term", True)
               token._.set("doid_id", self.terms[span.text.lower()]["id"])

        with doc.retokenize() as retokenizer:
            for span in filter_spans(spans):
                retokenizer.merge(span, attrs={"_": {"merged_concept": True}})
                doc._.doids = list(doc._.doids) + [span]

        return doc
    # setter function for doc level
    def has_doids(self, tokens):
        return any([t._.get("is_doid_term") for t in tokens])
```
and then in the

```
if __name__ == "__main__":

 # # python -m spacy download en_core_web_sm
    nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("doid_extractor", after = "ner")

```
It works good as I want. Now I have a dataframe where each row include a column called text including some text.

So I write I the following function:

```
def row_df(df, i):
    text = {} 
    text = str(df.loc[i, "text"]) 
    doc = nlp(text)
    for token in doc:                
          if token._.is_doid_term:              
              pass

```
and I want to parrallelise the use of this functio. So, in the main I add the following:

`Parallel(n_jobs = 4)(delayed(row_df)(df, nlp, idx) for idx, _ in df.iterrows())
`
When run the main I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\onto.py", line 108, in <module>
    Parallel(n_jobs = 4)(delayed(row_df)(df, idx) for idx, _ in df.iterrows())
  File "C:\Users\Admin\miniconda3\envs\projet1\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\Admin\miniconda3\envs\projet1\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Admin\miniconda3\envs\projet1\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\Admin\miniconda3\envs\projet1\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\Admin\miniconda3\envs\projet1\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
AttributeError: [E046] Can't retrieve unregistered extension attribute 'is_doid_term'. Did you forget to call the `set_extension` method?
```
I dont know how to solve this issue. any suggestion. Thanks

Noting that if I set the number of jobs to 1 (n_jobs = 1), the code works perfectly?

**Comment by polm** [comment] 2022-07-27 02:52
Duplicate of #11212. Please do not open duplicates, we'll follow up in the Discussion.

**Closed by polm** 2022-07-27 02:52 UTC
