### ISSUE TITLE
Multithread operations: thinc.exceptions.UndefinedOperatorError

### ISSUE THREAD

**Issue by TimurNurlygayanov** [explosion/spaCy#4863] opened 2020-01-02 07:53 UTC
## How to reproduce the behavior

Run several threads with the following code:

```
import spacy
from joblib import Parallel, delayed

sentences = ['test', 'test', 'test', 'test']

def test(sentence):
    nlp = spacy.load('en', disable=['parser', 'ner'])
    doc = nlp(sentence)

Parallel(n_jobs=10, timeout=300, backend='threading') \
        (delayed(test)(s) for s in sentences))
```

Result:
```

Traceback (most recent call last):
  File "get_films_by_description.py", line 76, in <module>
    for i, task in enumerate(keys))
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "get_films_by_description.py", line 56, in get_text
    text = prepare_text(text)
  File "get_films_by_description.py", line 34, in prepare_text
    nlp = spacy.load('en', disable=['parser', 'ner'])
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 162, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 179, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 211, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 941, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 936, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 661, in spacy.pipeline.pipes.Tagger.from_disk
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "pipes.pyx", line 640, in spacy.pipeline.pipes.Tagger.from_disk.load_model
  File "pipes.pyx", line 548, in spacy.pipeline.pipes.Tagger.Model
  File "/usr/local/lib/python3.7/site-packages/spacy/_ml.py", line 586, in build_tagger_model
    pretrained_vectors=pretrained_vectors,
  File "/usr/local/lib/python3.7/site-packages/spacy/_ml.py", line 323, in Tok2Vec
    return _legacy_tok2vec.Tok2Vec(width, embed_size, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/spacy/ml/_legacy_tok2vec.py", line 59, in Tok2Vec
    (norm | prefix | suffix | shape)
  File "/usr/local/lib/python3.7/site-packages/thinc/check.py", line 134, in checker
    raise UndefinedOperatorError(op, instance, args[0], instance._operators)
thinc.exceptions.UndefinedOperatorError: 

  Undefined operator: |
  Called by (<thinc.neural._classes.function_layer.FunctionLayer object at 0x12d437bd0>, <thinc.neural._classes.hash_embed.HashEmbed object at 0x12d437e50>)
  Available: 

  Traceback:
  ├─ from_disk in /usr/local/lib/python3.7/site-packages/spacy/util.py:654
  ├─── build_tagger_model in /usr/local/lib/python3.7/site-packages/spacy/_ml.py:586
  └───── Tok2Vec in /usr/local/lib/python3.7/site-packages/spacy/_ml.py:323
         >>> return _legacy_tok2vec.Tok2Vec(width, embed_size, **kwargs)

```

## Environment
Operating System: MacOS
Python Version Used: 3.7.4
spaCy Version Used: spacy==2.2.3

```
 python3 -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.4
* **Models:** en

```

**Comment by TimurNurlygayanov** [comment] 2020-01-02 07:58
The workaround, just in case if somebody will face the same issue:

```
import spacy
from joblib import Parallel, delayed

sentences = ['test', 'test', 'test', 'test']
nlp = spacy.load('en', disable=['parser', 'ner'])

def test(sentence):
    global nlp
    doc = nlp(sentence)

Parallel(n_jobs=10, timeout=300, backend='threading') \
        (delayed(test)(s) for s in sentences))
```

**Comment by adrianeboyd** [comment] 2020-01-02 08:09
Thanks for the report! This is a duplicate of #4349 and should be fixed in the next release of thinc.

**Closed by adrianeboyd** 2020-01-02 08:09 UTC
Labels: bug, duplicate, 🔮 thinc
