### ISSUE TITLE
Thousands of words mistakenly use "you" as lemma 

### ISSUE THREAD

**Issue by chaouiy** [explosion/spaCy#10065] opened 2022-01-15 14:26 UTC
## How to reproduce the behaviour
Calculate `token.lemma_` for token `party` in the sentence `While in the city one day I met several of the old, as well as the young men, who had been members of the Free State party all through the Kansas troubles, and who had, like our family, lost everything at the hands of the Missourians` using `en_core_web_sm ` model, you will get `you` as a result

## Your Environment
- **spaCy version:** 3.2.1
- **Platform:** Linux-5.11.0-46-generic-x86_64-with-glibc2.2.5
- **Python version:** 3.8.0
- **Pipelines:** ja_core_news_sm (3.2.0), ru_core_news_sm (3.2.0), zh_core_web_sm (3.2.0), nl_core_news_sm (3.2.0), da_core_news_sm (3.2.0), pl_core_news_md (3.2.0), pt_core_news_sm (3.2.0), es_core_news_sm (3.2.0), it_core_news_sm (3.2.0), de_core_news_sm (3.2.0), fr_core_news_sm (3.2.0), en_core_web_sm (3.2.0)

# Additional information 
It happens to thousands of words other than "party" that all strangely use "you" as lemma.

**Comment by honnibal** [comment] 2022-01-15 16:11
Sounds bad! Thanks for the report, we're looking into it.

**Comment by chaouiy** [comment] 2022-01-15 23:00
@adrianeboyd  can you please provide the duplicate issue ?

**Comment by adrianeboyd** [comment] 2022-01-17 07:14
Hi, this is a duplicate of #9853. It's been fixed in our internal training data and will be fixed in the next model release (probably model version v3.3.0).

Attached is a file with the current internal version of attribute ruler patterns (rename to `.json`), also including a few other bug fixes from other reports related to whitespace dependency relations.

[ar_patterns.json.txt](https://github.com/explosion/spaCy/files/7875441/ar_patterns.json.txt)

You can update this in an `en_core_*` v3.2.0 model as described here: https://github.com/explosion/spaCy/issues/10003#issuecomment-1009952032

**Comment by adrianeboyd** [comment] 2022-01-17 10:51
Let me close this to keep the discussion in one place in #9853, which will still include a link here.

**Closed by adrianeboyd** 2022-01-17 10:51 UTC
Labels: bug, duplicate, feat / lemmatizer
