### ISSUE TITLE
is_sent_start `None` instead of False

### ISSUE THREAD

**Issue by DomHudson** [explosion/spaCy#5050] opened 2020-02-22 14:32 UTC
## Summary
The docs describe is_sent_start is being a boolean (or None if unknown). It appears that the value is a boolean type, for tokens that demark a sentence boundary, and a None-type otherwise.

## How to reproduce the behaviour
```python
import spacy

nlp = spacy.load('en_core_web_sm', disable = ('ner',))
doc = nlp('This is a sentence. This is a second sentence.')
for token in doc:
    print(token.is_sent_start)
```
Output:
```
True
None
None
None
None
True
None
None
None
None
None
```

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.3.0-40-generic-x86_64-with-elementary-5.1.2-hera
* **Python version:** 3.6.9

```
$ pip list

Package            Version   
------------------ ----------
blis               0.4.1     
catalogue          1.0.0     
certifi            2019.11.28
chardet            3.0.4     
cymem              2.0.3     
en-core-web-sm     2.2.5     
idna               2.9       
importlib-metadata 1.5.0     
murmurhash         1.0.2     
numpy              1.18.1    
pip                20.0.2    
pkg-resources      0.0.0     
plac               1.1.3     
preshed            3.0.2     
requests           2.23.0    
setuptools         45.2.0    
spacy              2.2.3     
srsly              1.0.1     
thinc              7.3.1     
tqdm               4.43.0    
urllib3            1.25.8    
wasabi             0.6.0     
wheel              0.34.2    
zipp               3.0.0   
```

```
$ lsb_release -a

Distributor ID:	elementary
Description:	elementary OS 5.1.2 Hera
Release:	5.1.2
Codename:	hera
```

**Comment by svlandeg** [comment] 2020-02-23 16:05
I agree that this is unexpected behaviour, because with the simple `sentencizer` you do get `True`/`False`: 

```

```
True
False
False
False
False
True
False
False
False
False
False
```

**Comment by adrianeboyd** [comment] 2020-02-23 16:39
I actually think that this is more the intended behavior and the `sentencizer` should be modified.

The idea behind it is that more than one component might want to add sentence boundaries, so you leave the remaining tokens as `None` unless you're sure you don't want them to be modified by a future component in the pipeline. See #4775.

**Comment by svlandeg** [comment] 2020-02-23 16:44
That seems pretty confusing to the user / downstream components though.

**Comment by adrianeboyd** [comment] 2020-02-23 19:25
I can see that, but I think it makes sense to make this be configurable, because there are a lot of cases I can think of where it can be useful to have a combination of components assigning sentence boundaries.

In particular, I can imagine a case where the `sentencizer` is applied to a small set of custom punctuation (like custom section or paragraph separators) and either the `SentenceRecognizer` or the `parser` is used for the remaining boundaries.

And I think that as long as the `parser` is primarily improving recall for sentence boundaries that the other components miss, it makes sense to have the other components with `None` as the default so that people who add a parser to a pipeline end up with the parser's improved sentence boundaries at the end of the pipeline even if they've added other components before the parser that may also set sentence boundaries.

**Comment by DomHudson** [comment] 2020-02-24 09:37
In my opinion the combination of `{None, True, False}` is not transparent or flexible enough to provide the information that it is currently trying to captured. It is likely to cause problems as it would be entirely reasonable to expect `True` to indicate a sentence boundary and `False` otherwise - a clean API should be self-explanatory. 

I think the best approach is to have this attribute as a boolean (no None-types allowed) once the sentence boundaries have been set and None-type otherwise. If there is a desire to allow more complex stacking of pipelines and pipeline-units then a more complete history should be kept, for example a `SentenceBoundaryBoolean` object could be created which mimics `True` or `False` but also allows the state of certain tokens to be altered after their initial creation and retains the history of the model that caused the latest change. This would provide much more flexibility and explainability than the limited `{True, False, None}`.

What do you think?

**Comment by adrianeboyd** [comment] 2020-02-24 17:25
Thanks for the feedback! I'll add your suggestions to #4775.

**Comment by DomHudson** [comment] 2020-02-26 10:19
Thanks! In the mean time, should we change the documentation? Regarding `is_sent_start` it currently says:

> A boolean value indicating whether the token starts a sentence. `None` if unknown. Defaults to `True` for the first token in the `Doc`.

I think something like this is more accurate:

Indicates whether the token starts a sentence. This is `True` for the first token in each sentence and `None` otherwise. `None` if unknown. Defaults to `True` for the first token in the `Doc`.

**Comment by honnibal** [comment] 2020-05-20 16:35
> I think the best approach is to have this attribute as a boolean (no None-types allowed) once the sentence boundaries have been set and None-type otherwise. If there is a desire to allow more complex stacking of pipelines and pipeline-units then a more complete history should be kept, for example a SentenceBoundaryBoolean object could be created which mimics True or False but also allows the state of certain tokens to be altered after their initial creation and retains the history of the model that caused the latest change. This would provide much more flexibility and explainability than the limited {True, False, None}.

> What do you think?

In theory I sort of agree, but the problem is performance matters. The strategy you suggest is simply not viable -- you're adding an extra object on every token, with multiple other objects for the history. This absolutely cannot work, both for the specific case and for the general pattern of the library.

The ternary system (true, false, none) is a compromise, and I'll consider an alternative strategy that can fit in one `int32_t`. I actually can't think of something that's a useful improvement on the ternary system within that constraint -- I'd say ternary's an improvement on binary, at least.

I do think the documentation is correct:

> A boolean value indicating whether the token starts a sentence. None if unknown. Defaults to True for the first token in the Doc.

That's what the value reflects, the confusion is only about how different components should set the values.

**Comment by svlandeg** [comment] 2020-07-03 09:18
Closing this and merging with Issue #4775 to centralize discussion there.

**Closed by svlandeg** 2020-07-03 09:18 UTC
Labels: feat / doc
