### ISSUE TITLE
Inconsistent "dative" dependency?

### ISSUE THREAD

**Issue by justinbhopper** [explosion/spaCy#8440] opened 2021-06-20 16:03 UTC
In the examples below, I would expect the word "**to**" to be a "**dative**" dependency in every case.  
However, instead "**to**" is getting marked as a prepositional modifier ("**prep**") with most verbs.  So far I have only found "give" and "send" result in dative.  

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp("I took the results to the mother.")
print(doc[4].dep_) # "prep"

doc = nlp("I gave the results to the mother.")
print(doc[4].dep_) # "dative"

doc = nlp("I sent the results to the mother.")
print(doc[4].dep_) # "dative"

doc = nlp("I emailed the results to the mother.")
print(doc[4].dep_) # "prep"
```

Is this expected?  Is there a linguistic rationale behind the different results, or is there just a limit on how well spaCy can detect the dative case?

## Your Environment
* Operating System: Windows 10
* Python Version Used: Python 3
* spaCy Version Used: v3.0
* Environment Information: Binder

**Comment by polm** [comment] 2021-06-21 04:20
Moving this to a discussion since it's not a bug.

**Closed** 2021-06-21 04:20 UTC
