### ISSUE TITLE
TypeError for sentences' noun_chunks if "it_core_news_sm" is used

### ISSUE THREAD

**Issue by sotnyk** [explosion/spaCy#3199] opened 2019-01-26 10:20 UTC
## How to reproduce the behaviour

```
import spacy
from spacy.lang.it.examples import sentences as sents_it
from spacy.lang.fr.examples import sentences as sents_fr

fr_nlp = spacy.load('fr_core_news_sm')
fr_doc = fr_nlp(sents_fr[0])

it_nlp = spacy.load('it_core_news_sm')
it_doc = it_nlp(sents_it[0])

print(list(list(fr_doc.sents)[0].noun_chunks))
print(list(list(it_doc.sents)[0].noun_chunks))
```

For French (also have been checked small English and German vocabularies) we get:

> [de dollard]

For Italian:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-5-03cc3443c5ec> in <module>
----> 1 list(list(it_doc.sents)[0].noun_chunks)

span.pyx in __get__()

TypeError: 'NoneType' object is not callable
```

Additional issue:

it_doc.noun_chunks simple returns empty list without any elements. But one or more noun chunks is expected.

## Info about spaCy

* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.6.8

**Comment by ines** [comment] 2019-01-26 13:01
Thanks for the report – I really thought we had this fixed in the nightly, but I was able to reproduce the error there as well. 

The problem is that Italian doesn't have a noun chunk iterator and spaCy doesn't fail gracefully here. For `Doc` objects, I think we already fixed this – but the sentences in `doc.sents` are `Span` objects, and it seems like `Span.noun_chunks` still defaults to `None` for the noun chunks iterator (instead of just returning no noun chunks).

**Comment by sotnyk** [comment] 2019-01-27 17:45
@ines , Thank you for explanation.

So, I should implement noun chunks recognition in Italian texts "by hand", using POS tagging feature.

**Comment by ines** [comment] 2019-01-30 21:37
If you do end up implementing Italian noun chunks, that'd be really cool and we'd definitely appreciate a pull request 🙂 (Maybe you can take inspiration from one of the other languages, like Spanish?)

In the meantime, fixing `Span.noun_chunks` like `Doc.noun_chunks` (if no noun chunks are available) should also solve this and prevent spaCy from raising an error.

**Closed** 2019-02-08 17:33 UTC
Labels: bug, feat / doc, help wanted, help wanted (easy)
