### ISSUE TITLE
spaCy dll falied

### ISSUE THREAD

**Issue by barakm123** [explosion/spaCy#1027] opened 2017-04-28 06:18 UTC
Hey there,

I installed spaCy "pip install spacy" it's looks ok but when i import it by "import spacy" i get DLL error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Anaconda3\lib\site-packages\spacy\__init__.py", line 4, in <module>
    from . import util
  File "C:\Users\User\Anaconda3\lib\site-packages\spacy\util.py", line 5, in <module>
    import regex as re
  File "C:\Users\User\Anaconda3\lib\site-packages\regex.py", line 394, in <module>
    import _regex_core
  File "C:\Users\User\Anaconda3\lib\site-packages\_regex_core.py", line 21, in <module>
    import _regex
ImportError: DLL load failed: The specified procedure could not be found.

my python is : 
"Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32"

Thanks!

Best regards, barak

**Comment by CpuKnows** [comment] 2017-05-09 03:27
I had this issue as well, but it was fixed after I created a conda environment [1] and specificed *python=3*.

>conda create --name py36 python=3

This command installed a few new packages:
* pip: 9.0.1-py36_1
* python: 3.6.1-0
* setuptools: 27.2.0-py36_1
* vs2015_runtime: 14.0.25123-0
* wheel: 0.29.0-py36_0

I suspect the installation of *vs2015_runtime* is what fixed this issue, but I haven't done a root cause analysis. Visual Studio is mentioned in the Windows installation section [2]

[1] https://conda.io/docs/using/envs.html#create-a-separate-environment
[2] https://spacy.io/docs/usage/#source-windows

**Comment by ines** [comment] 2017-05-10 15:46
Thanks a lot for sharing your solution and analysis!
This definitely makes sense – closing this issue now, but if the error persists, feel free to reopen.

**Comment by johnkabler** [comment] 2017-05-16 17:33
I have the same exact issue, and this didn't do anything to fix it.  The only environment I have on the machine is Python 3.  I've previously had no issue installing Spacy on windows before.  

If I could, I'd simply use a Linux box, but this is a project for an integration with enterprise software which is windows only.  

I already have VS and C++ tools on the machine, and other non-Spacy tools build without issue.  This issue should be reopened.  

CpuKnows' answer, while appreciated, didn't work, and it shouldn't be accepted.  I love Spacy, and I'm happy to help with root cause analysis whenever you'd like.

**Closed** 2017-05-17 08:56 UTC
Labels: install, windows

**Comment by eugene-yang** [comment] 2017-05-25 15:51
I also run into this issue. I'm currently using anaconda also and the environment is exactly the same as @CpuKnows had mentioned. I cannot install it as well. 

OS: Windows 10 
Python: 3.6.0
Anaconda: 5.1.0

The following is the error message I got.

```
 Failed building wheel for spacy
  Running setup.py clean for spacy
Failed to build spacy
Installing collected packages: spacy
  Running setup.py install for spacy ... error
    Complete output from command C:\Users\eugene\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\eugene\\AppData\\Local\\Temp\\pip-build-ksb29oc8\\spacy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\eugene\AppData\Local\Temp\pip-7wwgngv6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'spacy.parts_of_speech' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\eugene\Anaconda3\include -IC:\Users\eugene\AppData\Local\Temp\pip-build-ksb29oc8\spacy\include -IC:\Users\eugene\Anaconda3\include -IC:\Users\eugene\Anaconda3\include /EHsc /Tpspacy/parts_of_speech.cpp /Fobuild\temp.win-amd64-3.6\Release\spacy/parts_of_speech.obj /Ox /EHsc /openmp
    parts_of_speech.cpp
    c1xx: fatal error C1083: Cannot open source file: 'spacy/parts_of_speech.cpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2
```

I also tried the un-official version of wheel files that many developer who don't want to build the wheel on Windows by themselves would use. [http://www.lfd.uci.edu/~gohlke/pythonlibs/](http://www.lfd.uci.edu/~gohlke/pythonlibs/)

I can install it successfully but I would run into the DLL problem when running download en.

Here is the error messages:

```
Traceback (most recent call last):
  File "C:\Users\eugene\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\eugene\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\eugene\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\eugene\Anaconda3\lib\site-packages\spacy\__init__.py", line 4, in <module>
    from . import util
  File "C:\Users\eugene\Anaconda3\lib\site-packages\spacy\util.py", line 5, in <module>
    import regex as re
  File "C:\Users\eugene\Anaconda3\lib\site-packages\regex.py", line 394, in <module>
    import _regex_core
  File "C:\Users\eugene\Anaconda3\lib\site-packages\_regex_core.py", line 21, in <module>
    import _regex
ImportError: DLL load failed: The specified procedure could not be found.
```

Thank you :)

**Comment by cgohlke** [comment] 2017-05-25 17:40
> `ImportError: DLL load failed: The specified procedure could not be found.`

This looks like [Python issue 29943](https://bugs.python.org/issue29943).

**Comment by eugene-yang** [comment] 2017-05-26 08:10
@cgohlke thank you :)
I just updated to 3.6.1 and it works great now
