### ISSUE TITLE
SSL Certificate Validation Failed

### ISSUE THREAD

**Issue by jbullen94** [explosion/spaCy#9131] opened 2021-09-03 08:52 UTC
## How to reproduce the behaviour
follow instructions on the guide for downloading models. 
```
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
```
The output of which based on my environment is:
```
pip install -U pip setuptools wheel
Requirement already satisfied: pip in c:\python39\lib\site-packages (21.2.4)
Requirement already satisfied: setuptools in c:\python39\lib\site-packages (57.4.0)
Requirement already satisfied: wheel in c:\python39\lib\site-packages (0.37.0)
PS C:\dev> pip install -U spacy
Requirement already satisfied: spacy in c:\python39\lib\site-packages (3.1.2)
Requirement already satisfied: pathy>=0.3.5 in c:\python39\lib\site-packages (from spacy) (0.6.0)
Requirement already satisfied: thinc<8.1.0,>=8.0.8 in c:\python39\lib\site-packages (from spacy) (8.0.8)
Requirement already satisfied: packaging>=20.0 in c:\python39\lib\site-packages (from spacy) (21.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in c:\python39\lib\site-packages (from spacy) (1.8.2)
Requirement already satisfied: jinja2 in c:\python39\lib\site-packages (from spacy) (3.0.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\python39\lib\site-packages (from spacy) (2.26.0)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in c:\python39\lib\site-packages (from spacy) (0.3.2)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in c:\python39\lib\site-packages (from spacy) (0.7.4)
Requirement already satisfied: numpy>=1.15.0 in c:\python39\lib\site-packages (from spacy) (1.21.2)
Requirement already satisfied: setuptools in c:\python39\lib\site-packages (from spacy) (57.4.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.7 in c:\python39\lib\site-packages (from spacy) (3.0.8)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in c:\python39\lib\site-packages (from spacy) (0.8.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.4 in c:\python39\lib\site-packages (from spacy) (2.0.6)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\python39\lib\site-packages (from spacy) (2.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\python39\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in c:\python39\lib\site-packages (from spacy) (2.4.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\python39\lib\site-packages (from spacy) (4.62.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\python39\lib\site-packages (from spacy) (3.0.5)
Requirement already satisfied: pyparsing>=2.0.2 in c:\python39\lib\site-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in c:\python39\lib\site-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\python39\lib\site-packages (from pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4->spacy) (3.10.0.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jbullen\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jbullen\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python39\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: colorama in c:\users\jbullen\appdata\roaming\python\python39\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.3)
Requirement already satisfied: click<7.2.0,>=7.1.1 in c:\python39\lib\site-packages (from typer<0.4.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python39\lib\site-packages (from jinja2->spacy) (2.0.1)
PS C:\dev> python -m spacy download en_core_web_sm
Traceback (most recent call last):
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\jbullen\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Python39\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python39\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Python39\lib\site-packages\spacy\cli\download.py", line 35, in download_cli
    download(model, direct, sdist, *ctx.args)
  File "C:\Python39\lib\site-packages\spacy\cli\download.py", line 67, in download
    compatibility = get_compatibility()
  File "C:\Python39\lib\site-packages\spacy\cli\download.py", line 78, in get_compatibility
    r = requests.get(about.__compatibility__)
  File "C:\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

## Your Environment
output from spacy info. Currently running Powershell as Admin.
- **spaCy version:** 3.1.2
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.9.2

**Comment by polm** [comment] 2021-09-04 05:14
Moving to Discussions since this is not a bug.

**Closed** 2021-09-04 05:14 UTC
