### ISSUE TITLE
OSError: [E050] Can't find model 'es_core_news_sm'

### ISSUE THREAD

**Issue by Catalina1100** [explosion/spaCy#8877] opened 2021-08-03 17:41 UTC
Hi!

I was trying to load the Spanish model in Google Collab and got this error.

**OSError: [E050] Can't find model 'es_core_news_sm'**

Here is the code I used:

#!spacy download es_core_news_sm
import spacy

nlp = spacy.load("es_core_news_sm")
doc = nlp("Sevilla es una maravilla.")
for token in doc:
    print(token.text)

Does anyone know how I couldfix it, please? 

Cheers,
Katerina

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by munhouiani** [comment] 2021-08-03 18:08
Did you download the Spanish model before?

`!python -m spacy download es_core_news_sm`

**Comment by Catalina1100** [comment] 2021-08-03 19:06
Yes, I did download it. Thanks. Is there anything else I missed?

**Comment by munhouiani** [comment] 2021-08-03 22:31
You should be able to load the model now
```
nlp = spacy.load("es_core_news_sm")
```

**Comment by polm** [comment] 2021-08-04 03:39
Since this is not a bug report but an installation issue I'll be moving it to Discussions...

**Closed** 2021-08-04 03:39 UTC
