### ISSUE TITLE
Error when pretraining using spacy 3.0

### ISSUE THREAD

**Issue by codester13** [explosion/spaCy#7677] opened 2021-04-07 11:33 UTC
Pretraining custom weights in Spacy pipeline gives error.

When I run this using a jupyter notebook:

`!python -m spacy pretrain config.cfg ./output_pretrain --paths.raw_text ./data.jsonl `

The following error occurs: 
```
[i] Using CPU
[i] Loading config from: config.cfg
[x] Error parsing config overrides
paths -> raw_text   not a section value that can be overwritten
```

## Your Environment

- Operating System: Windows 10.0.19041
- Python Version Used: 3.8.8
- spaCy Version Used:3.0.5

**Comment by polm** [comment] 2021-04-08 04:36
Closing as duplicate of #7679, please don't double-post.

**Closed by polm** 2021-04-08 04:36 UTC
