### ISSUE TITLE
Token-based matching: Exclude token in pattern from matches

### ISSUE THREAD

**Issue by marijnfer** [explosion/spaCy#6492] opened 2020-12-03 15:26 UTC
I have the following rule: 
[{"LOWER": {"IN": ["born"]}, "OP": "!"}, {"LOWER": "on"}, {"ENT_TYPE": "Date"}]

The goal of this rule is to detect _on date_ without born before it, however I'm not interested in the first token. 

Is it possible to ignore this token, or to provide a blacklist of tokenpatterns to the ruler, to prevent a match on _born on date_ and_ add [ {"LOWER": "on"}, {"ENT_TYPE": "Date"}] to the regular ruleset. Any solution is welcome.

**Comment by adrianeboyd** [comment] 2020-12-04 10:01
This looks like a duplicate of #6420, let's merge it with that issue.

**Closed by adrianeboyd** 2020-12-04 10:01 UTC
Labels: feat / matcher
