### ISSUE TITLE
NER Training on GPU is not reproducible

### ISSUE THREAD

**Issue by FrancescoCasalegno** [explosion/spaCy#7981] opened 2021-05-03 10:22 UTC
## Description

Running a simple NER training (see next section) on GPU gives results that vary from run to run.
Notice that  running the very same thing on CPU gives instead consistent results.

 In particular, the content of `model-best/` and `model-last` (i.e. both the `meta.json` and the `ner/model` produced as an output of the training) have different contents in different runs.

The differences in the `meta.json` mainly seem to affect the loss function:
          <img width="550" alt="Screenshot 2021-04-30 at 19 54 53" src="https://user-images.githubusercontent.com/17013890/116734937-27cd2b00-a9ee-11eb-9c64-fa19a656351f.png">
          <img width="550" alt="Screenshot 2021-04-30 at 19 55 15" src="https://user-images.githubusercontent.com/17013890/116734943-2ac81b80-a9ee-11eb-86d3-ec1916696fc3.png">

## How to reproduce the behaviour
I executed the following command — using `--gpu-id -1` to run on CPU, `--gpu-id -1` to run on GPU.
```
python -m spacy train \
    config.cfg \
    --gpu-id 0 \  # set to -1 to train on CPU
```
The config.cfg reads as follows:

```
[paths]
train = annotations.train.spacy
dev = annotations.dev.spacy
base_model = "en_ner_craft_md"

[system]
gpu_allocator = null
seed = 2

[nlp]
lang = "en"
pipeline = ["tok2vec", "tagger", "attribute_ruler", "lemmatizer", "parser", "ner"]
batch_size = 32
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null

[nlp.tokenizer]
@tokenizers = "spacy.Tokenizer.v1"

[components]

[components.tok2vec]
source = ${paths.base_model}

[components.tagger]
source = ${paths.base_model}

[components.attribute_ruler]
source = ${paths.base_model}

[components.lemmatizer]
source = ${paths.base_model}

[components.parser]
source = ${paths.base_model}

[components.ner]
source = ${paths.base_model}

[corpora]

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
train_corpus = "corpora.train"
dev_corpus = "corpora.dev"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.2
accumulate_gradient = 1
patience = 0
max_epochs = 6
max_steps = 20000
eval_frequency = 10
frozen_components =  ["tok2vec", "tagger", "attribute_ruler", "lemmatizer", "parser"]
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = true

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
tag_acc = null
lemma_acc = null
dep_uas = null
dep_las = null
dep_las_per_type = null
sents_f = null
sents_p = null
sents_r = null
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]

[initialize]
vectors = null
init_tok2vec = null
vocab_data = null
lookups = null
after_init = null
components = {}
tokenizer = {}

[initialize.before_init]
@callbacks = "spacy.copy_from_base_model.v1"
tokenizer = ${paths.base_model}
vocab = ${paths.base_model}
```

## Your Environment

* Operating System: `Ubuntu 18.04.5 LTS (Bionic Beaver)`
* Python Version Used: `Python 3.7.5`
* spaCy Version Used: `spacy[cuda102]==3.0.6`
* Environment Information: running with CUDA `V10.2.89`

**Comment by svlandeg** [comment] 2021-05-03 12:51
Thanks for the report. Just to make sure I'm on the same page: you are getting different results if you perform multiple GPU training runs, with the same seed, of a tok2vec-based NER pipeline (i.e. no transformers)?

Could you do me a favor, if you have `spacy` installed from source? There's a test in `spacy/tests/parser/test_ner.py` called `test_overfitting_IO` that (also) tests reproducibility. It should definitely go green as is. But you can add `require_gpu()` at the start and run the test again. Does this succeed on your system or fail? (it succeeds on mine).

**Comment by svlandeg** [comment] 2021-05-03 12:59
Also: probably duplicate of https://github.com/explosion/spaCy/issues/6490. I'll look into this.

**Comment by FrancescoCasalegno** [comment] 2021-05-03 13:57
Dear @svlandeg,

Thanks for looking into this!

Reproducibility seems to be one of the strongest points I love about `spacy` and it is definitely a must-have for my project.

>  you are getting different results if you perform multiple GPU training runs, with the same seed, of a tok2vec-based NER pipeline (i.e. no transformers)?

**Yes.** The observed issue is unrelated to transformers since I am using a `tok2vec` component (see `config.cfg` file above for more details).


> There's a test in `spacy/tests/parser/test_ner.py` called `test_overfitting_IO` that (also) tests reproducibility. It should definitely go green as is. [...]

**Yes, I can confirm that the test passes in my environment, also when running on GPU.** I just launched the test, with and without an extra `spacy.require_gpu()` line just after the function signature:
https://github.com/explosion/spaCy/blob/e99ff6f2554f915c8c3543659f89d8b2c42496a0/spacy/tests/parser/test_ner.py#L305

> probably duplicate of #6490.

Notice that that issue is referred to `spacy 2.x`, while this issue is for `spacy 3.x`. But maybe the underlying issues are indeed related.

**Comment by FrancescoCasalegno** [comment] 2021-05-17 09:16
Hello @svlandeg,

Did you have a chance to have a look at this issue in the last weeks?
Are there any updates?

Thanks in advance!

**Comment by FrancescoCasalegno** [comment] 2021-05-25 14:27
Hi @svlandeg,

Any news on this? Sorry for being annoying, I just hoped you guys could find a fix, since GPU training is a key element for our work!

Thanks :)

—Francesco

**Comment by polm** [comment] 2021-08-09 11:46
I managed to track down the source of this issue, though it's not something we can fix right away. For details see #6490. 

Since this is the same problem as the earlier issue I'm going to close this as a duplicate.

**Closed by polm** 2021-08-09 11:46 UTC
Labels: training, gpu, feat / ner
