### ISSUE TITLE
Spacy convert not writing files larger than 2 GB.

### ISSUE THREAD

**Issue by buriy** [explosion/spaCy#6117] opened 2020-09-22 18:04 UTC
Copy some conllu file over and over into some file.
Then run "spacy convert" it to json.
You'll see output file size is about 2147479553 or so.

## Your Environment

* Operating System: Linux Ubuntu 18.04
* Python Version Used: 3.7 and 3.8
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment] 2020-09-23 06:30
I know there's a hard-coded size limit for msgpack files (you'll get an error), but I'm not sure what the situation is for JSON. Your impression is that there's no error and the file just ends up truncated?

You shouldn't need to generate one huge JSON file, though. `spacy train` and similar commands will recurse through a provided directory to load any `.json` files, so you can create a large corpus out of smaller files.

**Comment by buriy** [comment] 2020-09-23 09:08
Not sure how it truncates the file but it appears to work correctly.
650mb conllu -> 2gb json,
1300mb conllu -> 2.1gb json,
2600mb conllu -> 2.1gb json,
and it trains correctly.

(I was checking how the resulting quality changes when you change the dataset size)

Thanks, I'll move to the list of smaller files, but this issue should be at least reported and a error should appear when it happens.

**Comment by buriy** [comment] 2020-09-23 10:41
Yes the files are truncated indeed.

**Comment by adrianeboyd** [comment] 2020-09-24 06:00
Okay, I'll mark this as a bug. It's probably something that needs to be addressed in `srsly`.

**Comment by honnibal** [comment] 2020-09-24 22:08
Yeah it'll be some limit deep inside ujson I guess. You shouldn't want to do this though? Large json files are pretty painful, just split things up more.

**Comment by adrianeboyd** [comment] 2020-09-25 13:05
Yeah, I think we need `srsly` to detect when this limit is hit so there's an error message. I didn't immediately see where the limit was defined or where it was truncating, though.

**Comment by buriy** [comment] 2020-09-25 15:58
It breaks on the end of the line in both cases, and files are slightly less 2GB, so I believe you should have something like
signed_int32 x;
if ... x + len(line) ...
near write_line(line)

**Comment by polm** [comment] 2021-05-24 08:49
So I've been taking a look at this and I'm not sure what's going on.

I've had trouble reproducing the problem directly - if I try to load a 1.3GB CoNLL file I get out of memory errors and it crashes other processes on my machine. So I changed direction and checked ujson and srsly. 

I used this script to generate a large json file, but whether using ujson or srsly I was able to write a file well over 2GB without issue. With the current setting it'll be over 3GB. 

```
import ujson
import srsly

text = "x" * 128
biglist = [text] * 30000000

srsly.write_json("blarg.json", biglist)
```

So this doesn't appear to be a built-in limit of ujson or srsly. On the other hand I can't imagine something before the serialization code causing it to get cut off at a fixed file size. I guess I'm curious if anyone else can reproduce this issue.

**Comment by polm** [comment] 2021-05-28 05:31
Since I have not been able to reproduce this issue, we've had no other reports of it, and there's an obvious workaround for the case where it was reported, I'm going to mark it as resolved, but if anyone has more information or another instance of it please feel free to reply or open a new issue.

**Closed by polm** 2021-05-28 05:31 UTC
Labels: bug, feat / cli, feat / ux
