### ISSUE TITLE
update error messaging 'Microsoft Visual C++ 14.0 is required.' on Windows-- 64 bit is a better solution

### ISSUE THREAD

**Issue by fschwiet** [explosion/spaCy#5869] opened 2020-08-03 19:24 UTC
## Feature description

Please update the install scripts to check warn for 32 bit python on windows that 64 bit is preferred as an alternative to trying to install visual c++ 14.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

I don't think so.

## explanation

First, I knew nothing about python or pip before today but I was able to get spacy running, so I want to thank you for getting things set up well.  The only issue I had was being thrown off by the "Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"" messaging.  I couldn't find the components referenced in visual studio installer, tried a few unsuccessfully, googling the error message took me down a rabbit hole.  Eventually I found this gem: https://github.com/explosion/spaCy/issues/5769#issuecomment-660165758.  The comment indicated I just needed an 64 install of python on Windows, and once I reinstalled python as 64 bit everything went smoothly.

I imagine it would help others to update the message to indicate 64 bit python is preferred.  python.org's download page for windows leans toward 32 bit, so I doubt 32 bit installs are rare.

thank you

**Comment by honnibal** [comment] 2020-08-12 13:50
This is a very good point, and in fact even more confusing errors than the MSVC 14.0 error you saw are possible. And unfortunately this often affects users who've never even had to deal with compiler toolchains before...

The problem is that the code-path is kind of hard to control: the error is triggered within setuptools. I suppose we can make an explicit 32-bit check within the `setup.py`, and raise an error there? Errors raised within the setup process don't display fantastically well, but it'd be better than the current one for sure.

**Comment by fschwiet** [comment] 2020-08-12 20:49
Sounds reasonable to me.

**Comment by wanyujiang** [comment] 2020-09-17 13:15
Hi,I meet the same problem when I use 'pip install f:\pylibtiff-0.4.2-cp37-cp37m-win_amd64.whl', but the way you suggest is not working, because I am in python64,win10 64, is there any other way to solve this problem?

**Comment by polm** [comment] 2021-05-31 05:45
Thanks for the report on this. For now what we've done is added an entry to our [installation FAQ](https://github.com/explosion/spaCy/discussions/8226) recommending using 64bit instead, with a link to this thread. 

I'm going to close this because it seems there's nothing else we need to do right now. I think this will be less of an issue over time as 32bit support becomes increasingly less important, but we can revisit this if there's some reason to later.

-----

@wanyujiang It's not really appropriate to ask about an unrelated project here, and it's been a long time since your question, but you should try installing the latest [Microsoft Visual C++ Redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0). If that doesn't work I don't know how to help you.

**Closed by polm** 2021-05-31 05:45 UTC
Labels: enhancement, feat / ux, help wanted, install, windows
