### ISSUE TITLE
nlp.pipe(n_processes=x) does not work with token._.attribute

### ISSUE THREAD

**Issue by theudas** [explosion/spaCy#4737] opened 2019-11-30 15:59 UTC
## How to reproduce the behaviour
I have a pipeline that sets some custom .\_.attribute.
If I run my pipeline with nlp.pipe(texts, n_processes=16) it forgot that any of my custom.\_.attributes do exist:

Traceback (most recent call last):
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 1124, in _apply_pipes
    sender.send([doc.to_bytes() for doc in docs])
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 1124, in <listcomp>
    sender.send([doc.to_bytes() for doc in docs])
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 1105, in _pipe
    for doc in docs:
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 1106, in _pipe
    doc = proc(doc, **kwargs)
  File "C:\python\pipeline\pipeline\modules\module_inherited.py", line 26, in __call__
    self.apply(doc, p)
  File "C:\python\pipeline\pipeline\modules\module_base.py", line 28, in apply
    token._.affirmed = category == 0
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\tokens\underscore.py", line 63, in __setattr__
    raise AttributeError(Errors.E047.format(name=name))
AttributeError: [E047] Can't assign a value to unregistered extension attribute 'affirmed'. Did you forget to call the `set_extension` method?

My guess is, that during the pickle process the custom attributes are getting lost.

## Info about spaCy
* **spaCy version:** 2.2.3
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4

**Comment by ines** [comment] 2019-12-01 22:10
Thanks for the report. Could you share a small reproducible example of the code you're running?

**Comment by theudas** [comment] 2019-12-02 12:57
Hey   @ines , here you go:
```
import spacy
from spacy.tokens import Token

# Load Model 
nlp = spacy.load("de_core_news_md")

# Add Awesome Extension
Token.set_extension("awesome", default=False, force=True)
print("Trying single document:\n")
# Make Pipeline for Awesome
def is_awesome(doc):
    for token in doc:
        if token.lemma_ in ["Python", "Katze", "Spacy"]:
            token._.awesome = True
    return doc

nlp.add_pipe(is_awesome)

# This will work
doc = nlp("Ich mag Katzen und Tee.")
for token in doc:
    if token._.awesome:
        print(token)
    
# This will work as well
print("Doing regular piping:\n")
texts = ["Ich mag Katzen und Tee.", "SpaCy ist meine Lieblingslibrary in Python", "hat jemand meine Katze gesehen?"]
docs = nlp.pipe(texts)

for doc in docs:
    print()
    for token in doc:
        if token._.awesome:
            print(token)

print("Breaking Pipeline:\n")
# I broke the Pipeline
docs = nlp.pipe(texts, n_process=4)

for doc in docs:
    print()
    for token in doc:
        if token._.awesome:
            print(token)
```

**Comment by adrianeboyd** [comment] 2019-12-02 16:36
Just as a data point: I can't reproduce this problem (linux, v2.2.3 or develop).

**Comment by adrianeboyd** [comment] 2019-12-03 08:22
So the obvious reason for the windows vs. linux difference: it's due to spawn vs. fork. The newly spawned python processes in windows don't see the global `Token.set_extension()`. The attributes aren't lost, just whether the extension has been registered.

I think you'll need to set the extension within the pipeline for this to work with `spawn`, e.g.:

```
def is_awesome(doc):
    Token.set_extension("awesome", default=False, force=True)
    for token in doc:
        if token.lemma_ in ["Python", "Katze", "Spacy"]:
            token._.awesome = True
    return doc
```

**Comment by BramVanroy** [comment] 2019-12-03 08:31
When running the code as-is, I do get a different error that is related to spawning new process outside main, so I first had to change the code to:

```python
import spacy
from spacy.tokens import Token

if __name__ == '__main__':
    # Load Model
    nlp = spacy.load("de_core_news_md")

    # Add Awesome Extension
    Token.set_extension("awesome", default=False, force=True)
    print("Trying single document:\n")


    # Make Pipeline for Awesome
    def is_awesome(doc):
        for token in doc:
            if token.lemma_ in ["Python", "Katze", "Spacy"]:
                token._.awesome = True
        return doc


    nlp.add_pipe(is_awesome)

    # This will work
    doc = nlp("Ich mag Katzen und Tee.")
    for token in doc:
        if token._.awesome:
            print(token)

    # This will work as well
    print("Doing regular piping:\n")
    texts = ["Ich mag Katzen und Tee.", "SpaCy ist meine Lieblingslibrary in Python", "hat jemand meine Katze gesehen?"]
    docs = nlp.pipe(texts)

    for doc in docs:
        print()
        for token in doc:
            if token._.awesome:
                print(token)

    print("Breaking Pipeline:\n")
    # I broke the Pipeline
    docs = nlp.pipe(texts, n_process=4)

    for doc in docs:
        print()
        for token in doc:
            if token._.awesome:
                print(token)

```

After changing that, I can indeed reproduce your issue on Windows.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python\Python37\Lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'is_awesome' on <module '__mp_main__' from 'C:\\Users\\bmvroy\\.PyCharm2019.2\\config\\scratches\\scratch_27.py'>
```

* **spaCy version:** 2.2.3
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3

**Comment by theudas** [comment] 2019-12-14 11:59
I am still getting errors everywhere.

```
nlp = spacy.load("de_core_news_md", disable=["ner"])
docs = nlp.pipe(all_texts, n_process=8)    
for doc in tqdm(docs):
    # do something
```

0it [00:00, ?it/s]Traceback (most recent call last):
  File "tagger.py", line 57, in <module>
    for doc in tqdm(docs):
  File "C:\Users\psodm\Anaconda3\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 816, in pipe
    for doc in docs:
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 859, in _multiprocessing_pipe
    proc.start()
    -> <Process(Process-1, initial)>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
    |             |           -> <Process(Process-1, initial)>
    |             -> <Process(Process-1, initial)>
    -> <Process(Process-1, initial)>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           |                                             -> <Process(Process-1, initial)>
           -> <multiprocessing.context.DefaultContext object at 0x000002196C18A688>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
           |     -> <Process(Process-1, initial)>
           -> <class 'multiprocessing.popen_spawn_win32.Popen'>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
    |              |            -> <_io.BufferedWriter name=4>
    |              -> <Process(Process-1, initial)>
    -> <module 'multiprocessing.reduction' from 'C:\\Users\\psodm\\Anaconda3\\lib\\multiprocessing\\reduction.py'>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
    |              |     |              -> <Process(Process-1, initial)>
    |              |     -> None
    |              -> <_io.BufferedWriter name=4>
    -> <class 'multiprocessing.reduction.ForkingPickler'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               |     -> 3
               -> <function _main at 0x00000260A02EB318>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
    |       -> {'log_to_stderr': False, 'authkey': b'\xe4\x8eQ\xcbH\x93&\xe1_\xc1\x8e\x94V\x9d\x93HC4"k\xff\x97\xa2}\xf3z\xe6K\xd0\xf3\x1d\x02'...
    -> <function prepare at 0x00000260A02EB4C8>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    |                     -> {'log_to_stderr': False, 'authkey': b'\xe4\x8eQ\xcbH\x93&\xe1_\xc1\x8e\x94V\x9d\x93HC4"k\xff\x97\xa2}\xf3z\xe6K\xd0\xf3\x1d\x02'...
    -> <function _fixup_main_from_path at 0x00000260A02EB5E8>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\psodm\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\psodm\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\psodm\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__mp_main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'C:\\python\\m...
         -> <code object <module> at 0x00000260A022D390, file "C:\python\med2vec\tagger.py", line 7>
  File "C:\python\med2vec\tagger.py", line 57, in <module>
    for doc in tqdm(docs):
  File "C:\Users\psodm\Anaconda3\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 816, in pipe
    for doc in docs:
  File "C:\Users\psodm\Anaconda3\lib\site-packages\spacy\language.py", line 859, in _multiprocessing_pipe
    proc.start()
    -> <Process(Process-1, initial)>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
    |             |           -> <Process(Process-1, initial)>
    |             -> <Process(Process-1, initial)>
    -> <Process(Process-1, initial)>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           |                                             -> <Process(Process-1, initial)>
           -> <multiprocessing.context.DefaultContext object at 0x00000260A0246C88>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
           |     -> <Process(Process-1, initial)>
           -> <class 'multiprocessing.popen_spawn_win32.Popen'>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                |                          -> <Process(Process-1, initial)>
                -> <module 'multiprocessing.spawn' from 'C:\\Users\\psodm\\Anaconda3\\lib\\multiprocessing\\spawn.py'>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
    -> <function _check_not_importing_main at 0x00000260A02EB3A8>
  File "C:\Users\psodm\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by BramVanroy** [comment] 2019-12-14 13:28
The error is the same as I said before. It tells you exactly what is wrong...

You have to put your code in the if-main block:

```python
# your imports here
# your functions here
if __name__ == '__main__':
    # your initializing code here
```

**Comment by adrianeboyd** [comment] 2019-12-16 08:08
I hope the spacy-related issues have been resolved, so I'm going to close this, thanks!

**Closed by adrianeboyd** 2019-12-16 08:08 UTC
Labels: feat / pipeline, usage
