### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by kurodenjiro** [explosion/spaCy#4984] opened 2020-02-08 03:34 UTC
File "wikidata_train_entity_linker.py", line 172, in <module>
    plac.call(main)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 137, in main
    docs, golds = zip(*train_batch)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by svlandeg** [comment] 2020-02-09 11:52
This looks like the `train_batch` argument is empty. Could you paste the commands you ran, the logs that were produced, and the full error stack?

Likely caused by issue https://github.com/explosion/spaCy/issues/4982 you opened earlier?

**Comment by kurodenjiro** [comment] 2020-02-10 02:00
ok let me try

**Comment by kurodenjiro** [comment] 2020-02-11 14:36
i fix it but it still error i dont understand why ? 
root@PC1096:/mnt/e/project/spacy_1/bin/wiki_entity_linking# python3 wikidata_train_entity_linker.py kb-data/ -o ./new-model
2020-02-11 16:45:45,942 - INFO - __main__ - Creating Entity Linker with Wikipedia and WikiData
2020-02-11 16:45:45,943 - INFO - __main__ - STEP 1a: Loading model from kb-data/nlp_kb
2020-02-11 16:46:18,488 - INFO - __main__ - Original NLP pipeline has following pipeline components: ['tagger', 'parser', 'ner']
2020-02-11 16:46:18,489 - INFO - __main__ - STEP 1b: Loading KB from kb-data/kb
2020-02-11 16:46:18,654 - INFO - __main__ - STEP 2: Reading training & dev dataset from kb-data/gold_entities.jsonl

2020-02-11 16:46:34,159 - INFO - __main__ - Training set has 1589406 articles, limit set to roughly all articles per epoch
2020-02-11 16:46:34,160 - INFO - __main__ - Dev set has 177028 articles, limit set to rougly all articles for evaluation2020-02-11 16:46:34,160 - INFO - __main__ - STEP 3: Creating and training an Entity Linking pipe for 10 epochs
2020-02-11 16:46:35,433 - INFO - __main__ - Dev Baseline Accuracies:
Processing dev data:   0%|                                                                   | 0/177028 [00:00<?, ?it/s]

sudo npm install -g yarn
^[[B



2020-02-11 19:17:31,909 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Counts: {}
2020-02-11 19:17:31,910 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Random: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
2020-02-11 19:17:31,911 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Prior: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
2020-02-11 19:17:31,911 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Oracle: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
Traceback (most recent call last):
  File "wikidata_train_entity_linker.py", line 172, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 137, in main
    docs, golds = zip(*train_batch)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by kurodenjiro** [comment] 2020-02-11 14:39
Processing dev data: 0% always Zero for a long time . i dont know why ?

**Comment by kurodenjiro** [comment] 2020-02-11 15:51
![Untitled](https://user-images.githubusercontent.com/26534614/74252913-f43aae00-4d20-11ea-92bc-abcb1fc5bb49.png)
there is current version 2.2.3 . and still like that a

**Comment by svlandeg** [comment] 2020-02-12 07:47
Original issue seems to be solved, new issue has duplicate https://github.com/explosion/spaCy/issues/5003 so closing this one.

**Closed by svlandeg** 2020-02-12 07:47 UTC
Labels: feat / nel
