### ISSUE TITLE
Change CNN window size in entity recognizer

### ISSUE THREAD

**Issue by raghuapce** [explosion/spaCy#9382] opened 2021-10-06 10:05 UTC
@honnibal

The below links are not working. I would like to increase the CNN window size from 4 to 6 in entity recognizer in spacy v2 (2.2.4). Also, It would be great if you could document the working of Spacy entity recognizer in detail.

There's two places you could change this. One is the window size in the entity recognizer's CNN: https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L242 . The default setting is depth 4, which means the token's vector is sensitive to information from 4 words on either side.

The other place to change this is in the extraction of state tokens. I'm preparing something that explains this part of the procedure better. Implementation: https://github.com/explosion/spaCy/blob/master/spacy/syntax/_state.pxd#L130

This is not a part of the implementation I'm proud of... The entity recognizer uses the "6' case. You'll need to change the `nr_features` constant in `EntityRecognizer` within `pipeline.pyx` if you add more features (yeah, I know...). The features themselves aren't that satisfying for the entity recognizer. It feels like we should be able to make better use of the entity history.

_Originally posted by @honnibal in https://github.com/explosion/spaCy/issues/1532#issuecomment-343316068_

**Comment by polm** [comment] 2021-10-06 11:33
This is not a bug so I'm moving it to Discussions.

Also do not @ specific maintainers.

**Closed** 2021-10-06 11:33 UTC
Labels: v2
