### ISSUE TITLE
Retraining POS Tagger

### ISSUE THREAD

**Issue by inceatakan** [explosion/spaCy#6283] opened 2020-10-21 20:25 UTC
With sentences like "Love apples." and "Love MacBook Pro", where the Subject 'I' is missing, pos tagger is returning 'love' as Noun and Dependency Parser is returning it N-N compound. By correcting such examples in Prodigy, can I retrain Spacy's POS tagger?

**Comment by adrianeboyd** [comment] 2020-10-23 08:42
Yes, you can update the tagger with new examples. Be aware that you should provide a mixture of examples (not just the new examples) while training to avoid the catastrophic forgetting problem, or you model may start to perform incorrectly on other cases it used to get right. Here are basics on how to train and update models: https://spacy.io/usage/training

**Comment by inceatakan** [comment] 2020-10-23 18:17
Thank you very much @adrianeboyd!
 
I retrained the pos tagger with prodigy:

In Step 1 I labeled the a few examples ('love it.', 'I love it.', 'I love Spicy.', "Love Spacy.") with the following command, 

1. pos.teach new_pos_tags en_core_web_lg ./train_data.txt --label VERB,NOUN

and then retrained the model with the following code:

2. !python -m prodigy pos.batch_train new_pos_tags_3 en_core_web_lg --output ./tagger_model

QUESTION: How can I retrain the 'tagger_model' above? Do I first need to upload it as nlp object?

**Comment by adrianeboyd** [comment] 2020-10-29 14:25
The problem is that the underlying spacy tagger model that you're trying to update only really knows about the fine-grained tags. The coarse-grained POS tags are just mapped from the fine-grained tags with the tag map. Unfortunately, prodigy kind of muddles up these two types of tags in its recipes, so it will show you the coarse-grained tags in the annotator even though the model itself was really predicting the fine-grained tags underneath, so unless you're careful, you might not be annotating the type of data you need to update this particular model.

If you want to update `en_core_web_lg`, you'll need to use the fine-grained PTB tags instead with the `--fine-grained` option and `pos.correct` instead of `pos.teach`. The example below just focuses on the noun and verb tags, but since this may not provide enough context in the new examples, it might be better to go ahead use all the tags (provide them as a list in a text file with one tag per line instead, the full list is in the model `meta.json`).

```
prodigy pos.correct test_ptb_tags en_core_web_lg texts.txt --label NN,NNP,NNPS,NNS,VB,VBD,VBG,VBN,VBP,VBZ --fine-grained
```

Then you can export the data with `prodigy data-to-spacy --tagger` and use that to update the tagger model. It's probably best to use `spacy train` with the base model `-b` option.

I started working on updates to the tagger recipes a while ago to make this a bit easier (so it would read the labels from the model if you didn't provide any and always use the fine-grained tags if you're using a model), but these haven't made it into a release yet. It might make sense to plan this for the version of prodigy that will be released for spacy v3, since the tag/pos labels will be predicted separately by different components rather than through a tag map.

**Comment by inceatakan** [comment] 2020-10-29 18:48
Adrian,

Thank you very much for this very detailed explanation and recommendation.

-Atakan

**Closed** 2020-11-12 11:02 UTC
Labels: feat / tagger, training, ✨ prodigy
