### ISSUE TITLE
text color dont working after spacy in jupyter notebook

### ISSUE THREAD

**Issue by phayllia** [explosion/spaCy#4200] opened 2019-08-26 22:08 UTC
## How to reproduce the behaviour

In a new jupyter notebook, print '\033[34mtest\033[0m' produces the text in blue as expected.

>>import spacy
>>print '\033[34mtest\033[0m'
After importing, the text color print doesn't work anymore

## Your Environment

* Operating System: Windows
* Python Version Used: 2.7
* spaCy Version Used: 2.0.9
* Environment Information:

**Comment by svlandeg** [comment] 2019-08-27 08:06
Yes, I can confirm that this happens indeed, something in the `spaCy` installation is preventing the color to print. @ines : any idea why this happens?

**Comment by ines** [comment] 2019-08-27 08:35
Just testing it – I really hope this won't be too difficult to track down. The thing is, this could happen in any dependency. In spaCy and our libraries, we typically avoid setting anything in the global scope (and of course never monkeypatch built-ins) for reasons like this.

The most related dependency is my package [`wasabi`](https://github.com/ines/wasabi), but it shouldn't be doing anything on import 🤔

**Comment by svlandeg** [comment] 2019-08-27 08:42
same here but on a windows:
![image](https://user-images.githubusercontent.com/8796347/63755653-590b6480-c8b7-11e9-9cc1-6a415c7f6e6b.png)

**Comment by svlandeg** [comment] 2019-08-27 08:44
I can take this on if you can't reproduce!

**Comment by ines** [comment] 2019-08-27 08:48
Ahh, maybe it's a Windows thing? Okay, here are some things to try:

```python
import wasabi
print("\033[34mtest\033[0m")
```

If the above works fine:

```python
from wasabi import Printer
msg = Printer()
print("\033[34mtest\033[0m")
```

If those work, it's most likely not in `wasabi` where we actually handle the related printing stuff.

**Comment by svlandeg** [comment] 2019-08-27 08:49
It's not `wasabi`  - the color stays blue. Let me try out a few other `spaCy` dependencies ;-)

**Comment by svlandeg** [comment] 2019-08-27 08:50
@phayllia : are you running this on a Windows?

**Comment by ines** [comment] 2019-08-27 08:53
(Sorry, misclicked!) Thanks for checking. And damn, I was hoping it'd be `wasabi`, since it's a super small zero-dependency codebase and ours, so it would have been easy to resolve. Still hope it's in one of our dependencies so we can just fix it, and not in a third-party package.

**Comment by svlandeg** [comment] 2019-08-27 09:01
I can't pin it on one of the dependencies :(

**Comment by ines** [comment] 2019-08-27 09:08
Damn... so if none of the dependencies have an impact at import, I guess next would be to check what spaCy creates in the global scope and what runs when you `import spacy`. Luckily, all the language data is out because that's lazy-loaded. And there shouldn't be that much, because we really try to avoid it.

**Comment by svlandeg** [comment] 2019-09-09 09:10
https://askubuntu.com/questions/831971/what-type-of-sequences-are-escape-sequences-starting-with-033/831973

**Comment by svlandeg** [comment] 2019-09-09 09:54
After first thoroughly inspecting `spaCy`'s codebase, I finally found the root cause somewhere else: not a direct dependency of `spaCy` but a standard Python package .... `tqdm` !

![image](https://user-images.githubusercontent.com/8796347/64521358-253d2f80-d2f8-11e9-85b3-d002a8a5c1ce.png)

The relevant issue is here: https://github.com/tqdm/tqdm/issues/678 - not fixed yet. So I think we can close this issue as unfortunately we can't really fix this ourselves. I would suggest upvoting the `tqdm` issue though.

**Comment by svlandeg** [comment] 2019-09-09 10:00
@ines: we're only using `tqdm` in the `examples`, `bin` and `cli` scripts. We could import it within the functions to potentially fix this bug?

**Comment by ines** [comment] 2019-09-09 11:25
Ha, I knew it'd be _something_ along those lines! Thanks for tracking this down.

> We could import it within the functions to potentially fix this bug?

Yes, that sounds like an okay workaround for now. Maybe just add a quick inline comment pointing to this issue – and then we just need to remember to change it back once the problem is resolved.

**Closed** 2019-09-09 14:32 UTC
Labels: bug, jupyter, third-party
