### ISSUE TITLE
Lemmatization of the word "Installed" outputs "instal" (with a single 'l')

### ISSUE THREAD

**Issue by navotoz** [explosion/spaCy#11174] opened 2022-07-21 06:39 UTC
## How to reproduce the behavior
```
! python -m spacy download en_core_web_trf
import spacy

nlp = spacy.load("en_core_web_trf")
doc = nlp("I installed Microsoft products" )
empty_list = []
for token in doc:
    empty_list.append(token.lemma_)

final_string = ' '.join(map(str,empty_list))
print(final_string)
````
The outcome was:
I **instal** microsoft product

The expected outcome was:
I **install** microsoft product

## Your Environment
* Operating System: Linux Debian 11
* Python Version Used: 3.9.4
* spaCy Version Used: 3.4.0
* spaCy Model Used: en_core_web_sm, en_core_web_md, en_core_web_lg

**Comment by adrianeboyd** [comment] 2022-07-21 11:42
This is basically a duplicate of #6075. The comment here is for v2 is still relevant for the difference between lookup and rule-based results: https://github.com/explosion/spaCy/issues/6075#issuecomment-696080478

Updated instructions for v3 in case you want to change the behavior:

If you want to change the results in your v3 model for individual cases like `instal`, you can modify the table in `nlp.get_pipe("lemmatizer").lookups.get_table("lemma_exc")` to edit the lemmas for installed and installing. If you save the model with `nlp.to_disk`, it will save the modified tables so you can reload this as a custom model.

**Closed** 2022-07-29 00:05 UTC
Labels: duplicate, lang / en, models, feat / lemmatizer, resolved
