### ISSUE TITLE
POS tagging after multi-word expression re-tokenization

### ISSUE THREAD

**Issue by DBaker999** [explosion/spaCy#4218] opened 2019-08-30 14:19 UTC
Hello,

I am wondering how the POS tagging is done for mult-word expressions.
'carboxylic acid' gets tagged as 'ADJ' although it would seem more natural to have it tagged as a 'NOUN' because the term 'acid' the head of this multiword expression
(see code below)
Am I missing something?  Is this something which I can adjust?

Thank you,

David

import spacy
from spacy.pipeline import EntityRuler
sentence = "A fatty acid is a carboxylic acid"
nlp = spacy.load('en_core_web_sm')
doc = nlp(sentence)

print([(t.text, t.pos_) for t in doc])

output: [('A', 'DET'), ('fatty', 'ADJ'), ('acid', 'NOUN'), ('is', 'VERB'), ('a', 'DET'), ('carboxylic', 'ADJ'), ('acid', 'NOUN')]

mwes = ['carboxylic acid', 'fatty acid']
ruler = EntityRuler(nlp)
for a in mwes:
    ruler.add_patterns([{"label": "x", "pattern": a}])

nlp.add_pipe(ruler)
doc = nlp(sentence)

with doc.retokenize() as retokenizer:
    for ent in doc.ents:
        retokenizer.merge(doc[ent.start:ent.end])

print([(t.text, t.pos_) for t in doc])
output: [('A', 'DET'), ('fatty acid', 'ADJ'), ('is', 'VERB'), ('a', 'DET'), ('carboxylic acid', 'ADJ')]

_______________________

doc = nlp('carboxylic acid')
print([(t.text, t.head, t.pos_) for t in doc])
output: [('carboxylic', acid, 'ADJ'), ('acid', acid, 'NOUN')]

_______________________
Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.2
* **Models:** en

**Comment by adrianeboyd** [comment] 2019-08-30 16:04
The new span was taking the attributes of the first word rather than the root of the span. Hopefully fixed by #4219.

Duplicate of #4015.

**Closed** 2019-09-05 08:34 UTC
Labels: bug, feat / doc
