### ISSUE TITLE
Can't deserialize nlp object with from_bytes()

### ISSUE THREAD

**Issue by asantos-6** [explosion/spaCy#2690] opened 2018-08-21 15:34 UTC
## Definition

I retrained the 'pt_core_news_sm' to include a new entity type and it works fine when I load it locally like so: 
```
nlp = spacy.load('path_to_my_model')
```
Then I serialize it with the to_bytes function:
```
nlp_bytes = nlp.to_bytes()
```
Up until now everything works fine, the problem is when I try to load this model onto a new blank Language model using the ```from_bytes``` function:
```
nlp2 = Portuguese()
nlp2 = nlp2.from_bytes(nlp_bytes)
```
According to your documentation in your website this was supposed to be enough. However, it doesn't load the model correctly onto ```nlp2``` since its ```entity``` structure inside says that there is ```"No component 'ner' found in the pipeline. Available names: []"``` and the results using this model are way off.

Are you aware of this or am I just doing something wrong? Note that I want to be able to do this because I don't want to load the model I trained from disk but from a serialized file where I would write the ```nlp_bytes```.

Thank you in advance

## My Environment

* Operating System: Ubuntu 18.04.1
* Python Version Used: Python 2.7
* spaCy Version Used: spaCy 2.0.11

**Comment by honnibal** [comment] 2018-08-26 17:23
Would you mind trying this in v2.1.0a1, which you could install with `pip install spacy-nightly`? I think it should be fixed there.

**Comment by asantos-6** [comment] 2018-08-27 10:13
I did, but apparently there's an incompatibility with the model saved with the version 2.0.11 and version 2.1.0a1 because when I try to run ```nlp = spacy.load('path_to_my_model')``` the following error occurs: 
```
IOError: [Errno 2] No such file or directory: '.../my_model/parser/model'
```
Does this mean that the way things are saved with ```Language.to_disk()``` changed? And if so, that means I would have to train and save the model again to a new folder and then load it to test if indeed the serialization/desserialization problem is solved, correct?

**Comment by honnibal** [comment] 2018-09-28 12:46
You'll need to retrain the model between v2.0.x and v2.1.x --- the settings are different, so models aren't compatible across those versions. Could you let us know whether the problem is still occurring after you retrain?

**Closed** 2018-10-12 13:08 UTC
Labels: bug, more-info-needed
