### ISSUE TITLE
Lemmatisation of "did" is no longer "do" in the context of n't

### ISSUE THREAD

**Issue by chrisjbryant** [explosion/spaCy#13098] opened 2023-11-02 06:34 UTC
I just updated from spacy 3.6 to 3.7 and "did" is no longer getting lemmatised as "do" when followed by n't.

```
nlp = spacy.load("en_core_web_sm")
sent = "I didn't go to the bank at the weekend."
for tok in nlp(sent):
    print(tok.text, tok.lemma_)
```
Output:
```
I I
did did      # lemma should be "do"
n't n't
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .
```

## How to reproduce the behaviour

- **spaCy version:** 3.7.2
- **Platform:** Linux-6.2.0-1017-gcp-x86_64-with-glibc2.35
- **Python version:** 3.10.12
- **Pipelines:** en_core_web_sm (3.7.0)

**Comment by Kepsondiaz** [comment] 2023-11-02 21:21
hello @chrisjbryant
I think the error comes from the code you provided. 
you should process the text with **nlp function** before doing the for loop like this:  

`doc = nlp(sent)`

**Comment by Kepsondiaz** [comment] 2023-11-02 21:22
your code should look like this : 

`nlp = spacy.load("en_core_web_sm")
sent = "I didn't go to the bank at the weekend."
doc = nlp(sent)

for tok in doc:
    print(tok.text, tok.lemma_)
`

**Comment by Kepsondiaz** [comment] 2023-11-02 21:23
Output

**Comment by Kepsondiaz** [comment] 2023-11-02 21:23
`I -PRON-
did do
n't not
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .
`

**Comment by Kepsondiaz** [comment] 2023-11-02 21:24
`I -PRON-
did do
n't not
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .
`

**Comment by Kepsondiaz** [comment] 2023-11-02 21:24
I -PRON-
did do
n't not
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .

**Comment by chrisjbryant** [comment] 2023-11-03 03:20
Ah! My bad, that was a mistake in my demo code above. 

I did some more testing as the error appeared in my code when I upgraded spacy in my app, but when I test a clean spacy install, lemmatisation works as expected. So most likely not a spacy problem!

**Comment by chrisjbryant** [comment] 2023-11-03 03:42
My bad, that was a typo in my example code. I have updated it now. The error is still present in spacy.

**Comment by rmitsch** [comment] 2023-11-03 08:30
Hi @chrisjbryant, can you set up a fresh virtual environment and run this script there? I can't reproduce this. If I run 
```python
import spacy
print(spacy.__version__)
nlp = spacy.load("en_core_web_sm")
sent = "I didn't go to the bank at the weekend."
for tok in nlp(sent):
    print(tok.text, tok.lemma_)
```
my output is:
```
3.7.2
I I
did do
n't not
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .

```

**Comment by chrisjbryant** [comment] 2023-11-03 08:38
I was previously using a conda env, but just tried with venv and same result. :/

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> print(spacy.__version__)
3.7.2
>>> nlp = spacy.load("en_core_web_sm")
>>> sent = "I didn't go to the bank at the weekend."
>>> for tok in nlp(sent):
...     print(tok.text, tok.lemma_)
... 
I I
did did
n't n't
go go
to to
the the
bank bank
at at
the the
weekend weekend
. .
>>> 
```

**Comment by rmitsch** [comment] 2023-11-03 08:51
Huh, after noticing I ran this with Python 3.9 I set up a clean venv with Python 3.10 - there I can reproduce this. We'll look into it.

**Comment by adrianeboyd** [comment] 2023-11-03 09:03
I can confirm that this is a bug. A few of the attribute ruler patterns were switched from `LOWER` to `NORM` in v3.7.x (to generalize a bit better overall), but "did" is already normalized to "do" by the tokenizer, and then the "did n't" pattern no longer matches as intended.

You can add the old rule back to the current `en_core_*` models as a workaround:

```python
nlp.get_pipe("attribute_ruler").add(
    patterns=[[{"TAG": "VBD", "LOWER": "did"}]],
    attrs={"POS": "AUX", "LEMMA": "do"},
    index=0,
)
```

**Comment by chrisjbryant** [comment] 2023-11-03 10:21
Just to make sure, don't forget to check other cases too, since I now also recreated it with `hadn't`!

**Comment by adrianeboyd** [comment] 2023-11-03 10:55
Yeah, we'll review all the changes. (The underlying idea was to use `NORM` to match more variants of contractions with apostrophes.)

**Comment by adrianeboyd** [comment] 2023-11-06 14:32
Thanks again for the report, we've updated this in the internal attribute ruler data and added a test to `spacy-models`, so let's hope this is fixed in the next round of pipeline releases (probably pipeline version v3.8.0).

**Closed** 2023-11-14 00:05 UTC
Labels: bug, lang / en, feat / lemmatizer
