### ISSUE TITLE
How can I retrain existing spacy v3 NER model with additional data?

### ISSUE THREAD

**Issue by laxmimerit** [explosion/spaCy#8511] opened 2021-06-26 22:07 UTC
Hi,
I have trained Spacy v3 model on 1 million rows and want to train for additional 1 million.
```
!python -m spacy train spacy_v3/config.cfg --output spacy_v3/output --paths.train spacy_v3/train.spacy --paths.dev spacy_v3/test.spacy --gpu-id 0
```
While training on additional 1 million or more data, I want to start my training from the previous best-model. Is there anyway to retrain existing ner model?

**Comment by polm** [comment] 2021-06-27 04:44
Since this is a question and not a bug I'm moving it to a Discussion.

**Closed** 2021-06-27 04:44 UTC
