### ISSUE TITLE
French POS seems to mixup `SYM` and `VERB`

### ISSUE THREAD

**Issue by FelixLC** [explosion/spaCy#1178] opened 2017-07-06 13:11 UTC
I've followed the installation tutorial and tried with a very simple example with latest version of spacy and it seems that POS assigns all `SYM` to `VERB` and vice-versa

### To reproduce
```
mkvirtualenv -p python3 spacy
pip install -U spacy
python -m spacy download fr
```
Then follow instructions at https://github.com/explosion/spaCy/issues/1052 to avoid `KeyError`.

```python
import spacy
nlp = spacy.load('fr')
doc = nlp("il s'agissait donc d'un bigéminisme auriculaire asymptomatique, la TSH étant < 1")
for word in doc:
    print('{}/{}'.format(word.text, word.pos_), end=' ')
```

Yields:
```
il/PRON s'/PRON agissait/SYM donc/ADV d'/ADP un/DET bigéminisme/NOUN auriculaire/ADJ asymptomatique/ADJ ,/PUNCT la/DET TSH/PROPN étant/AUX </VERB 1/NUM ./PUNCT
```

## Your Environment
* **spaCy version:** 1.8.2
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** fr

**Comment by ines** [comment] 2017-11-06 01:35
Sorry for only getting to this now – I just tried your example using the latest French model for v2.0, `fr_core_news_sm` and it looks like the problem is now fixed:

```bash
pip install spacy-nightly
spacy download fr_core_news_sm

>>> import fr_core_news_sm
>>> nlp = fr_core_news_sm.load()
>>> doc = nlp("il s'agissait donc d'un bigéminisme auriculaire asymptomatique, la TSH étant < 1")
>>> [(t.text, t.pos_) for t in doc]

[('il', 'PRON'), ("s'", 'PRON'), ('agissait', 'VERB'), ('donc', 'ADV'), ("d'", 'ADP'), 
('un', 'DET'), ('bigéminisme', 'NOUN'), ('auriculaire', 'ADJ'), ('asymptomatique', 'NOUN'), 
(',', 'PUNCT'), ('la', 'DET'), ('TSH', 'PROPN'), ('étant', 'VERB'), ('<', 'ADP'), ('1', 'NUM')]
```

At the moment, there's only an `sm` model available – but we'll also be training `md` and `lg` versions, as well as a separate word vector package.

**Closed by ines** 2017-11-06 01:35 UTC
Labels: language / french, models, performance
