### ISSUE TITLE
Growing memory usage (re-open)

### ISSUE THREAD

**Issue by dennlinger** [explosion/spaCy#3181] opened 2019-01-21 15:30 UTC
## How to reproduce the behaviour
Similar to #205 I encounter issues with growing memory in my environment.
Essentially, the problem happens if I have a simple script that loads a SpaCy model, and I re-execute the script.

```
import spacy
nlp = spacy.load("en_vectors_web_lg")
# do stuff with the model
```
Expected behavior:<br/>
Once I ran the script out of my editor (Spyder), memory usage should not increase significantly once I re-run the script.

Observed behavior:<br/>
With each execution the memory consumption continues to grow.
Note that manually clearing the variable (`del nlp`) does also *not* free the memory.

The current workaround for me is to completely kill the kernel after each execution.

## Environment
* Operating System: Ubuntu 18.04 Bionic Beaver (64-bit) / Ubuntu 16.04
* Python Version Used:  Python 3.7.1 (experienced the same with Anaconda Python 3.6)
* spaCy Version Used: 2.0.18
* Environment Information: conda 4.5.12, Spyder, IPython 7.2
* Models: en_vectors_web_lg, en

**Comment by Noirai** [comment] 2019-02-25 08:32
Same problem here. 
spaCy version: Spacy2.1.0a9.dev0
Platform: Darwin-17.7.0-x86_64
Python: 3.7.2
en_core_web_sm model.
According to my profiler in every loop of my code nlp.pipe() would allocate memory, would not release after the loop finish.
RAM usage would rise continually to ~80 GB+. 
Tried batch_size=1, n_threads=1 / -1, no actual effect.
Reloading model (creating new nlp variable using spacy.load() ) in every loop does not solve the problem either.

**Comment by honnibal** [comment] 2019-02-27 10:44
Could you run the following benchmark and let me know the output for you? I can't reproduce the memory leak you're reporting on my machine, so I'm not sure what's going on. If it's true that `nlp.pipe()` leaks on every `Doc` that's obviously very serious!

You'll need to `pip install psutil` before running this.

```python
import spacy
import plac
import thinc.extra.datasets
import psutil


def load_data():
    train_data, _ = thinc.extra.datasets.imdb()
    texts, _ = zip(*train_data)
    return list(texts)


def parse_texts(model_name, texts, iterations=1000):
    for i in range(iterations):
        nlp = spacy.load(model_name)
        for doc in nlp.pipe(texts):
            yield doc


@plac.annotations(
    iterations=("Number of iterations", "option", "n", int),
    model=("spaCy model to load", "positional", None, str)
)
def main(model='en_core_web_sm', iterations=1000):
    print("Load IMDB texts")
    texts = load_data()
    for i, doc in enumerate(parse_texts(model, texts, iterations=iterations)):
        if i % 1000 == 0:
            print(i, psutil.virtual_memory().percent)


if __name__ == '__main__':
    plac.call(main)
```

**Comment by dennlinger** [comment] 2019-02-27 12:55
I can quickly update you on my end, even though it seems that my problem is not to the same extent as @Noirai is experiencing it.

Essentially, for me, the issue is that it is allocating the space twice (for a short time), shortly before actually releasing the old object. Unfortunately, due to memory limitations on my work machine I at first did not see this factor of 2 only, and unfortunately assumed it would increase further with more re-executions (I guess this is good news after all).

I also don't know enough about the way Python is handling memory, but I would still be curious why it is not possible to release the object manually with `del`, so I can work without any problems even when low on memory.

I can also kind of see this behiavor in the output from your script, which I let run for a short while:

```
Load IMDB texts
Downloading data from http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
84041728/84125825 [============================>.] - ETA: 0sUntaring file...
0 47.9
1000 50.7
2000 51.1
3000 51.0
4000 50.2
5000 50.8
6000 50.9
```
Notice how the first print shows a slightly lower memory consumption, whereas the others are more or less consistent (even though this 3-4% difference should equal around 250-300MB on my 8 GB machine, but the nlp object only measures around 45MB [done with `pympler.asizeof`]).

Not sure if this helps too much, but thanks already for looking into this!

**Comment by honnibal** [comment] 2019-03-10 01:55
Well...If it's transient memory usage, it could be any number of things, for instance if it's serialising it might have to build an extra copy in memory. If you find places where we can avoid this, I'd definitely be happy to take the patch. But so long as there's no memory leak I'll go ahead and close this. Thanks for following up!

**Closed by honnibal** 2019-03-10 01:55 UTC
Labels: perf / memory
