### ISSUE TITLE
Lemmatization case sensitive

### ISSUE THREAD

**Issue by mvaz** [explosion/spaCy#3893] opened 2019-07-02 09:26 UTC
## How to reproduce the behaviour

I'm using the same code snippet as with #3572 and as far as I understood should have been resolved with #3551 

import spacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_sm")

matcher = Matcher(nlp.vocab)
pattern = [{"LEMMA": "bike"}]
matcher.add("BasinTest", None, pattern)

doc = nlp("The Bike is a great tools")
matches = matcher(doc)
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]  # Get string representation
    span = doc[start:end]  # The matched span
    print(match_id, string_id, start, end, span.text)

The code produces no output, meaning that the lemmatisation is case sensitive.

[t.lemma_ for t in doc]
the output is ['the', 'Bike', 'be', 'a', 'great', 'tool']

Thanks

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.3

**Comment by BreakBB** [comment] 2019-07-03 12:30
I can reproduce your behaviour with the latest spaCy commit. But it's seems less a bug but a simple error of the model.

If you test the sentence "It is great to ride the Bike", your matcher works just fine. "The Bike", "The Car" , "The House" and "The Oasdijadddisd" all result in a named entity for the second word as PROPN and therefore the lemma remains the same.

**Comment by mvaz** [comment] 2019-07-08 17:10
Thanks for taking the time and the insight.
I tested and got the same result as you.
I'll have to verify on the specific examples on my text that weren't working as expected.

**Comment by ines** [comment] 2019-07-09 19:45
Yes, it looks like the incorrectly predicted proper noun makes the difference here. If your text contains a lot of improper capitalisation like this, you could consider updating the model with more examples of texts including things like "the Bike", where "Bike" is marked as a `NOUN` instead of a `PROPN`. 

Also referring this to #3052.

**Closed by ines** 2019-07-09 19:45 UTC
Labels: feat / tagger, perf / accuracy

**Comment by mvaz** [comment] 2019-07-09 20:34
Thanks for the suggestion.
