### ISSUE TITLE
AssertionError when running beam_parse

### ISSUE THREAD

**Issue by lhyleo** [explosion/spaCy#4650] opened 2019-11-14 18:33 UTC
It might be related to [https://github.com/explosion/spaCy/issues/4313](url), but I cannot figure out how to reopen an issue

## How to reproduce the behaviour

```python
import spacy

nlp = spacy.load('en_core_web_lg')
doc = nlp("Our principal executive office is located at 333 South Grand Avenue, 28th Floor, Los Angeles, CA 90071 and our telephone number is (213) 830-6300.") 
docs = [doc]
ner = nlp.get_pipe('ner')
beams = ner.beam_parse(docs, beam_width=5)
```

I got the following traceback:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-4-7f0219500ddb> in <module>
      2 docs = [doc]
      3 ner = nlp.get_pipe('ner')
----> 4 beams = ner.beam_parse(docs, beam_width=5)

nn_parser.pyx in spacy.syntax.nn_parser.Parser.beam_parse()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.transition_beams()

search.pyx in thinc.extra.search.Beam.advance()

AssertionError: 
```

## Your Environment

* Operating System: macOS 14.10.6
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.9

**Comment by adrianeboyd** [comment] 2019-11-14 19:27
This is indeed a duplicate of #4313. It was fixed recently and should work in spacy v2.2.0+.

**Comment by lhyleo** [comment] 2019-11-14 19:55
Is there a work around for spacy 2.1.x?

**Comment by adrianeboyd** [comment] 2019-11-14 20:50
Have you tried the suggested workaround from https://github.com/explosion/spaCy/issues/4313#issuecomment-536022028?

**Comment by lhyleo** [comment] 2019-11-15 17:27
Yes, in fact, I am not adding any new labels to the model and only using the original model. I tried to do `nlp.entity.add_label()` for every labels appear in the doc but it is still throwing the assertion error

**Comment by svlandeg** [comment] 2020-02-13 16:29
Closing this as the bug was fixed in PR https://github.com/explosion/spaCy/pull/4330.

**Closed by svlandeg** 2020-02-13 16:29 UTC
Labels: bug, 🔮 thinc
