### ISSUE TITLE
Language support pipelines links lead to wrong languages

### ISSUE THREAD

**Issue by gromanjakub** [explosion/spaCy#11120] opened 2022-07-12 09:30 UTC
The pipelines links on the right in the table of "[Language support](https://spacy.io/usage/models#languages)" redirect to wrong languages. Croatian (2nd row) leads to Chinese and then all the following rows' links lead to the languages one row above them. The first row of the table is correct.

## Which page or section is this issue related to?

https://github.com/explosion/spaCy/blob/master/website/src/widgets/languages.js

**Comment by polm** [comment] 2022-07-12 09:37
Thanks for the report! That sounds bad but I can't reproduce it here. Can you try doing a hard reload in your browser / clearing your cache?

**Comment by gromanjakub** [comment] 2022-07-12 09:58
Interestingly enough it seems to appear only in Firefox. Firefox on the left, Chrome on the right.
When reloading in Firefox, Chinese appears near the top where it should be and then reappears between Greek and Italian
![obrazek](https://user-images.githubusercontent.com/60711940/178464134-4c9fa8a9-e380-4f06-8ed0-fcfd57848894.png)

**Comment by polm** [comment] 2022-07-12 10:21
Huh, that's really weird. Thanks for investigating for us, we'll keep looking into it!

**Comment by polm** [comment] 2022-07-13 06:10
I checked with Firefox on my machine, and with our team, but I can't reproduce this. 

Could you check again with a hard refresh (ctrl+shift+r or equivalent), and if you still see it, let us know your OS version and Firefox version?

**Comment by polm** [comment] 2022-07-25 02:17
I was unable to reproduce this on Windows 10 with the same Firefox version. If you are still having this issue, maybe it's due to an extension or something?

**Comment by polm** [comment] 2022-08-08 03:12
Going to close this since I've been unable to reproduce it, but if you (or anyone else) still has issues with it please let us know.

**Closed by polm** 2022-08-08 03:12 UTC
Labels: docs, more-info-needed
