### ISSUE TITLE
Confidence Score for NER 

### ISSUE THREAD

**Issue by gsevrodrigues** [explosion/spaCy#5917] opened 2020-08-13 17:35 UTC
It is important for my current project to output the confidence score for each entity we get from NER.
Doing my research, I've found out some issues regarding that. Those were particulary usefull for me: https://github.com/explosion/spaCy/issues/3996, https://github.com/explosion/spaCy/issues/881, https://github.com/explosion/spaCy/issues/831
They presented a method by our great honnibal that calculates the confidences from the spaCy NER extractions.

HOWEVER, after updating my `en_core_web_md` model to version `2.3.0`, the confidences I got for **a lot** of my NER extractions are `1.0` or `0.0`  (before updating the model, I used to see all types of scores, ranging from` 0.666...` to `0.999... `). Something seems just off... I wonder if I can trust those values. I also wonder how, internally, spaCy decides if a NER entity is acceptable or not considering its confidence (or if it taken into consideration at all).
Here is an snippet of my project where I get the confidences:

```python

nlp = spacy.load('en_core_web_md')
with nlp.disable_pipes('ner'):
    doc = nlp(text)

beams = nlp.entity.beam_parse([ doc ], beam_width = 16, beam_density = 0.0001)

entity_scores = defaultdict(float)
    for beam in beams:
        for score, ents in nlp.entity.moves.get_beam_parses(beam):
            for start, end, label in ents:
                entity_scores[(start, label)] += score
```

Am I doing anything incredibly wrong here? 

PS: I wonder if we are going to have an easy access to a confidence score from the entities in the near future? That would be great.

## Environment
* Operating System:  Windows 10 (but I'm also executing the code inside a container that runs Ubuntu and got the same issue)
* Python Version Used:  3.7.7
* spaCy Version Used: 2.3.0

**Comment by fcggamou** [comment] 2020-08-14 16:12
I believe in order to get proper beam probabilities you need to train your model with a global objective; check the answer to issue #2601. #5915 may be useful as well.

This is such a common use case, I hope it'll be easily supported in 3.0.

**Comment by themrmax** [comment] 2021-01-14 21:33
The beam-parse approach hasn't worked for me, however I have been having some success with training a separate `textcat` pipe to classify correct vs incorrect entity text (requires labeled examples of incorrectly extracted entities), and applying this serially to the output of the NER model to generate my scores. The downside of course is the extra training and classification time, not sure whether there are any optimisations here, or whether it would be worth supporting this set-up as a core feature of sPacy?

**Comment by lucinvitae** [comment] 2021-03-30 14:44
Hello @honnibal, @ines, and @svlandeg, apologies for the noise, but I have noticed that you have been discussing this issue, resolving/closing other related threads, and linking back to here or elsewhere. I figured it would help to organize the discussion a little more and define the feature request as well as use case (plus make some noise so it's clear how valuable this would be!).

_Disclaimer: if you already are actively working on this feature, then this post is merely a testament to the lack of visibility into the fact that this work is taking place, and the feature request can be ignored :)._

**Problem Statement**

The problem upfront is that (1) our team requires a robust way to return confidence scores for custom NER models, (2) spaCy does not seem to support this out of the box, and (3) the discussions for how to implement an effective solution are distributed over a number of threads, making the "docs" on this difficult to traverse and it hard to tell what the best or recommended approach is.

**Use Case**

We are beginning to train custom NER models and use them at scale, but multiple downstream applications have requested confidence scores for the NER model's predictions in order to rank results and select/filter by highest probability or confidence score. Example downstream apps: search/recommendation systems, and AI planning systems which depend on a spaCy-powered information extraction service. Without a dedicated spaCy feature that does this, we've resorted to investigating the beam-parse approach, and suggesting that downstream apps use method stubs in the short-term, but we're still not sure of the right direction. Alternatives proposed: separate regression models that predict a score (very meta! but confusing/indirect/potentially-ill-advised).

**Feature Request**

A spaCy-supported solution presented as a roadmap item for a future release of spaCy containing a supported method for scoring NER predictions by level of confidence, and/or a link to official public documentation for how to use spaCy functions/classes in order to score predictions.

I specifically call out the public documentation because these threads about using beam-parse are difficult to read and search through, and many solutions appear to be out of date. Perhaps a short-term workaround to the missing public docs could be to present or link to the latest and greatest method (beam-parse?) for scoring NER model predictions here in this thread or in a gist that gets updated periodically.

**Breadcrumb Trail**

Here's the trail of issues containing useful information about this topic, and a brief description of relevant information for each issue:

1. https://github.com/explosion/spaCy/issues/831 (in which @honnibal links to https://github.com/explosion/spaCy/issues/881 and @svlandeg links to the current issue, 5971)
2. https://github.com/explosion/spaCy/issues/881 (in which @honnibal defines the issue and presents a solution 4 years ago, then closes the issue)
3. https://github.com/explosion/spaCy/issues/4450 (in which @adrianeboyd links to a method in the spaCy codebase in response to a user request for a more stable way to train NER models while supporting confidence scores)
4. https://github.com/explosion/spaCy/issues/6644 (in which @svlandeg discusses that scoring NER confidence is a work in progress, but there's little visibility to where it's being tracked)
5. https://github.com/RasaHQ/rasa/issues/676 (not a spaCy thread, but @honnibal mentions the beam-parse method here)
6. https://support.prodi.gy/t/displaying-a-confidence-score-next-to-a-user-defined-entity/403 (prodigy thread, but @honnibal mentions a beam-parse method there)

(I think it's worth collecting these somewhere, mostly for my own reference and so other users can trace the breadcrumb trail, since the replies in these threads contain relevant context as well as implementation details for the beam-parse approach not mentioned in spaCy's documentation site, but also for the authors of spaCy so that they may see the path users like myself are taking and how it might be easy to get confused.)

Unrelated to confidence scores: Thanks for developing and open-sourcing a great library, which is helping our team to resolve issues and collect information for patients more quickly and at a lower cost.

**Comment by svlandeg** [comment] 2021-03-30 15:08
An important related PR (WIP) is https://github.com/explosion/spaCy/pull/6747:

> The SpanCategorizer component (...) takes a function that proposes (start, end) offsets in the documents as possible spans to be recognized ... and ... assigns label probabilities to each span

> Another really nice thing about this component is that it predicts directly over the spans, so we'll finally have a component that can give meaningful entity confidences 🎉

**Comment by EnzoNclt** [comment] 2021-06-15 09:39
Any update about confidence score in SpaCy 3 ? i'm currently using v3.0.6 but i'm still looking having the same issue than reported in ticket https://github.com/explosion/spaCy/issues/6644, `AttributeError: 'English' object has no attribute 'entity'` while i'm using beam parsing like this:
` with self.nlp.disable_pipes('ner'):
            doc = self.nlp(text)
        beams = self.nlp.get_pipe("ner").beam_parse([doc], beam_width=16, beam_density=0.0001)
        entity_scores = defaultdict(float)
        for score, ents in self.nlp.get_pipe("ner").moves.get_beam_parses(beams[0]):
            print(score, ents)
            for start_char, end_char, label in ents:
                entity_scores[(start_char, end_char, label)] += score`

**Comment by polm** [comment] 2021-07-14 04:41
@nsorros You should be able to use the [SpanCategorizer](https://spacy.io/api/spancategorizer) for this. We don't have an example project for it yet, but the docs are all there so it should be working. If you're confused about anything feel free to open a Discussion.

**Comment by adrianeboyd** [comment] 2021-07-14 06:36
There is an example project!

https://github.com/explosion/projects/tree/v3/experimental/ner_spancat

**Comment by nsorros** [comment] 2021-07-14 08:14
Thanks @adrianeboyd and @polm, span categoriser seems to resolve this, the docs are clear, will try it out and open a discussion if there is a problem. Super exciting 💥

**Closed** 2021-07-22 00:02 UTC
Labels: enhancement, feat / ner, resolved

**Comment by mbrunecky** [comment] 2021-07-22 22:25
Well, THANK YOU for the demo/example.
Works out of the box (well, I am not sure why I am getting the message below, but that's easy to fix).

HOWEVER, I am confused. This demo show confidence scores per LABEL (PERSON, PLACE, ORGANIZATION).
But (based on the discussion above), I was hoping I can get confidence for **EACH INDIVIDUAL SPAN** (i.e. for each ORGANIZATION instance in the data). So for the text "Setelah itu Saykoji ikut dalam kompilasi" I would hope to see confidence for predicting "Saykoji" is an ORGANIZATION (as opposed to PERSON or PLACE).
Is that even possible?

The (minor) error:
`The project.yml specifies a spaCy version range (3.1.0,<4.0.0) that's not compatible with the version of spaCy you're running (3.1.1)`

**Comment by mbrunecky** [comment] 2021-07-22 23:06
I tried adding " --displacy-path ./parses" to the 'evaluate' command. Execution reports the following (generated 25 parses), but there is **nothing** in my ./parses directory:
============================== SPANS (per type) ==============================
                   P       R       F
PERSON         74.50   52.11   61.33
PLACE          81.04   66.46   73.03
ORGANISATION   52.63   41.32   46.30

✔ Generated 25 parses as HTML
parses
✔ Saved results to metrics\spancat.json

**Comment by gennsev** [comment] 2021-07-29 21:47
SpanCategorizer is great, but can we use it to get the confidence scores from the default trained models such as `en_core_web_trf `and `en_core_web_md`, or is it intended only to help evaluating newly trained models?

**Comment by nsorros** [comment] 2021-07-30 05:38
I am also interested to the answer of this. From my understanding we need to train new models using it to get the confidence scores

**Comment by polm** [comment] 2021-07-31 06:42
SpanCategorizer is a separate component from the default NER component, so yes, you'd need to train new models to get this.

**Comment by mbrunecky** [comment] 2021-08-02 18:22
Is there any description of how SpanCategorizer differs from the 'default NER' component?
I mean what model architecture, hyper-parameters etc... Does this also mean that there is NO WAY of getting individual NER predictions confidence for Spacy running transformer models (such as RoBERTa)?
I may a bit slow, but after failing to make the demo/example generate any per-span-instance results (I tried to follow the code, but failed), I am still hoping to find an EASY-TO-FOLLOW example of how to get individual predictions.
The documentation goes to great length on to how to create your own span suggester etc. (which I will need later in the game), but I am still looking at 'how to get started'.

**Comment by gennsev** [comment] 2021-08-02 21:04
I'm on the same page as @mbrunecky. My project does not really demands training a new model, but I do need confidence scores for individual NER results.
And if I was even going to train a new model, would I then have the individual confidence scores? Or is SpanCategorizer used only during training, for accuracy calculation purposes?

**Comment by polm** [comment] 2021-08-03 06:35
At the moment the only way the individual span scores are exposed is that at inference time you can set a threshold value, and only scores with at least that value will be returned, but you can't inspect the individual scores. There's a PR (https://github.com/explosion/spaCy/pull/8855) for adding the individual scores that's a work in progress.

**Comment by mbrunecky** [comment] 2021-08-03 16:36
Thank you, @polm .
This is really needed, and hopefully we get it soon (I may try patching my code). I can imagine there are applications where individual predictions confidence does not matter (i.e. document classification), but in my NER application any prediction without confidence score is useless.
Which makes me wonder about the 'transformer' models. I was hoping to get the described accuracy improvements (albeit at a staggering computational cost), but if I can't get individual prediction confidence then it's a mute point.

**Comment by erotavlas** [comment] 2021-08-03 21:20
+1
I was just searching how to get the probabilities per entity from the NER model prediction and came across this. It would be really useful.

**Comment by polm** [comment] 2021-08-11 05:58
Just a note that #8855, which includes the scores in spancat output, has been merged and should be in the next release.
