### ISSUE TITLE
TextCategorizer object has no attribute 'walk'

### ISSUE THREAD

**Issue by DeltaSierra4** [explosion/spaCy#6933] opened 2021-02-04 21:57 UTC
## How to reproduce the behaviour
I'm trying to train a transformer model with GPU enabled to perform text categorization. I followed the instructions as posted on [the quickstart guide](https://spacy.io/usage/training#quickstart) to obtain a base configuration file (we'll name it bconfig.cfg here). Then I provided the paths to the train/dev files and filled in the defaults with init-config as the following:
`python3 -m spacy init fill-config bconfig.cfg rconfig.cfg`

After that. I ran the debug config script to check if it is all correctly set up.
`python3 -m spacy debug config rconfig.cfg`

This is the output I obtained:
```============================= Config validation =============================
/home/username/.local/lib/python3.8/site-packages/thinc/config.py:1032: RuntimeWarning: fields may not start with an underscore, ignoring "_doc_data"
  return create_model("ArgModel", **sig_args)

===================== Config validation for [initialize] =====================

====================== Config validation for [training] ======================
✔ Config is valid
```

Then I ran the training command:
`python3 -m spacy train ./rconfig.cfg --gpu-id=0 --output ./output`

Here's the error message I got:
```
✔ Created output directory: output
ℹ Using GPU: 0

=========================== Initializing pipeline ===========================
/home/username/.local/lib/python3.8/site-packages/thinc/config.py:1032: RuntimeWarning: fields may not start with an underscore, ignoring "_doc_data"
  return create_model("ArgModel", **sig_args)
Set up nlp object from config
Pipeline: ['transformer', 'textcat']
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/.local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/username/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/home/username/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/username/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/username/.local/lib/python3.8/site-packages/spacy/training/initialize.py", line 68, in init_nlp
    nlp._link_components()
  File "/home/username/.local/lib/python3.8/site-packages/spacy/language.py", line 1539, in _link_components
    proc1.find_listeners(proc2)
  File "/home/username/.local/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 140, in find_listeners
    for node in model.walk():
AttributeError: 'TextCategorizer' object has no attribute 'walk'
```

Here's the config file that I have obtained from the above procedure. I have also tried to prepare a config file using the spacy init config command but the results are the same.
```
[paths]
train = ./data/train.spacy
dev = ./data/dev.spacy
vectors = null
init_tok2vec = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["transformer","textcat"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.textcat]
factory = "textcat"
threshold = 0.5

[components.textcat.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat.model.linear_model]
@architectures = "spacy.TextCatBOW.v1"
exclusive_classes = true
ngram_size = 1
no_output_layer = false
nO = null

[components.textcat.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 500
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null
cats_score = 1.0

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

Any help or guidance would be appreciated.

## Your Environment
* Operating System: Ubuntu 20.04
* Python Version Used: 3.8.5
* spaCy Version Used: 3.0.1

**Comment by svlandeg** [comment] 2021-02-04 22:42
I think this is potentially caused by an incompatibility between the `spacy` version and `spacy-transformers`. Which version of `spacy-transformers` are you using? And if it's older, could you upgrade to 1.0.1 and try again?

**Comment by DeltaSierra4** [comment] 2021-02-05 02:10
That seems to have done the trick. Thank you svlandeg!

**Comment by svlandeg** [comment] 2021-02-05 08:31
Happy to hear it! I'll go ahead and close this issue then, feel free to open a new open if you'd run into any other problem ;-)

**Closed by svlandeg** 2021-02-05 08:31 UTC
Labels: feat / transformer, training
