### ISSUE TITLE
How can I connect NERs to a PERSON if they are related to each other?

### ISSUE THREAD

**Issue by Steven-Data** [explosion/spaCy#9325] opened 2021-09-29 23:10 UTC
I was wondering if there is a way to connect NERs to a PERSON if they are related to each other? For example, there are several NER were extracted by SpaCy, which are Steven (person), Jackson (person), San Jose (city), Google (organization), and 4243214567 (number). I would like to connect San Jose and 4243214567 to Steven because he lives in the city and the number is his phone number, and connect Google to Jackson because he work at the company. Do you have any suggestions for me on this use case? Thanks.

**Comment by polm** [comment] 2021-09-30 04:14
This is not a bug so I'm moving it to Discussions.

**Closed** 2021-09-30 04:14 UTC
