### ISSUE TITLE
Tokenization of "shed"

### ISSUE THREAD

**Issue by chrisjbryant** [explosion/spaCy#861] opened 2017-02-26 23:48 UTC
I've just noticed that in the latest version of spacy (1.6), "shed" is consistently getting tokenized as "she d" regardless of the context it occurs in. I'm guessing the tokenizer is trying to be too smart and always suspects a missing apostrophe. 

I used the following sentence:
We must shed light on the shed in the garden.

Interestingly, the erroneous tokenization does not happen in displacy.

**Comment by ines** [comment] 2017-02-27 09:56
Thanks – this was already reported in #847 and is fixed on master. So If you install from there, it should work fine. We'll also make a bug fix release that will include those changes.

The displaCy demo is currently using an older version of spaCy so that's probably why it doesn't occur there. (This regression was introduced when we refactored and generalised the tokenizer exceptions in v1.4 – the exceptions are now generated dynamically as pronoun + `'d`, pronoun + `d` etc. with a list of tokens to exclude. Turns out we somehow forgot to add some words like "shed" and "shell" to that list – sorry about that!)

**Closed by ines** 2017-02-27 09:56 UTC
Labels: duplicate, english, performance
