### ISSUE TITLE
OSError: [E050] in nlp.initialize()

### ISSUE THREAD

**Issue by lizgzil** [explosion/spaCy#6541] opened 2020-12-10 12:03 UTC
I am trying to train an entity linker but I am getting the error
```
OSError: [E050] Can't find model 'corpus/en_vectors'. It doesn't seem to be a Python package or a valid path to a data directory.
```
in `initialize()`.

I've looked at the docs [here](https://nightly.spacy.io/api/entitylinker), but am struggling to see why the error is occurring. 

## How to reproduce the behaviour

```
from spacy.kb import KnowledgeBase
from spacy.training import Example
import spacy

nlp = spacy.load('en_core_web_lg')
# here I usually load my local vocab path, but the same error occurs without this
# nlp.vocab.from_disk(self.vocab_path)
nlp.vocab.vectors.name = "spacy_pretrained_vectors"

def create_kb(vocab):
    entity_vector_length = 300
    kb = KnowledgeBase(vocab=vocab, entity_vector_length=entity_vector_length)
    # here I usually load my local knowledge base, but the same error occurs if you dont add anything 
    # kb.from_disk(self.kb_path)
    return kb

entity_linker = nlp.add_pipe("entity_linker")
entity_linker.set_kb(create_kb)

train_data = []
text_1 = "Russ Cochran his reprints include EC Comics."
dict_1 = {(0, 12): {"Q7381115": 1.0, "Q2146908": 0.0}}
train_data.append((text_1, {"links": dict_1}))
text_2 = "Russ Cochran has been publishing comic art."
dict_2 = {(0, 12): {"Q7381115": 1.0, "Q2146908": 0.0}}
train_data.append((text_2, {"links": dict_2}))
text_3 = "Russ Cochran captured his first major title with his son as caddie."
dict_3 = {(0, 12): {"Q7381115": 0.0, "Q2146908": 1.0}}
train_data.append((text_3, {"links": dict_3}))
text_4 = "Russ Cochran was a member of University of Kentucky's golf team."
dict_4 = {(0, 12): {"Q7381115": 0.0, "Q2146908": 1.0}}
train_data.append((text_4, {"links": dict_4}))

examples = []
for text, annotation in train_data:
    doc = nlp.make_doc(text)
    example = Example.from_dict(doc, annotation)
    examples.append(example)

other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "entity_linker"]
with nlp.select_pipes(disable=other_pipes):
    optimizer = nlp.initialize()
    for itn in range(n_iter):
        random.shuffle(examples)
        losses = {}
        batches = minibatch(examples, size=compounding(4.0, 32.0, 1.001))
        for batch in batches:
            nlp.update(
                batch, drop=0.2, losses=losses, sgd=optimizer,
            )
```

I'm getting this same issue when I try to load my own knowledge base and vocab. For this I thought maybe I needed to change the config file to point to the correct vectors location (which is "local_kb_path/vocab/vectors"), so I tried:
```
config = {"initialize": {"vectors": 'local_kb_path/vocab/vectors'}}
entity_linker = nlp.add_pipe("entity_linker", config=config)
```
but this gives 'extra fields not permitted'.

Many thanks!

## Your Environment

- **spaCy version:** 3.0.0rc2
- **Platform:** Darwin-18.6.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_md (3.0.0a0), en_core_web_lg (3.0.0a0)

**Comment by svlandeg** [comment] 2020-12-15 19:25
Thanks for the report!

It turns out that this has nothing do to with the EL algorithm. This happens because the code is calling `initialize` on an `nlp` object that was already initialized (and trained) with vectors before. This is a minimal reproducible snippet:
```
import spacy
nlp = spacy.load('en_core_web_lg')
with nlp.select_pipes(enable=[]):
    nlp.initialize()
```
which throws
```
Traceback (most recent call last):
  File "...\spacy\language.py", line 1213, in initialize
    self, data=I["vocab_data"], lookups=I["lookups"], vectors=I["vectors"]
  File "...\spacy\training\initialize.py", line 88, in init_vocab
    load_vectors_into_model(nlp, vectors)
  File "...\spacy\training\initialize.py", line 98, in load_vectors_into_model
    vectors_nlp = load_model(name)
  File "...\spacy\util.py", line 280, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'corpus/en_vectors'. It doesn't seem to be a Python package or a valid path to a data directory.
```
because `corpus/en_vectors` is in the original `en_core_web_lg` config file:
```
[paths]
vectors = "corpus/en_vectors"

[initialize]
vectors = ${paths.vectors}
```

I think this is a bug - you should be able to call `nlp.initialize` with only the newly created components enabled. We'll look into this!

**Comment by lizgzil** [comment] 2020-12-16 09:16
Thanks @svlandeg !

**Comment by svlandeg** [comment] 2020-12-29 09:45
Hi @lizgzil. So I thought about this some more, and came to the conclusion that this isn't really a bug. You're not really supposed to call `nlp.initialize` multiple times, even though it seems like a convenient way to initialize the new component(s).

To solve your use-case, I think you'd be better off to call `entity_linker.initialize` directly. Do note that you'll have to give it a `get_examples` argument. For more information, see [here](https://nightly.spacy.io/api/entitylinker#initialize).

Alternatively, you could start from a blank model, load your vocab into it, add the `entity_linker` and then call `nlp.initialize`. If you want to add the `ner` component from `en_core_web_lg`, you could achieve that with 

```
source_nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("ner", source=source_nlp)
```

However, note that the vocab and vectors of the loaded NER model should match.

By the way, for v3 we highly recommend using the [config system](https://nightly.spacy.io/usage/training#config) and the [CLI train](https://nightly.spacy.io/api/cli#train) functionality instead of implementing custom training loops. In the config, you can define certain components as sourced from another model, and others can be created from scratch, cf https://nightly.spacy.io/usage/training#config-components. 

There's also an example project on using the entity linker in v3 available here: https://github.com/explosion/projects/tree/v3/tutorials/nel_emerson. This toy project works with an entity ruler instead of a pretrained NER, but with the information from the docs you should be able to customize that to your specific use-case.

Hope that helps!

**Comment by lizgzil** [comment] 2021-01-04 09:20
Thank you @svlandeg I will let you know how I get on with that advice 👍

**Comment by svlandeg** [comment] 2021-01-04 10:41
Sounds good! I'll close this in the meantime, but feel free to reopen or open a new issue if you can't get it to work. (for usage questions, you can also use our new discussion board btw! https://github.com/explosion/spaCy/discussions)

**Closed by svlandeg** 2021-01-04 10:41 UTC
Labels: feat / config, feat / pipeline, 🌙 nightly
