### ISSUE TITLE
Inconsistent parse results with 'EntityRuler' added to a pipeline

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#3420] opened 2019-03-18 17:21 UTC
I am experimenting with EntityRuler to augment my statistical model for NER, it works fine. However, when I tried to extract relations between tokens by using parser, I am getting inconsistent results. I am also comparing `sm` and `lg` models with and without `EntityRuler`

`drug_patterns.json` file contains only a few items:

```json
{"label": "DRUG", "pattern": [{"lower": "aspirin"}]}
{"label": "DRUG", "pattern": [{"lower": "abbolactone"}]}
{"label": "DRUG", "pattern": [{"lower": "abboxapam"}]}
{"label": "DRUG", "pattern": [{"lower": "abciximab"}]}
```

```python
import spacy
from spacy.pipeline import EntityRuler 

nlp_sm = spacy.load('en_core_web_sm')

nlp_sm_med = spacy.load('en_core_web_sm')
ruler = EntityRuler(nlp_sm_med).from_disk('drug_patterns.jsonl')
nlp_sm_med.add_pipe(ruler, before='ner')

nlp_lg = spacy.load('en_core_web_lg')

nlp_lg_med = spacy.load('en_core_web_lg')
ruler = EntityRuler(nlp_lg_med).from_disk('drug_patterns.jsonl')
nlp_lg_med.add_pipe(ruler, before='ner')


text = "He was treated with aspirin 50mg po as needed"

spacy.displacy.render(**nlp_sm**(text), style='dep')
```

![Screenshot 2019-03-18 at 16 51 16](https://user-images.githubusercontent.com/20815939/54547696-253e2180-499e-11e9-8e51-c8139fe5ed95.png)

and now the same model, but with `EntityRuler` added:

spacy.displacy.render(**nlp_sm_med**(text), style='dep')

![Screenshot 2019-03-18 at 17 00 29](https://user-images.githubusercontent.com/20815939/54548804-9ed70f00-49a0-11e9-8f4d-a2a5e7038fb9.png)

The large model:

spacy.displacy.render(**nlp_lg**(text), style='dep')

![Screenshot 2019-03-18 at 17 11 28](https://user-images.githubusercontent.com/20815939/54548977-f1183000-49a0-11e9-8345-84c1da1faafc.png)

and now the same large model, but with `EntityRuler` added:

spacy.displacy.render(**nlp_lg_med**(text), style='dep')

![Screenshot 2019-03-18 at 17 12 37](https://user-images.githubusercontent.com/20815939/54549020-0ee59500-49a1-11e9-8a45-d73a83bc2999.png)

------------------------------------------------------------------------------------------

So, if I want to extract relations with the parser, how can I do it if I am getting different results? Am I doing something wrong here?

For example, when using `en_core_web_lg` with EntityRule, `aspirin` is completely detached. Only `en_core_web_sm` with `EntityRule` gives a reasonable result.

Also, regardless of using `EntityRuler`, how can I get consistency results with small and large models?

========================== Info about spaCy ==========================

spaCy version    2.1.0a10
Location         /anaconda3/envs/spacy_nightly/lib/python3.6/site-packages/spacy
Platform         Darwin-18.2.0-x86_64-i386-64bit
Python version   3.6.7
Models           en_core_web_md, en_core_web_lg, en_core_web_sm, en

**Comment by ines** [comment] 2019-03-18 17:24
Thanks for the report – that's very strange 🤔 Just to make sure we can reproduce it with the same state, could you uninstall `spacy-nightly` (2.1.0a10), re-install `spacy` (2.1.0), download the new models and check that the problem still occurs?

**Comment by kormilitzin** [comment] 2019-03-18 18:00
Hi @ines, I upgraded my version and result is the same I'm afraid. I event tried to parse a sentence which does not include the token from the `EntityRuler`. 

![Screenshot 2019-03-18 at 17 55 14](https://user-images.githubusercontent.com/20815939/54552050-245dbd80-49a7-11e9-95fb-abb0d95c3ca5.png)


Good news is that the inconsistency is consistent regardless of whether there are words from within the list of EntityRuler:

![Screenshot 2019-03-18 at 17 58 46](https://user-images.githubusercontent.com/20815939/54552230-86b6be00-49a7-11e9-87de-b2cdb500be5f.png)


I am wondering whether you could you reproduce my error. Please let me know.

**Comment by ines** [comment] 2019-03-18 18:07
Okay, I can't directly reproduce this... unless I did something wrong. So this is like... good and bad. 

But just to isolate it a bit, could you look at the `[t.dep_ for t in doc]` instead of the rendered visualization? And does it also happen if you run the model with the entity ruler first, like in the first cell in your notebook?

**Comment by kormilitzin** [comment] 2019-03-18 18:48
I'm trying to create a colab notebook, to share. I am very puzzled by this behaviour.

Here what I get:

<img width="962" alt="Screenshot 2019-03-18 at 18 45 59" src="https://user-images.githubusercontent.com/20815939/54555294-558dbc00-49ae-11e9-84e8-3e76a1aaea36.png">


<img width="962" alt="Screenshot 2019-03-18 at 18 46 58" src="https://user-images.githubusercontent.com/20815939/54555310-5d4d6080-49ae-11e9-819a-064a31e26ebe.png">

**Comment by kormilitzin** [comment] 2019-03-18 20:00
Hi @ines , I realised where the problem is. I should have pasted the complete workflow (I apologise, I missed this):

As you suggested in https://github.com/explosion/spaCy/issues/3345#issuecomment-468191679 , I added:

```
import spacy
from spacy.pipeline import EntityRuler

patterns = [{"label": "DRUG", "pattern": [{"lower": "aspirin"}]}]


def sent_start_hack(doc):
    # Hard-code sentence boundaries because they need to
    # be set in the pipeline before the parser
    doc[4].is_sent_start = True
    return doc


nlp_sm = spacy.load('en_core_web_sm')

nlp_sm_med = spacy.load('en_core_web_sm')
nlp_sm_med.add_pipe(sent_start_hack, before="parser")
ruler = EntityRuler(nlp_sm_med, patterns=patterns)
nlp_sm_med.add_pipe(ruler, before='ner')


doc_sm = nlp_sm("Quick brown fox jumps over lazy aspirin")
print([t.dep_ for t in doc_sm])
['amod', 'amod', 'nsubj', 'ROOT', 'prep', 'amod', 'pobj']

doc_sm_med = nlp_sm_ned("Quick brown fox jumps over lazy aspirin")
print([t.dep_ for t in doc_sm_med])
['amod', 'amod', 'nsubj', 'ROOT', 'ROOT', 'amod', 'pobj']
```

Now you should be able to reproduce my error. Well, it makes perfect sense why I'm getting these results. So perhaps for the sake of consistency, I will not use your hack.

**Comment by ines** [comment] 2019-03-18 22:58
Ahhh, thanks for the update! This issue really had me worried, so I'm glad it turned out to be not a bug. (My first suspicion was actually that it could be a bug in the visualizer!)

And yes, pretty sure the issue that hack was supposed to fix has been resolved since, so you won't need it anymore!

**Closed by ines** 2019-03-18 22:58 UTC
Labels: usage
