### ISSUE TITLE
Entities found by EntityRuler are modified by NER pipe in French

### ISSUE THREAD

**Issue by olivier-compilatio** [explosion/spaCy#4678] opened 2019-11-20 15:49 UTC
## Problem Description 
I want to use the EntityRuler for French, but when applying it before the NER pipe, it seems that the NER pipe changes the desired output and expands the entities (found by the EntityRuler) until the end of the sentence of each entity. 
Also : 
- When disabling the NER pipe the output is as expected.
- I can't reproduce the issue with the English model. 

## How to reproduce the behaviour

```
import spacy
from spacy.pipeline import EntityRuler  

nlp = spacy.load("fr_core_news_md")
ruler = EntityRuler(nlp)
patterns = [
    {
        "label": "QUANTITY",
        "pattern": [
            {"POS": "NUM", "DEP": "nummod"},
            {"POS": "ADJ", "DEP": "amod", "OP": "*"},
            {"POS": {"IN":  ["NOUN", "PNOUN"]}},
        ]
    },
]
ruler.add_patterns(patterns)
nlp.add_pipe(ruler, before="ner")
doc = nlp(
    "J'ai trouve 10 euros par terre. Les 6 enfants vivent dans trois grandes maisons. Il fait 3°C aujourd'hui, malgré la brume et la tramontane. 6.4 M$ ont été échangés en bourse aujourd'hui."
)
for ent in doc.ents:
    print(ent.text, ent.label_)

```

```
10 euros par terre. QUANTITY # expected output : "10 euros"
6 enfants vivent dans QUANTITY # expected output : "6 enfants"
trois grandes maisons. QUANTITY # expected output : "trois grandes maisons"
3°C aujourd'hui, malgré la brume et la tramontane. QUANTITY # expected output : "3°C"
6.4 M$ ont été échangé en bourse aujourd'hui. QUANTITY # expected output : "6.4 M$"

```

## Your Environment

* Operating System: Ubuntu 18.04 LTS
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.8
* Environment Information:

**Comment by adrianeboyd** [comment] 2019-11-20 16:49
Duplicate of #4229. It should be fixed in v2.2.0+.

**Closed** 2019-11-21 15:50 UTC
Labels: bug, feat / ner
