### ISSUE TITLE
Error with resuming training from saved model on GPU

### ISSUE THREAD

**Issue by sz640** [explosion/spaCy#1806] opened 2018-01-06 00:52 UTC
Hi

I finally got spaCy ner training working on AWS gpu instances. I have no problem training on GPU and saving the model to disk. But when I load the saved model and continue training on more data, it throws errors:

```
Loaded model './models/animal_ner'
Traceback (most recent call last):
  File "train_new_entity_type.py", line 128, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_new_entity_type.py", line 100, in main
    losses=losses)
  File "/usr/local/lib/python3.5/dist-packages/spacy/language.py", line 407, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 688, in spacy.syntax.nn_parser.Parser._make_updates
  File "/usr/local/lib/python3.5/dist-packages/thinc/api.py", line 67, in continue_update
    gradient = callback(gradient, sgd)
  File "/usr/local/lib/python3.5/dist-packages/spacy/_ml.py", line 536, in finish_update
    return ops.unflatten(d_X, lengths, pad=0)
  File "ops.pyx", line 136, in thinc.neural.ops.Ops.unflatten
TypeError: slice indices must be integers or None or have an __index__ method
```

You can reproduce this error with the [train_new_entity_type.py](https://github.com/explosion/spacy/blob/master/examples/training/train_new_entity_type.py) example script by adding `device=0`in `begin_training()` then running:

`python3 train_new_entity_type.py -n 10 -o ./models/animal_ner`

followed by

`python3 train_new_entity_type.py -n 10 -m ./models/animal_ner`

I've actually tried simply loading the model and doing inference and it works fine. And all above steps work on CPU with no errors. 

Any thoughts?

Thanks!

## Your Environment

* Operating System: Ubuntu 16.04 on AWS Deep Learning AMI
* Python Version Used: Python 3.5.2
* spaCy Version Used: 2.0.2
* Environment Information: AWS P2.xlarge instance, cuda 8.0

**Comment by avadhpatel** [comment] 2018-01-11 17:52
Having same error when I run it on Google GPU machine with my code. 

I am running with the following environment:
cupy==2.2.0
spacy==2.0.5
thinc==6.10.2
CUDA 9
OS - Ubuntu 17.04

**Comment by leloss** [comment] 2018-03-28 15:08
Any updates on this? Thanks!
Bug still present in spacy 2.0.10.
Ubuntu 17.10
Python 3.6.3
nvidia-390 driver
nvidia-cuda-toolkit 8.0
cupy 2.5.0
thinc 6.10.2
spacy 2.0.10

**Comment by leloss** [comment] 2018-03-28 17:47
@avadhpatel @sz640 
The problem is actually with thinc. Here is a quick fix that worked for me:

- Uninstall thinc ($ sudo pip3 uninstall thinc)
- Download thinc locally ($ wget https://github.com/explosion/thinc/archive/v6.10.2.tar.gz ... or any other version compatible with spacy).
- untar it ($ tar -xvf thinc-<version>)
- open file <thinc untar-ed folder>/thinc/neural/ops.pyx
- change lines 139, 140 and 141, type casting pad and length to integer (i.e., int(pad) and int(length))
- re-tar it ($ tar -cxvf thinc.tar.gz thinc-<your_version>/)
- re-pip it using this tar-ed version ($ sudo pip3 install thinc.tar.gz)
- (it's probably not necessary to re-install spacy but I did it anyway.)

I hope that helps you guys as well.
L.

**Comment by honnibal** [comment] 2018-03-29 09:18
@leloss Thanks for the fix! Will push that to Thinc.

I'm very confued by your process though. You've edited the .pyx file and not recompiled it with Cython, so the .cpp file within the archive will be the same. How can this work? You should end up with the same shared object file before and after your changes.

**Comment by leloss** [comment] 2018-03-30 16:26
@honnibal 
I just checked and my ops.cpp does look different and shows the changes I made in ops.pyx. I'm not an expert but I believe pip executes the package's setup.py file and compiles them accordingly.

**Comment by honnibal** [comment] 2018-12-08 11:34
This should be fixed in recent versions (e.g. v2.0.18).

**Closed by honnibal** 2018-12-08 11:34 UTC
Labels: bug, gpu, training
