### ISSUE TITLE
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'.

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6589] opened 2020-12-17 20:22 UTC
I still encounter the following error when training a new dataset using spacy-nightly

```
python -m spacy train /config.cfg --paths.train NER_clause1214.spacy --paths.dev NER_clause1123.spacy --output NER_models/
```

```
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues
```

## Your Environment
* Python Version Used: 3.7
* spaCy Version Used: spacy-nightly==3.0.0rc2

**Comment by svlandeg** [comment] 2020-12-17 20:36
We try our best to provide support on both this issue tracker as well as the GH discussion board, but please consider that opening duplicate issues will only further increase our workload.

Duplicate of https://github.com/explosion/spaCy/discussions/6472 and https://github.com/explosion/spaCy/issues/6495.

**Closed by svlandeg** 2020-12-17 20:36 UTC

**Comment by yw2903** [comment] 2020-12-17 20:48
Apologize. The reason I opened this one as the previous two were closed a week ago with no response.

**Comment by svlandeg** [comment] 2020-12-17 20:51
I closed the second, with a comment about it being a duplicate. However the first isn't closed, it's been converted to a thread on the discussion forum: https://github.com/explosion/spaCy/discussions/6472

Did you perceive the conversion as the issue being closed? If that's the case, that's not OK, and we should make sure to comment upon conversion to clarify that the issue was simply moved. The Discussion board is new, and we're still learning how best to deal with it.
