### ISSUE TITLE
Unpickle the parse result without pos / tag

### ISSUE THREAD

**Issue by HanVincent** [explosion/spaCy#2380] opened 2018-05-27 12:58 UTC
Hi, I want to preprocess all the sentences first, so I save the parsed result in pickle file. 
But after I unpickle it, I can't get token.pos_ or token.tag_ 
Is there anything I ignore? Many thanks! : )

Save:
```python3
nlp = spacy.load('en_core_web_lg') # ('en')

fs = open('test.txt', 'r', encoding='utf8')
docs = nlp.pipe([line.strip().lower() for line in fs]) # minibatching - faster

doc_bytes = [doc.to_bytes(user_data=True) for doc in docs]
vocab_bytes = nlp.vocab.to_bytes()

with open("processed.pickle","wb") as handle:
    pickle.dump((doc_bytes, vocab_bytes), handle)
```

Restore:
```python3
with open("processed.pickle", "rb") as handle:
    doc_bytes, vocab_bytes = pickle.load(handle)
    
nlp.vocab.from_bytes(vocab_bytes)
docs = [Doc(nlp.vocab).from_bytes(b) for b in doc_bytes]
```

Result:
```python3
tk = docs[1][6]
print(tk) # 'is'
print(tk.text)  # 'is', works well
print(tk.tag_) # get empty ''
print(tk.pos_) # get empty ''
```

## Your Environment

* **Python version:** 3.5.2
* **spaCy version:** 2.0.11
* **Platform:** Linux-4.14.12-041412-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by honnibal** [comment] 2018-06-04 22:41
It really looks like you're doing everything correctly here, so I'd say this is likely to be a bug in the way the `Morphology` class is serialized and deserialized. This component (which lives at `nlp.vocab.morphology`) controls the assignment of the tag attributes to the tokens, and sets the implied coarse-grained POS as well.

The weird thing is, if this is broken how isn't the deserialization of tags broken much more generally?! We do have tests for this, so I'm not sure what's going on. If you compare the `.tag` value, rather than the string it maps to, is that 0 as well, or does it get set? You can also use `msgpack.loads()` to deserialize the bytes representation, so you can poke around and see what the data's like.

**Comment by HanVincent** [comment] 2018-06-05 01:54
Yeah, I also tried .tag/.pos to see its value, it still return 0.
```python3
print(tk) # 'is'
print(tk.text)  # 'is', works well
print(tk.tag) # get 0
print(tk.pos) # get 0
```
I have to complete my term project this week, so I will try msgpack or figure out this recently.

**Comment by hadsed** [comment] 2018-08-22 02:03
I use msgpack to dump the docs. When reading back the object I get is the same behavior for the POS attribute (all zeros/nulls, even though they are there correctly before serialization), but the tags are actually made it through. Only difference is I used the `en_core_web_sm` instead of 'lg` and I used msgpack instead of pickle. I do something like this:

```python
docs = [(doc_id, nlp(text)) for doc_id, text in texts]
vocab = docs[0].vocab
d = {doc_id: parsed.to_bytes(tensor=False) for doc_id, parsed in docs}
d['vocab'] = vocab.to_bytes()
with open(filename, 'wb') as f:
    f.write(msgpack.dumps(d))
```
Then later I read it back like so:
```python
m = msgpack.load(open(filename, 'rb'))
v = Vocab().from_bytes(m['vocab'])
d = Doc(v).from_bytes(m[some_doc_id])
any([t.pos_ for t in d]), any([t.tag_ for t in d])
```
First thing is `False`, second thing is `True`.

**Comment by hadsed** [comment] 2018-08-22 03:06
OK I think the problem is actually pretty clear. Somewhere in the `Doc.to_bytes()` method there needs to be an additional item for the POS identifier: https://github.com/explosion/spacy/blob/master/spacy/tokens/doc.pyx#L778

Indeed, adding the `POS` variable to the end of the `array_head` list solves the issue (after recompiling spacy from source).

**Comment by hadsed** [comment] 2018-08-28 20:56
@ines Hoping this ping reaches you. This one's a quick fix, hoping I don't have to run my own fork here as it's... not ideal.

**Comment by honnibal** [comment] 2018-12-16 16:45
@HanVincent Just failed to reproduce this now, and realised that the issue was resolved in a prior patch. The problem was that the `doc.is_tagged` attribute was being set at the incorrect level of indentation during the `Tagger.set_annotations` method. This caused the attribute to only be set correctly during the `__call__()` method, not `.pipe()`, because in `__call__` we only have one doc per batch.

@hadsed The `.pos` attribute should only be set when the `.tag` attribute is set, so we shouldn't need to serialize them separately. So long as the `.is_tagged` attribute is set correctly, I think there shouldn't be a problem. Let me know if troubles persist. And of course, you can always submit a PR instead of running your own fork :).

**Closed by honnibal** 2018-12-16 16:45 UTC
Labels: bug, feat / serialize

**Comment by hadsed** [comment] 2019-01-01 23:54
@honnibal Happy to do a PR, just wanted to make sure this is the right thing to fix.

```python
import spacy
import msgpack
nlp = spacy.load('en_core_web_sm')
texts = [(101, 'mary had a lamb.')]
docs = [(doc_id, nlp(text)) for doc_id, text in texts]
vocab = docs[0][1].vocab
d = {doc_id: parsed.to_bytes(tensor=True) for doc_id, parsed in docs}
d['vocab'] = vocab.to_bytes()
filename = '/tmp/doc_dump.msgpk'
with open(filename, 'wb') as f:
f.write(msgpack.dumps(d))
from spacy.vocab import Vocab
from spacy.tokens import Doc
m = msgpack.load(open(filename, 'rb'))
v = Vocab().from_bytes(m[b'vocab'])
d = Doc(v).from_bytes(m[101])
any([t.pos_ for t in d]), any([t.tag_ for t in d])
```
