### ISSUE TITLE
Problem with : !python -m spacy project clone tutorials/ner_fashion_brands

### ISSUE THREAD

**Issue by herringbone64** [explosion/spaCy#8235] opened 2021-05-30 03:17 UTC
Hi There,
I installed spaCy v3.0.6 successfully, but run into the following when I try to run "!python -m spacy project clone tutorials/ner_fashion_brands". Any idea on what might be the problem? 

```
Traceback (most recent call last):
  File "/opt/conda/envs/Python-3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/cli/project/clone.py", line 39, in project_clone_cli
    project_clone(name, dest, repo=repo, branch=branch, sparse_checkout=sparse_checkout)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/cli/project/clone.py", line 62, in project_clone
    git_checkout(repo, name, dest, branch=branch, sparse=sparse_checkout)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/cli/_util.py", line 397, in git_checkout
    run_command(cmd, capture=True)
  File "/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/spacy/util.py", line 844, in run_command
    raise error
subprocess.SubprocessError: Error running command:

git -C /tmp/wsuser/tmpd0r1go5s clone https://github.com/explosion/projects . -b v3

Subprocess exited with status 129

Process log (stdout and stderr):

Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by polm** [comment] 2021-05-30 04:42
Since this looks like an install related problem and not a bug I'm moving it to Discussions, follow the link to see the Discussion.

**Closed** 2021-05-30 04:43 UTC
