### ISSUE TITLE
[Tokenizer] Cannot add the DOT in the infixes expression

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1488] opened 2017-11-03 11:31 UTC
## Your Environment
* Operating System: Ubuntu 16.04
* Python Version Used: 3.5.2
* spaCy Version Used:  2.0 nightly

Hello 
When i try to  add the DOT inside the non-whitespace separators expression i get the following error.

```
import spacy
import re
from spacy.tokenizer import Tokenizer

prefix_re = re.compile(r'''[\[\("']''')
suffix_re = re.compile(r'''[\]\)"']''')
infix_re = re.compile(r'''[-~\.]''')
simple_url_re = re.compile(r'''^https?://''')

def my_tokenizer(nlp):
    return Tokenizer(nlp.vocab,
                     {},
                     prefix_search=prefix_re.search,
                     suffix_search=suffix_re.search,
                     infix_finditer=infix_re.finditer,
                     token_match=simple_url_re.match)

nlp = spacy.load('en')
nlp.tokenizer = my_tokenizer(nlp)

doc = nlp("This is a test.")

for token in doc :
    print(token.text)
```

Error:

```
/home/damiano/lavoro/python/virtualenvs/parser/bin/python /home/damiano/lavoro/python/parser/test.py
Traceback (most recent call last):
  File "/home/damiano/lavoro/python/parser/test.py", line 24, in <module>
    doc = nlp("This is a test.")
  File "/home/damiano/lavoro/python/virtualenvs/parser/lib/python3.5/site-packages/spacy/language.py", line 308, in __call__
    doc = self.make_doc(text)
  File "/home/damiano/lavoro/python/virtualenvs/parser/lib/python3.5/site-packages/spacy/language.py", line 316, in make_doc
    return self.tokenizer(text)
  File "tokenizer.pyx", line 118, in spacy.tokenizer.Tokenizer.__call__
  File "tokenizer.pyx", line 153, in spacy.tokenizer.Tokenizer._tokenize
  File "tokenizer.pyx", line 251, in spacy.tokenizer.Tokenizer._attach_tokens
  File "doc.pyx", line 533, in spacy.tokens.doc.Doc.push_back
AssertionError
```

**Comment by ines** [comment] 2017-11-03 13:50
Thanks for the report! Just added an isolated test for this (see f0986df) and it seems to pass using the latest version on `develop`. It might be that the error was caused by some other issue that was fixed in the meantime, or maybe there's something else going on.

We're about to release the new version, so once that's out, could you try again and see if it works for you?

**Comment by damianoporta** [comment] 2017-11-03 13:58
Sure @ines !
When will you release the new version?

**Comment by ines** [comment] 2017-11-03 14:02
Definitely later today – as soon as Travis goes green, the package finished building and we've had lunch 😛

**Comment by damianoporta** [comment] 2017-11-03 14:06
:D Ok i will test it

**Comment by ines** [comment] 2017-11-03 14:14
If you're very impatient, you can also just clone spaCy from `develop` and build it from source:

```bash
pip install -r requirements.txt
python setup.py build_ext --inplace
export PYTHONPATH=`pwd`
```

**Comment by damianoporta** [comment] 2017-11-03 14:43
I am trying to be patient haha :)

**Comment by ines** [comment] 2017-11-03 20:53
Try again now? Also see my comment in #1491 regarding the adjustments needed for the prefix and infix functions. I'm about 99% confident that this will solve your problem.

**Comment by damianoporta** [comment] 2017-11-05 18:48
@ines Ok, now it splits the DOT correctly.

**Closed** 2017-11-05 18:51 UTC
Labels: v2
