### ISSUE TITLE
`LEMMA_ACC` missing in English models

### ISSUE THREAD

**Issue by Riccorl** [explosion/spaCy#8357] opened 2021-06-11 11:48 UTC
There is no `LEMMA_ACC` value for the English models ([https://spacy.io/models/en](https://spacy.io/models/en)).

Is this intended? What are the lemmatization performance of the English models?

**Comment by polm** [comment] 2021-06-12 08:33
Not a bug so moving to Discussions...

**Closed** 2021-06-12 08:33 UTC
