### ISSUE TITLE
prob = -20.0 for all lemmas in en_core_web_sm

### ISSUE THREAD

**Issue by udibr** [explosion/spaCy#1590] opened 2017-11-16 12:37 UTC
```
import spacy
nlp = spacy.load('en_core_web_sm')
{w.prob for w in nlp.vocab}
```

spacy (from master) 2.0.3
en_core_web_sm 2.0.0

this problem does not appear in en_core_web_lg 2.0.0

**Comment by damianoporta** [comment] 2017-11-16 16:08
Same issue with italian model.

**Comment by noeddl** [comment] 2017-11-27 11:01
I noticed the same problem for the German model. Seems as if this is a general issue with the small models.

**Comment by noeddl** [comment] 2017-12-04 14:51
I'm building an application which is relying on the prob-attribute right now and I would like to be able to use it in several languages (for most of which only small models are available at the moment).

It would be helpful to know whether this problem (prob always being -20) is a bug that can be fixed or whether it's maybe a functionality that simply does not work with the small models (similar to word vectors only being available in larger models).

Is there maybe some alternative way in spacy to find out the "general" frequency or probability of a word?

**Comment by jmlange** [comment] 2017-12-17 16:53
Same problem for French 'medium' model.
    spaCy version      2.0.5          
    Platform           Windows-10-10.0.15063-SP0
    Python version     3.6.2          
    Models             fr, fr_core_news_md

**Comment by gsoul** [comment] 2017-12-22 00:02
Same issue

**Comment by nithinshiriya** [comment] 2017-12-27 22:39
Same Issue with me as well.  Is there any workaround for this?.  Or please suggest us with the right version.

**Comment by gsoul** [comment] 2018-01-10 10:17
@ines @honnibal sorry for disturbing, but could you please advise if you have any ETA for this?

**Comment by honnibal** [comment] 2018-01-16 12:43
@gsoul We've been working through the backlog on spaCy that built up while I was on holidays over December. I think we'll probably get this resolved in the next week or so.

Merging this thread with #1574 , as the root cause of both is the same.

**Closed by honnibal** 2018-01-16 12:43 UTC
Labels: bug, models
