### ISSUE TITLE
i am not able to download en modules like sm, md.

### ISSUE THREAD

**Issue by ipratham101** [explosion/spaCy#12731] opened 2023-06-16 05:38 UTC
please help i am trying this from 2 days tried around 50 methods none worked
now am kinda lost the motivation to learn about spacy, this is going to be my last hope

## Which page or section is this issue related to?

error->

C:\Users\Divyansh Ahuja>python -m spacy download en

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy\tokens\doc.pyx", line 36, in init spacy.tokens.doc
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\schemas.py", line 158, in <module>
    class TokenPatternString(BaseModel):
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\main.py", line 369, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\utils.py", line 231, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\Divyansh Ahuja\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2725, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'in' is not a valid parameter name

C:\Users\Divyansh Ahuja>

**Comment by kadarakos** [comment] 2023-06-21 09:15
Seems like an installation issue. I would suggest maybe a fresh install in a virtual environment, for example I like using `conda`, but others prefer `venv`. Also please don't feel deterred, installation is difficult often, for example I stopped using Windows, when I started programming for this reason (some people are amazing at dealing with Windows though). 

I also recommend the `spaCy` course for you. Its free and gives a lot of information on how to get started: https://course.spacy.io/en/

**Comment by teleprint-me** [comment] 2023-07-12 20:34
I'm getting the same error in a fresh and properly setup environment.

```sh
16:30:22 | ~/Documents/code/git/pygptprompt
(.venv) git:(dev | Δ) λ python -m spacy download en_core_web_sm                                  
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/pipeline/attributeruler.py", line 8, in <module>
    from ..language import Language
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/language.py", line 42, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/tokens/_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "spacy/tokens/doc.pyx", line 49, in init spacy.tokens.doc
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/spacy/schemas.py", line 180, in <module>
    class TokenPatternString(BaseModel):
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/pydantic/main.py", line 291, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/austin/Documents/code/git/pygptprompt/.venv/lib/python3.11/site-packages/pydantic/utils.py", line 256, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'in' is not a valid parameter name
```

I'm on Linux and got the same error.

**Comment by teleprint-me** [comment] 2023-07-12 21:16
I am happy to announce that I have found a fix for the issue I posted previously regarding the `TypeError: __init__() got multiple values for keyword argument "in"`. Here's how I went about it.

The issue arises from the fact that `in` is a Python keyword and it is used as an attribute in the `TokenPatternString` and `TokenPatternNumber` classes in `spacy/schemas.py`, which are Pydantic models. Pydantic tries to convert the variable to an attribute and runs into an error because `in` is a reserved keyword in Python.

The two problematic classes are:

1. `TokenPatternString`

2. `TokenPatternNumber`

To resolve the issue, the attribute `IN` in both classes should be renamed to avoid conflict with the Python keyword. I suggest renaming `IN` to `IN_LIST`. This necessitates modifying these classes as follows:

**From:**
```py
class TokenPatternString(BaseModel):
    REGEX: Optional[Union[StrictStr, "TokenPatternString"]] = Field(None, alias="regex")
    IN: Optional[List[StrictStr]] = Field(None, alias="in")  # Change 'IN' to 'IN_LIST'
```
**To:**
```py
class TokenPatternString(BaseModel):
    REGEX: Optional[Union[StrictStr, "TokenPatternString"]] = Field(None, alias="regex")
    IN_LIST: Optional[List[StrictStr]] = Field(None, alias="in_list")  # Change 'IN' to 'IN_LIST'
```

**From:**
```py
class TokenPatternNumber(BaseModel):
    REGEX: Optional[StrictStr] = Field(None, alias="regex")
    IN: Optional[List[StrictInt]] = Field(None, alias="in")  # Change 'IN' to 'IN_LIST'
```
**To:**
```py
class TokenPatternNumber(BaseModel):
    REGEX: Optional[StrictStr] = Field(None, alias="regex")
    IN_LIST: Optional[List[StrictInt]] = Field(None, alias="in_list")  # Change 'IN' to 'IN_LIST'
```

This change doesn't break anything else, as the `alias` is still set to the original "in" keyword, so it doesn't interfere with the loading of existing trained models or saved data.

Please let me know if you need more information about this issue or the suggested solution. I'm looking forward to your feedback and suggestions.

**Comment by teleprint-me** [comment] 2023-07-13 20:11
@svlandeg

```sh
============================================================================ 4115 passed, 568 skipped, 68 xfailed, 3 xpassed in 449.84s (0:07:29) ============================================================================
16:03:08 | ~/Documents/code/git/spaCy
(.venv) git:(fix-model-dl-iss-12731 | θ) λ python -V                  
Python 3.11.3
16:10:28 | ~/Documents/code/git/spaCy
(.venv) git:(fix-model-dl-iss-12731 | θ) λ pip list --format=columns | grep spacy         
spacy              3.6.0      /home/austin/Documents/code/git/spaCy
spacy-legacy       3.0.12
spacy-loggers      1.0.4

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
16:10:46 | ~/Documents/code/git/spaCy
(.venv) git:(fix-model-dl-iss-12731 | θ) λ pip list --format=columns | grep pydantic
pydantic           1.10.11

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by svlandeg** [comment] 2023-07-14 07:43
Thanks again! I've been trying to replicate this using both Python 3.10 and 3.11, installing `spacy==3.6.0` which pulls in `pydantic==1.10.11`. So far the `download` command just keeps working fine for me 😕 

That said, we'll definitely have a look at your PR, but as you noted that this would be breaking the loading of current models, we would not be able to release this patch before the next minor release.

I know this is not ideal, but in the meantime, here's a workaround:
On the [models](https://spacy.io/models/) page, navigate to the model you need and click "Release details". You can download the `tar.gz` file and `pip install` directly from that instead of going through the `download` command.

**Comment by teleprint-me** [comment] 2023-07-14 16:32
@svlandeg 

I was able to get `py.test` working and all the tests I could run passed (`py.test spacy` and `py.test spacy --slow`.

I noticed a regression from changing the property value but not the alias. I don't have the time or funds to do a deep dive, but reverting the properties seemed to have solved the regressions.

I haven't had the time to update my PR and add it as a note. I wasn't sure how to provide an additional test to this, even after reading the docs on testing, so I did what I could.

I would still proceed with caution regardless and understand why devs would need to take their time with this (seeing as this is a complex library and build process).

While relative imports can be nice from a feature point of view, I've learned to recognize they can be problematic in more situations than it's worth.

Either way, I appreciate the reply and the suggested workaround. I look forward to the update seeing as I've decided to stick with spaCy and to use it in my some of my projects moving forward.

**Comment by adrianeboyd** [comment] 2023-07-21 07:55
This issue appears to be a duplicate of #11664. Python 3.11 is supported by pydantic v1.10.0+ and spaCy v3.4.2+.

Please see additional details and tips in some related issues and comments:

* https://github.com/explosion/spaCy/issues/12697#issuecomment-1577309702
* https://github.com/explosion/spaCy/pull/12819#issuecomment-1638443887
* https://github.com/explosion/spaCy/pull/12819#issuecomment-1645092919

**Closed** 2023-07-29 00:05 UTC
Labels: duplicate, third-party, compat, resolved
