### ISSUE TITLE
Error should be raised if you try to set conflicting doc.ents

### ISSUE THREAD

**Issue by chandan2495** [explosion/spaCy#2550] opened 2018-07-16 10:18 UTC
## How to reproduce the behaviour
```python
import spacy
from spacy.tokens import Span
nlp = spacy.load('en_core_web_sm')
doc = nlp(u"Louisiana Office of Conservation")
print(doc.ents[0], doc.ents[0].label_)

entity = Span(doc, 0, 1, label=391L)
print(entity, entity.label_)

doc.ents = list(doc.ents) + [entity]

print(doc.ents[0], doc.ents[0].label_)
```
## Output:
`(Louisiana Office of Conservation, u'ORG')`
`(Louisiana, u'MONEY')`
`(Louisiana Office of Conservation, u'MONEY')`

## Expected Behaviour:
I was expecting MONEY entity to override the ORG entity and end offset of MONEY should have been used after merging. Please let me know if I got this wrong.

## Your Environment
* Operating System:Windows 7
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.7
* Environment Information: None

**Comment by ines** [comment] 2018-07-16 10:49
Thanks a lot for the great and detailed bug report 👍  I just tried the example and I can confirm that it's also reproducible in v2.1.0 nightly. The current behaviour is definitely a bug.

In terms of the expected behaviour: I suggest that spaCy should actually raise an error here. By definition, a token can only be part of *one* entity. So when the `doc.ents` are set and an overlapping entity exists, there's no clear answer for how this should be resolved. Which entity should take precedence? 

So it's probably more intuitive and logical if spaCy raised with a message like: "Trying to set conflicting `doc.ents`: `(0, 4, 'ORG')` and `(0, 1, 'MONEY')`. A token can only be part of one entity, so make sure the entities you're setting don't overlap."

**Comment by chandan2495** [comment] 2018-07-17 07:41
Thanks for quick reply Ines. I think the new span can take preference on existing one as this will help users to create new derived entities.

**Comment by honnibal** [comment] 2018-12-20 11:59
This is fixed now in `spacy-nightly`. See also #2566.

**Closed by honnibal** 2018-12-20 11:59 UTC
Labels: bug, feat / doc, feat / ner

**Comment by isaacmg** [comment] 2018-12-21 05:43
I actually am finding the raising of an error here is causing more problems for me than resolving. I have many causes where I have for instance both "Jon" and and "Jon Smith" as NAME entities. I do want both tagged as a NAME. I would prefer instead in such cases to tag whichever entity has more tokens as this is likely to be more specific rather than raising an error. There are many other instances as well and I do not want to change my setup to exclude overlapping.

**Comment by rbhambriiit** [comment] 2018-12-25 09:17
I would like spaCy to preserve the longer entity as well. 

@isaacmg 
Both "Jon" and and "Jon Smith" can not be tagged as named since in first case 'Jon' gets a tag of 'U' 
whereas in second case a 'B'. Model is bound to be confused.

One way as mentioned already is to take care of the overlaps.

Also there are scenarios where same token / char span is tagged to 2 entities. I guess that comes up as an error now. Not tested.

**Comment by isaacmg** [comment] 2019-01-17 02:54
@honnibal  I would like an answer about how to override this error message at the very least. As it is currently a blocker.

**Comment by rbrtdambrosio** [comment] 2019-02-11 13:16
There is a way to handle the error here? 
Indeed to have the entity with the maximum length as default would be great.

**Comment by phdowling** [comment] 2019-02-27 16:12
I am also running into this as a problem, I have a PhraseMatcher finding entities on top of the NER pipeline, but I would like to be able to link both entities. What's the suggested workaround?

**Comment by dmarx** [comment] 2019-03-13 19:24
Can someone provide sample code illustrating how to make the longer and/or newer span take precedence? @rbhambriiit, it sounds like you might know how to do this?
