### ISSUE TITLE
Lookups data not serialized with latest nl_core_news_sm

### ISSUE THREAD

**Issue by lonneke123** [explosion/spaCy#4589] opened 2019-11-05 12:33 UTC
## How to reproduce the behaviour
doc = nlp(('Hallo, ik ben Piet. Ik heb gisteren iets gekocht.'))
for w in doc:
  print(w.text, w.pos_, w.lemma_)

The result is:
hallo X hallo
, PUNCT ,
ik PRON ik
ben VERB ben
piet NOUN piet
. PUNCT .
ik PRON ik
heb VERB heb
gisteren ADV gisteren
iets PRON iets
gekocht VERB gekocht
. PUNCT .

So no word is lemmatized. This is happening since the new release. The pos tagger does work

**Comment by ines** [comment] 2019-11-05 12:55
Are you using the latest model? You can run `python -m spacy validate` to check.

I just tried it locally using the latest spaCy (v2.2.2) and the latest compatible version of the model (v2.2.1) and my results look like this:

```
Hallo NOUN hallo
, PUNCT ,
ik PRON ik
ben VERB zijn
Piet NOUN piet
. PUNCT .
Ik PRON ik
heb VERB hebben
gisteren ADV gisteren
iets PRON iets
gekocht VERB kopen
. PUNCT .
```

**Comment by lonneke123** [comment] 2019-11-05 13:31
![image](https://user-images.githubusercontent.com/57399169/68211410-ca624480-ffd7-11e9-8a0d-77138dc6c41d.png)

Yes I use the versions you mentioned above. (see printscreen) I tried installing other packages, but it doesn't solve the issue.

**Comment by lemontheme** [comment] 2019-11-05 14:38
The Dutch lemmatizer makes extensive use of lookup tables. These have been moved to a separate package in the new release. Have you already tried `pip install spacy-lookups-data` -- or, alternatively -- `pip install spacy[lookups]`?

**Comment by adrianeboyd** [comment] 2019-11-05 14:40
It only works with `spacy-lookups-data` installed, so I think the tables didn't get packaged with the model as intended?

**Comment by lemontheme** [comment] 2019-11-05 14:53
Prepare to be surprised, but that's actually the expected behavior. The idea is that lemmatization data is an attribute of individual Language subclasses (e.g., as defined in spacy/lang/nl/\_\_init\_\_.py). In fact, previous versions included this data as large dictionaries in python modules that sometimes took up upwards of 10MB in disk space. Trouble is -- as more languages added lemmatization data,  spaCy came to mean a fairly hefty download. The core developers have begun remedying this situation in the latest release.

**Comment by ines** [comment] 2019-11-05 16:16
The lemmatizer data should be shipped in the models, though, and serialize to disk when you save out the `nlp` object. If that's not the case, that's definitely a bug. 

I just checked and the `vocab` directory of the installed model doesn't include the lookup files – maybe the lookups data package wasn't available when the model was trained. So we should fix that. In the meantime, installing `spacy-lookups-data` is a fine workaround.

**Comment by lemontheme** [comment] 2019-11-05 19:05
Huh... I stand corrected. My bad!

**Comment by ines** [comment] 2019-11-06 10:20
@lemontheme Everything else you said and how you explained the lookups was correct, though!

**Comment by adrianeboyd** [comment] 2019-11-22 09:22
This has been fixed in newer `nl` model releases.

**Closed by adrianeboyd** 2019-11-22 09:22 UTC
Labels: bug, models, upgrade
