### ISSUE TITLE
Loaded NER Model gives different results

### ISSUE THREAD

**Issue by ak3895** [explosion/spaCy#3458] opened 2019-03-22 10:12 UTC
I followed the spaCy documentation to train my custom NER Model but I cant seem to get the same results from the saved model.
This is the result when I use the trained object to predict which gives me the correct set of results.
![Screenshot from 2019-03-22 15-29-57](https://user-images.githubusercontent.com/42930917/54815176-5f1d6980-4cb7-11e9-8933-690c8a96ee77.png)
Saved the model obtained on training and got completely different and wrong results for same textual data input. Output shown in below image:
![Screenshot from 2019-03-22 15-39-12](https://user-images.githubusercontent.com/42930917/54815806-c5ef5280-4cb8-11e9-9218-f571c4bf339a.png)

Any help appreciated.

##  Environment Details

* Platform: Linux-4.15.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
* Python Version : 3.5.2
* spaCy Version : 2.1.1

**Comment by honnibal** [comment] 2019-03-22 12:52
Thanks for the report. I think this probably has the same root cause as #3433 . It's currently our highest priority bug.

**Comment by honnibal** [comment] 2019-03-23 11:33
Confirmed this is the same as #3433. I think I've got a fix now. Closing this to merge with the prior thread.

**Closed by honnibal** 2019-03-23 11:33 UTC
Labels: bug, feat / ner

**Comment by chaitanya1019** [comment] 2019-04-17 06:08
> I followed the spaCy documentation to train my custom NER Model but I cant seem to get the same results from the saved model.
> This is the result when I use the trained object to predict which gives me the correct set of results.
> ![Screenshot from 2019-03-22 15-29-57](https://user-images.githubusercontent.com/42930917/54815176-5f1d6980-4cb7-11e9-8933-690c8a96ee77.png)
> Saved the model obtained on training and got completely different and wrong results for same textual data input. Output shown in below image:
> ![Screenshot from 2019-03-22 15-39-12](https://user-images.githubusercontent.com/42930917/54815806-c5ef5280-4cb8-11e9-9218-f571c4bf339a.png)
> 
> Any help appreciated.
> 
> ## Environment Details
> * Platform: Linux-4.15.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
> * Python Version : 3.5.2
> * spaCy Version : 2.1.1

Hey @ak3895, are you trying to train your model to parse the resumes?
If so, can you please help me with this [https://github.com/explosion/spaCy/issues/3528#issuecomment-483947072](issue)

**Comment by chaitanya1019** [comment] 2019-04-18 05:02
@ak3895 can u provide with your link to ur repo for the resume parsing/ the dataset that you have used.

**Comment by chaitanya1019** [comment] 2019-04-18 05:04
@ak3895 also did you add additional entity types to an existing pretrained ner model(eg: en_core_web_sm) like the one mentioned [here](https://spacy.io/usage/training#example-new-entity-type)
