### ISSUE TITLE
Lemmatizer and POS issue with french model

### ISSUE THREAD

**Issue by campdav** [explosion/spaCy#1297] opened 2017-09-02 16:58 UTC
Hi everyone
I am facing issues when I want to use french model to perform few tasks : retrieve sentences and run POS.

I install first the french model:
`python -m spacy download fr`

Then, here are simple code to reproduce the problem:
`import spacy`
`nlp = spacy.load("fr")`
`doc = nlp("Mon petit doigt me dit que ce sont pourtant les bonnes réponses. Il n'y a pas de doutes.")`
`print([(sent.text) for sent in doc.sents])`
`print([(word.text, word.lemma, word.lemma_, word.tag, word.tag_, word.pos, word.pos_) for word in doc])`

- Sentences are not correctly defined (the cut occurs after the "y" instead of the punctuation)
- during the POS: the lemmatization is not working at all,
- POS for verbs show SYM instead of VERB.

I do not reproduce the issue with english model on english sentences.

## Your Environment
* Operating System: MacOS 10.12.6
* Python Version Used: 3.5.3
* spaCy Version Used: 1.9.0

**Comment by 0asa** [comment] 2017-09-05 09:53
Hi! 

AFAIK:

- lemma is not supported for french, according to https://spacy.io/docs/api/language-models
- Sentence tokenization is a know issue (https://github.com/explosion/spaCy/issues/1044) and will be fixed in Spacy 2.0
- for the POS/SYM/VERB issue do you have examples to share?

**Comment by campdav** [comment] 2017-09-05 10:15
HA ! Too bad for the lemma...

Regarding the POS/SYM/VERB:

*>>> import spacy*
*>>> nlp = spacy.load('fr')*
*>>> doc = nlp("Le chat mange la souris.")*
*>>> print([(word.text, word.pos_) for word in doc])*

*[('Le', 'DET'), ('chat', 'NOUN'), ('mange', 'SYM'), ('la', 'DET'), ('souris', 'NOUN'), ('.', 'PUNCT')]*

However, **('mange', 'SYM')** should be **('mange', 'VERB')**

*>>> doc = nlp("La souris est mangée par le chat.")*
*>>> print([(word.text, word.pos_) for word in doc])*

*[('La', 'DET'), ('souris', 'NOUN'), ('est', 'AUX'), ('mangée', 'SYM'), ('par', 'ADP'), ('le', 'DET'), ('chat', 'NOUN'), ('.', 'PUNCT')]*

Also, **('mangée', 'SYM')** should be **('mangée', 'VERB')**

**Comment by 0asa** [comment] 2017-09-06 11:38
Using Spacy 1.8.2 gives the right POS...
Looks like that's something "new" in 1.9

**Comment by campdav** [comment] 2017-09-07 10:00
Thanks for your feedback. Hoping it will be fixed in v2.

**Comment by Gullfaxi171** [comment] 2017-09-20 14:31
Same issue here : 
- using 1.9 : wrong POS for verbs
- rolling back to 1.8.2 : good POS but crash because of this bug : https://github.com/explosion/spaCy/issues/1052
- correcting the issue with adding TAG MAP for SP : no more crash, but wrong POS are back

Seems like the 2 issues ar linked

**Comment by ines** [comment] 2017-11-09 16:16
Just tried it with the [new French model](https://spacy.io/models/fr) for v2.0, `fr_core_news_sm` and it looks like the problem is resolved:

```bash
>>> import fr_core_news_sm
>>> nlp = fr_core_news_sm.load()
>>> doc = nlp("Mon petit doigt me dit que ce sont pourtant les bonnes réponses. Il n'y a pas de doutes.")

>>> print([(sent.text) for sent in doc.sents])
['Mon petit doigt me dit que ce sont pourtant les bonnes réponses.', "Il n'y a pas de doutes."]

>>> print([(word.text, word.lemma_, word.pos_) for word in doc])
[('Mon', 'mon', 'DET'), ('petit', 'petit', 'ADJ'), ('doigt', 'doigt', 'NOUN'), ('me', 'se', 'PRON'), 
('dit', 'dire', 'VERB'), ('que', 'que', 'SCONJ'), ('ce', 'ce', 'PRON'), ('sont', 'être', 'AUX'), 
('pourtant', 'pourtant', 'ADV'), ('les', 'le', 'DET'), ('bonnes', 'bonne', 'ADJ'), 
('réponses', 'réponse', 'NOUN'), ('.', '.', 'PUNCT'), ('Il', 'il', 'PRON'), ("n'", 'ne', 'ADV'), 
('y', 'yu', 'PRON'), ('a', 'avoir', 'VERB'), ('pas', 'pas', 'ADV'), ('de', 'de', 'DET'), 
('doutes', 'douter', 'NOUN'), ('.', '.', 'PUNCT')]
```

The `fr_core_news_md` model might even perform a little better overall.

**Closed by ines** 2017-11-09 16:16 UTC
Labels: language / french, models
