### ISSUE TITLE
[Rule-Based Matching] Clarify that while attribute names are case-insensitive, attribute values are case-sensitive

### ISSUE THREAD

**Issue by jabortell** [explosion/spaCy#6410] opened 2020-11-19 16:29 UTC
On the [Rule-based Matching page](https://spacy.io/usage/rule-based-matching), there's a Q&A box titled "Does it matter if the attribute names are uppercase or lowercase?", and the answer is "No, it shouldn't." While using the [Matcher Explorer](https://explosion.ai/demos/matcher), I discovered after some confusion that while the attribute names (POS, TAG, DEP, etc) can be any case, the attribute values (VERB, nsubj) are case-sensitive. I think it'd be helpful to clarify that this is the expected behavior, or to make the attribute values case-insensitive as well, although that would of course leave the realm of a documentation issue entirely.

## Which page or section is this issue related to?
https://spacy.io/usage/rule-based-matching

**Comment by svlandeg** [comment] 2020-11-20 10:01
I'm a little unsure. I understand your confusion, but I wonder whether adding a sentence about "values" might actually confuse other readers? How would you phrase it? The problem is that that section is really specifically about the attribute names, so I'm not even sure about the terminology "values" - we don't really use it up until that point.

Perhaps it would help to add an example with the 4 possibilities - name & value lower-cased or upper-cased, and show the resulting matches? Perhaps some sentence with a wild card where matching on a lower-cased value gives a different result than the upper-cased value? But they each remain the same when changing the attribute from lower to upper?

**Comment by jabortell** [comment] 2020-11-20 16:45
I see that I could've been more specific about what I meant  the attribute "values", as some of them can be bools, regexes, etc, for which of course it wouldn't make sense to talk about case sensitivity. And to be clear, I wasn't talking about string-matching attributes (ORTH, etc), for which the user is using for its case-sensitivity, but about the attributes (at least POS and DEP) which take values ("VERB" and "nsubj") that are looked up in a dictionary. I think it makes sense to mention *somewhere* that the user can go wrong if the case doesn't match.

It makes sense in my brain that similar information should be close together, so likewise, it'd make sense to me that documentation about the case-sensitivity of values of POS/DEP/etc would go with the documentation about the case-sensitivity of the attribute names.

That's my thinking on it, but I'm not a contributor or anything like that, so feel free to disregard and move on :)

**Comment by svlandeg** [comment] 2020-11-20 18:40
> It makes sense in my brain that similar information should be close together, so likewise, it'd make sense to me that documentation about the case-sensitivity of values of POS/DEP/etc would go with the documentation about the case-sensitivity of the attribute names.

Sure, but it depends on how you look at it, you could also say that you'd expect the documentation on the attribute keys to be together, and the documentation about the values to be together ;-) I'm not trying to be pedantic, just trying to look at this from different angles. It's not always easy for us to decide what the most clear way is to write the docs, so I definitely appreciate your feedback!

What if we'd add a note to the [table](https://spacy.io/usage/rule-based-matching#adding-patterns-attributes), in the row for `POS`, `DEP` etc, that says "Note that the values of this type of attribute are case-sensitive?" We could probably also make the table more explicit and name the "Type" column "Value type" or something such.

**Comment by jabortell** [comment] 2020-11-20 21:26
I'm glad you're being pedantic, you make good points! I do like your idea for putting the note in the table, because it documents all the dictionary-referencing attributes at once, and that's the first location in the documentation that I'd look for clarification on usage. And I do like the more specific "Value Type". Although I'm not sure whether that would benefit many people, I personally enjoy more specific descriptions than less specific.

**Comment by svlandeg** [comment] 2020-11-20 21:27
Great! Do you feel like creating the PR?

**Comment by jabortell** [comment] 2020-11-20 21:31
Sure! This -- spaCy/website/docs/usage/rule-based-matching.md --  is the entry point, correct?

**Comment by svlandeg** [comment] 2020-11-20 21:35
Yep :-)

**Comment by svlandeg** [comment] 2020-11-24 15:23
Fixed by PR #6421 - thanks again for the discussion & PR!

**Closed by svlandeg** 2020-11-24 15:23 UTC
Labels: docs
