### ISSUE TITLE
Token's  property `is_currency` does not work

### ISSUE THREAD

**Issue by TheML9I** [explosion/spaCy#2491] opened 2018-06-29 07:34 UTC
## How to reproduce the behaviour
I have a piece of simple code from public tests

```python
doc = nlp("Net income was $9 million")
assert [t.text for t in doc] == ['Net', 'income', 'was', '$', '9', 'million'] # test passes
assert doc[3].is_currency == True
```

```python
AssertionError                            Traceback (most recent call last)
<ipython-input-70-0b36974f0595> in <module>()
----> 1 assert doc[3].is_currency == True
```

```python
doc[3].is_currency  # False
```

## Your Environment

* Operating System: MacOs High Sierra
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information: miniconda

**Comment by ines** [comment] 2018-06-29 09:09
Thanks for the report – I think I know what the problem is: Since the `is_currency` attribute was added *after* the current models were trained, it's not yet present in the models (wihch cache the lexical attributes in their `lexemes.bin`).

In contrast, the following works as expected:

```python
from spacy.lang.en import English

nlp = English()
doc = nlp("Net income was $9 million")
assert doc[3].is_currency == True
```

This will be fixed with the next model release!

**Comment by TheML9I** [comment] 2018-06-29 14:00
@ines thanks for your comment! 
Looking forward to the next model release.

Indeed, it works for your example.

**Closed** 2018-07-05 15:24 UTC
Labels: bug, enhancement, models
