### ISSUE TITLE
ResourceWarning when calling spacy.load in a unittest

### ISSUE THREAD

**Issue by anyakorneyeva** [explosion/spaCy#7036] opened 2021-02-11 15:30 UTC
## The error:
```
name='C:\\ProgramData\\Anaconda3\\envs\\spacy30-pd\\lib\\site-packages\\en_core_web_sm\\en_core_web_sm-3.0.0\\tok2vec\\model'>
  reader(path / key)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\ProgramData\Anaconda3\envs\spacy30-pd\lib\site-packages\spacy\util.py:1172: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\ProgramData\\Anaconda3\\envs\\spacy30-pd\\lib\\site-packages\\en_core_web_sm\\en_core_web_sm-3.0.0\\tagger\\model'>
  reader(path / key)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

## The code:
```
class TestReaderSpacy(unittest.TestCase):
    """
    Basic tests
    """

    def test_spacy_unclosed_file(self):
        import spacy
        nlp_en_sm = spacy.load("en_core_web_sm")
        spacy_doc = nlp_en_sm("spaCy is the best. But why does it throw a ResourceWarning in unittests?")
        print(spacy_doc.sents)
```

When I run the same code outside of the unittest framework, there is no warning.

Looks related to: https://github.com/explosion/spaCy/issues/1706

## Environment

- **spaCy version:** 3.0.1
- **Platform:** Windows-10-10.0.14393-SP0
- **Python version:** 3.7.6
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0), es_core_news_lg (3.0.0), es_core_news_md (3.0.0), es_core_news_sm (3.0.0), es_dep_news_trf (3.0.0), fr_core_news_lg (3.0.0), fr_core_news_md (3.0.0), fr_core_news_sm (3.0.0), fr_dep_news_trf (3.0.0), zh_core_web_lg (3.0.0), zh_core_web_sm (3.0.0), zh_core_web_trf (3.0.0)

**Comment by polm** [comment] 2021-03-15 10:55
Was able to reproduce this on Linux with Python 3.9.

**Comment by djhenderson** [comment] 2021-05-09 02:05
A mimimal test case is:

```
> py
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load("en_core_web_sm")
C:\Program Files\Python39\lib\site-packages\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
C:\Program Files\Python39\lib\site-packages\spacy\util.py:1176: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python39\\lib\\site-packages\\en_core_web_sm\\en_core_web_sm-3.0.0\\tok2vec\\model'>
  reader(path / key)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Program Files\Python39\lib\site-packages\spacy\util.py:1176: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python39\\lib\\site-packages\\en_core_web_sm\\en_core_web_sm-3.0.0\\tagger\\model'>
  reader(path / key)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Program Files\Python39\lib\site-packages\spacy\util.py:1176: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python39\\lib\\site-packages\\en_core_web_sm\\en_core_web_sm-3.0.0\\senter\\model'>
  reader(path / key)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
>>>
```

This is a first install of spaCy and CuPy and CUDA.
```
> py -m spacy validate
✔ Loaded compatibility table

================= Installed pipeline packages (spaCy v3.0.6) =================
ℹ spaCy installation: C:\Program Files\Python39\lib\site-packages\spacy

NAME              SPACY            VERSION
en_core_web_sm    >=3.0.0,<3.1.0   3.0.0     ✔
en_core_web_trf   >=3.0.0,<3.1.0   3.0.0     ✔
```

**Comment by polm** [comment] 2021-05-09 06:58
I am able to reproduce your output above by setting `PYTHONDEVMODE=1` in my terminal on Linux.

**Comment by phyordia** [comment] 2021-05-24 14:25
I have the same error. 
Python 3.9.2 and Spacy 3.0.6.

**Comment by polm** [comment] 2021-05-31 09:20
Thanks for the reports on this. I managed to track down where this was happening - it wasn't obvious from the stack trace due to some functions being passed around. There were a few places in the code where files were read in like `open(fname).read()` rather than using a context manager, and those have all been revised now, so this shouldn't happen after the next release.

I'm going to go ahead and close this, but if you have issues after the next release feel free to revisit it.

**Closed by polm** 2021-05-31 09:20 UTC
Labels: tests
