### ISSUE TITLE
Assigning vectors to OOV words

### ISSUE THREAD

**Issue by maxmealy** [explosion/spaCy#5170] opened 2020-03-19 17:31 UTC
What is the correct way to modify the vectors for out of vocabulary words, so that the updated vectors are used by NER? I am trying to do it below and it is not working as I would expect. Thanks.

```python
nlp = spacy.load("en_core_web_md")

doc = nlp("He traveled to Paris last week")
doc.ents[0].label_ >>> GPE

doc = nlp("He traveled to Lutetia last week")
doc.ents[0].label_ >>> ORG

nlp.vocab.set_vector("Lutetia", nlp.vocab["Paris"].vector)
doc = nlp("He traveled to Lutetia last week")
doc.ents[0].label_ >>> ORG
```

**Comment by adrianeboyd** [comment] 2020-03-23 15:50
I think the model is using the vector, but the vector isn't the only feature used by the model so it's still predicting `ORG`. The model also uses the word form, prefix (1 character), suffix (3 characters), and shape (`Xxxxx`).

If you have a list of entities, you could use the `EntityRuler` in combination with the `ner` component or if you have example sentences including your entities (and with all other OntoNotes entity types labeled or you'll run into the catastrophic forgetting problem), you could update the model as described here: https://spacy.io/usage/training#ner

**Comment by maxmealy** [comment] 2020-03-24 12:47
Are we sure NER uses the updated vector? Using a longer place name and then shifting all the non-prefix/suffix letters forward one, I get a similar result:
```python
doc = nlp("He traveled to Palestine last week")
doc.ents[0].label_ >>> GPE

doc = nlp("He traveled to Pbmftuine last week")
doc.ents[0].label_ >>> ORG

nlp.vocab.set_vector("Pbmftuine", nlp.vocab["Palestine"].vector)
doc = nlp("He traveled to Pbmftuine last week")
doc.ents[0].label_ >>> ORG
```
I see what you are saying about more training, but if the entity vectors are zero, I'm not sure that will get the same results if there is insufficient context.

**Comment by evalkaz** [comment] 2020-03-30 10:04
Running this on spacy `2.2.3` and `en_core_web_md` version `2.2.5` I get these results:
```python
>>> nlp = spacy.load("en_core_web_md")
>>> doc = nlp("He traveled to Lutetia last week")
>>> doc.ents[0].label_
"GPE"
>>> doc = nlp("He traveled to Pbmftuine last week")
>>> doc.ents[0].label_
"GPE"
>>> nlp.meta["version"] # model version
"2.2.5"
```
Try to update `en_core_web_md` model version.

**Comment by maxmealy** [comment] 2020-03-30 16:36
@evalkaz It looks like 2.2.5 weights are a little different and make a GPE prediction using context, even with an OOV word with a 0 vector. However, the underlying issue here is unchanged: What is the correct way to change a word's vector, so that the new vector is used by the NER model? Here is an example with no context to isolate the issue a little more:
```python
>>> nlp = spacy.load("en_core_web_md")
>>> doc = nlp("Palestine")
>>> len(doc.ents)
1
>>> nlp.vocab.set_vector("Pbmftuine", nlp.vocab["Palestine"].vector)
>>> doc = nlp("Pbmftuine")
>>> len(doc.ents)
0
```

**Comment by adrianeboyd** [comment] 2020-03-31 17:12
@evalkaz Can you try saving the model to disk (`nlp.to_disk("/path/to/model")`) and then reloading it with `spacy.load(/path/to/model)` to see if this makes a difference?

I think I found a spot where `vectors.set_vector()` is missing a step that links the lexeme to the right vector, but reloading should fix this. Because the word itself is also a feature `Pbmftuine` is never going to be identical to `Palestine`, but this would make all the other features identical.

**Comment by evalkaz** [comment] 2020-04-01 11:33
@adrianeboyd yeah, I can reproduce this. After saving and reloading the model `Pbmftuine` is recognized as an entity, without reloading not.

**Comment by adrianeboyd** [comment] 2020-04-01 11:47
Thanks for confirming that! This does look like a bug then.

**Comment by maxmealy** [comment] 2020-04-07 17:30
@adrianeboyd @honnibal I rebuilt spaCy from the latest changes and don't believe #5266 actually resolves the issue here. To restate it again, changing the vectors for a word via nlp.vocab doesn't seem to change the vector that is being fed into the NER model. Saving/Loading from disk seems to fix it.
```
>>> nlp = spacy.load('en_core_web_md')
>>> tok2vec = nlp.get_pipe("ner").model.tok2vec
>>> text = "Pbmftuine"
>>> veca = tok2vec([nlp(text)])
>>> nlp.vocab.set_vector("Pbmftuine", nlp.vocab["Palestine"].vector)
>>> nlp.vocab.set_vector("Pbmftuine".lower(), nlp.vocab["Palestine".lower()].vector)
>>> vecb = tok2vec([nlp(text)])
>>> np.array_equal(veca, vecb)
True
```

**Comment by adrianeboyd** [comment] 2020-04-08 09:55
Hmm, I'm not sure what's going on then. I'll reopen this for now.

**Comment by svlandeg** [comment] 2021-02-18 10:47
This seems to work properly now with spaCy v3:

```
import spacy
nlp = spacy.load("en_core_web_md")
doc = nlp("Palestine")
print(len(doc.ents))

doc = nlp("Pbmftuine")
print(len(doc.ents))

nlp.vocab.set_vector("Pbmftuine", nlp.vocab["Palestine"].vector)
doc = nlp("Pbmftuine")
print(len(doc.ents))
```
gives me:
```
1
0
1
```
So I'll tentatively close this :-)

**Closed by svlandeg** 2021-02-18 10:47 UTC
Labels: bug, feat / ner, feat / vectors, usage
