### ISSUE TITLE
Getting scores as probabilities or confidence from the output of the Spacy TextCategorizer

### ISSUE THREAD

**Issue by haroonhassan** [explosion/spaCy#3995] opened 2019-07-20 13:29 UTC
## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by svlandeg** [comment] 2019-07-22 09:31
duplicate of https://github.com/explosion/spaCy/issues/3995

**Closed by svlandeg** 2019-07-22 09:31 UTC
