### ISSUE TITLE
Not able to pickle the nlp.load("en_core_web_lg")

### ISSUE THREAD

**Issue by vaibhavpancholi** [explosion/spaCy#2481] opened 2018-06-26 12:34 UTC
i am using latest version of spacy .I am using rest api. I am thinking if i can pickle language object it will give faster response.As we are facing timeout issues due to load of large model.

Is there any work around for the issue.

filehandler = open(path,"wb")
pickle.dump(nlp,filehandler)

it gives me error 
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'

i am stuck with this.

Please help

**Comment by ines** [comment] 2018-06-26 15:52
Could you check which version of spaCy you're running? (e.g. via `python -m spacy info`)

Your issue sounds like the same problem as #2121, which was caused by a previous version of Thinc. So if you're not on the latest spaCy, upgrade to `v2.0.11` and try again?

**Comment by vaibhavpancholi** [comment] 2018-06-27 06:52
even after updating the spacy to 2.0.11 while pickling i am getting same error.

below is the error.

    Info about spaCy

    spaCy version      2.0.11           
    Platform           Linux-4.13.0-1019-gcp-x86_64-with-debian-stretch-sid
    Python version     3.6.1          
    Models             en_core_web_md, en_core_web_lg, en

(py361) root@smart-learning:/home/ubuntu/smart-learningv2.0# python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load("en_core_web_lg)
  File "<stdin>", line 1
    spacy.load("en_core_web_lg)
                              ^
SyntaxError: EOL while scanning string literal
>>> nlp=spacy.load("en_core_web_lg")
>>> import pickle
>>> pickle.dump(nlp, open("/home/ubuntu/smart-learningv2.0", 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/smart-learningv2.0'
>>> pickle.dump(nlp, open("/home/ubuntu/smart-learningv2.0/nlp.pkl", 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'

**Comment by honnibal** [comment] 2018-12-06 23:45
Should now be fixed in the next spacy-nightly.

**Closed by honnibal** 2018-12-06 23:45 UTC
Labels: feat / serialize, models
