### ISSUE TITLE
NER training with new entity array shape error

### ISSUE THREAD

**Issue by nyejon** [explosion/spaCy#3189] opened 2019-01-23 15:30 UTC
## How to reproduce the behaviour
Run the standard new entity training example on https://spacy.io/usage/training#section-ner

## Info about spaCy

* **spaCy version:** 2.1.0a6
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.1

I get a "ValueError: could not broadcast input array from shape (77,64) into shape (73,64)"

I have tried both the english md and lg models iwth the same results

**Comment by ines** [comment] 2019-01-23 15:39
Could you check the output of `python -m spacy validate` to make sure you're using the correct compatible models (especially since you're on `spacy-nightly`)?

**Comment by nyejon** [comment] 2019-01-23 15:40
===================== Installed models (spaCy v2.1.0a6) =====================
ℹ spaCy installation:
/Users/jonathannye/.local/share/virtualenvs/offer-machine-learning-mJ7mbo3c/lib/python3.7/site-packages/spacy

TYPE      NAME              MODEL             VERSION
package   en-core-web-md    en_core_web_md    2.1.0a5   ✔
package   en-core-web-lg    en_core_web_lg    2.1.0a5   ✔
package   de-core-news-md   de_core_news_md   2.1.0a5   ✔

**Comment by nyejon** [comment] 2019-02-18 14:11
Hi, to extend this issue - If I change the ner config after training I get:

{
  "beam_width":1,
  "beam_density":0.0,
  "cnn_maxout_pieces":3,
  "deprecation_fixes":{
    "vectors_name":"en_model.vectors"
  },
  "nr_class":89,  <----- This was incorrectly written out as 73
  "hidden_depth":1,
  "token_vector_width":96,
  "hidden_width":64,
  "maxout_pieces":2,
  "pretrained_vectors":"en_model.vectors",
  "bilstm_depth":0
}

If I change the value of NR class to 89 as the new model expects it loads but everything is labelled as a NORP

**Comment by ines** [comment] 2019-02-18 15:30
@nyejon Are you using the latest nightly, `2.1.0a7`? We definitely fixed a bug that might have caused problems like "everything is labelled XY", so if you're still using a6, try again with the new nightly and see if the problem is resolved.

**Comment by nyejon** [comment] 2019-02-18 18:17
Yes I am. This was tested again because I had upgraded to see if it works now

**Comment by honnibal** [comment] 2019-02-24 15:44
Found the bug, and fixed a number of other issues associated with adding labels to a pre-trained model. It's definitely a hard workflow to support correctly, but we're really committed to making it work, as it's super valuable.

**Closed** 2019-02-24 15:49 UTC
Labels: feat / ner, training, 🌙 nightly
