### ISSUE TITLE
Show doc['id'] or at least some other infos for errors when training with CLI

### ISSUE THREAD

**Issue by Arakkun** [explosion/spaCy#3698] opened 2019-05-07 20:32 UTC
I'm training a model, and obtain the 
"ValueError: [E069] Invalid gold-standard parse tree. Found cycle between word IDs:  ..." 
Knowing which doc is causing the error or which phrase, or at least a bit more infos about the error would be really useful. Especially as the JSON input format for training has already an 'id' field meaning "# ID of the document within the corpus"

**Comment by sairampillai** [comment] 2019-05-20 06:51
@ines If no one is working on it, I would like to work on this issue

**Comment by ines** [comment] 2019-05-20 10:58
@sairampillai Thanks! And yes, feel free to go ahead and prepare the PR! 😃

**Comment by rbhambriiit** [comment] 2019-06-28 08:47
Hitting this on v2.0.18
is someone working on this?

**Comment by rbhambriiit** [comment] 2019-06-28 09:09
can't we just skip cases with bad training data somehow? @ines

**Comment by ines** [comment] 2019-06-29 09:38
The error is raised here:

https://github.com/explosion/spaCy/blob/26c37c5a4dc8acf113e9b74f3162ed2a3bc74aea/spacy/gold.pyx#L568-L569

So in the meantime, you can always build spaCy from source and hack in a print statement here if you need it 🙂

**Comment by rbhambriiit** [comment] 2019-07-01 15:25
Thanks. I tried to build from source as you mentioned by following: https://spacy.io/usage#source

I hit "RuntimeError: Python version >= 3.5 required." - perhaps documentation needs to be updated with this for venv to require certain python version

Now i am running python3.6 and spacy v2.1.4
(the original version was v2.0.18 - where i hit the cycle issue and reached here.)

I did another run to reproduce the issue in this new spacy build - hitting a different scenario now

"""
(.env36) -bash-4.2$ python -m spacy train -n 5 en models_expt1 train_expt1_july1.json valid_expt1_july1.json
Training pipeline: ['tagger', 'parser', 'ner']
Starting with blank model 'en'
Counting training words (limit=0)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/app/data/rahul/playground/spacy_2.1/spaCy/.env36/lib64/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/.env36/lib64/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/spacy/cli/train.py", line 205, in train
    corpus = GoldCorpus(train_path, dev_path, limit=n_examples)
  File "gold.pyx", line 112, in spacy.gold.GoldCorpus.__init__
  File "gold.pyx", line 123, in spacy.gold.GoldCorpus.write_msgpack
  File "gold.pyx", line 163, in read_tuples
  File "gold.pyx", line 321, in read_json_file
  File "gold.pyx", line 368, in _json_iterate
OverflowError: value too large to convert to int
(.env36) -bash-4.2$
(.env36) -bash-4.2$
"""




.

**Comment by rbhambriiit** [comment] 2019-07-01 15:58
I have made some changes in the gold.pyx file and wish to see those additional prints.

While compiling from source , i see this:

```

(.env36) -bash-4.2$ python setup.py build_ext --inplace
Cythonizing sources
Processing gold.pyx
Processing gold-checkpoint.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
^
------------------------------------------------------------

gold-checkpoint.pyx:1:0: 'gold-checkpoint' is not a valid module name
Traceback (most recent call last):
  File "/app/data/rahul/playground/spacy_2.1/spaCy/bin/cythonize.py", line 169, in <module>
    run(args.root)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/bin/cythonize.py", line 158, in run
    process(base, filename, db)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/bin/cythonize.py", line 124, in process
    preserve_cwd(base, process_pyx, root + ".pyx", root + ".cpp")
  File "/app/data/rahul/playground/spacy_2.1/spaCy/bin/cythonize.py", line 87, in preserve_cwd
    func(*args)
  File "/app/data/rahul/playground/spacy_2.1/spaCy/bin/cythonize.py", line 63, in process_pyx
    raise Exception("Cython failed")
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 275, in <module>
    setup_package()
  File "setup.py", line 209, in setup_package
    generate_cython(root, "spacy")
  File "setup.py", line 132, in generate_cython
    raise RuntimeError("Running cythonize failed")
RuntimeError: Running cythonize failed
(.env36) -bash-4.2$


```
Will you be able to help?

**Comment by honnibal** [comment] 2019-07-10 07:44
It's helpful if you avoid @ -ing maintainers, as it makes our mentions hard to use. Thanks :).

The error message in your traceback is correct:

> gold-checkpoint.pyx:1:0: 'gold-checkpoint' is not a valid module name

Your problem is that you have a module named `gold-checkpoint.pyx`, and that's not a valid module name. So you need to remove that to compile the rest of the source.

**Comment by sairampillai** [comment] 2019-07-10 07:57
I'm still working on it and I would like to discuss the changes and approach we should take with this. I see no simple way to display the 'id' of the doc and it requires a lot of cascading changes. Let me get back with a pull request later with appropriate code changes.

**Comment by adrianeboyd** [comment] 2019-08-15 07:59
This is related to #4017.

Keeping track of the document ID / paragraph number would require quite a few changes in GoldCorpus/GoldParse, but a quick solution to help people pin down where the errors are, it would be easy to print the tokens affected and the tokens in the document.

See #4123.

**Comment by svlandeg** [comment] 2020-01-02 22:34
As discussed in PR #4844, it would probably make sense to try and keep the `doc_id` as an optional field in the new `Example` class currently living in the `develop` branch. Work in progress by @sfragis :-)

**Comment by mukul-mehta** [comment] 2020-05-18 13:04
I'd like to work on this issue as well! Is it still open, has further progress been made? If not, I'd love to start working on it.

**Comment by polm** [comment] 2021-05-29 09:32
As a note, the error initially at issue here, E069, no longer exists. There still isn't a generic Doc ID, so it's hard to make a generic solution for this, though many errors now include the span at issue.

**Comment by polm** [comment] 2022-01-17 10:44
Given the initial error here no longer exists and we've made several improvements on this front since the issue was opened, I'm going to close this, but if anyone has specific suggestions about improving debugging for training feel free to open a feature proposal in Discussions.

**Closed by polm** 2022-01-17 10:44 UTC
Labels: enhancement, help wanted, help wanted (easy), feat / cli
