### ISSUE TITLE
RuntimeError compiling spaCy -- cannot assign double to int    [BUG]

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [explosion/spaCy#1610] opened 2017-11-19 14:32 UTC
* Operating System: Ubuntu 16.04
* Python Version Used: 3.4.5 Continuum Analytics [GCC 4.4.7]
* spaCy Version Used: 2.0.x  ??   (the current version that a git clone gets me)
* Environment Information: conda environment, spaCy not present.
`Cython                    0.26.1                    <pip>`

I was trying to compile spacy within an Conda environment, when a (seemingly) simple-to-fix bug was found (see the terminal output below).
There is a double being assigned to an int in the file: `_beam_utils.pyx` at line 93.
It is coming from `beam._state`. Looking through the file `search.pyx` (from `site-packages/thinc/extra`) from which `Beam` is imported, I cannot follow exactly which type it is declared as, although many defs use `int` and the `_beam_utils.pyx` file does include the cython header:`infer_types=True`.

If this is indeed a mistake, then lines 94 and 95 look like they must also be changed.

### Here are some relevant terminal outputs. First the installation of the spacy requirements:
```
pip install -r requirements.txt
Collecting cython<0.27.0,>=0.24 (from -r requirements.txt (line 1))
  Downloading Cython-0.26.1-cp34-cp34m-manylinux1_x86_64.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 384kB/s 
Requirement already satisfied: pathlib in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: numpy>=1.7 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: cymem<1.32,>=1.30 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: thinc<6.11.0,>=6.10.1 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: murmurhash<0.29,>=0.28 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: plac<1.0.0,>=0.9.6 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: six in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: ujson>=1.35 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: dill<0.3,>=0.2 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: regex==2017.4.5 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: ftfy<5.0.0,>=4.4.2 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 14))
Collecting pytest<4.0.0,>=3.0.6 (from -r requirements.txt (line 15))
  Downloading pytest-3.2.5-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 5.1MB/s 
Collecting mock<3.0.0,>=2.0.0 (from -r requirements.txt (line 16))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: msgpack-python in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: msgpack-numpy in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from -r requirements.txt (line 18))
Collecting html5lib==1.0b8 (from -r requirements.txt (line 19))
  Using cached html5lib-1.0b8.tar.gz
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from thinc<6.11.0,>=6.10.1->-r requirements.txt (line 6))
Requirement already satisfied: termcolor in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from thinc<6.11.0,>=6.10.1->-r requirements.txt (line 6))
Requirement already satisfied: cytoolz<0.9,>=0.8 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from thinc<6.11.0,>=6.10.1->-r requirements.txt (line 6))
Requirement already satisfied: wrapt in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from thinc<6.11.0,>=6.10.1->-r requirements.txt (line 6))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from requests<3.0.0,>=2.13.0->-r requirements.txt (line 12))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from requests<3.0.0,>=2.13.0->-r requirements.txt (line 12))
Requirement already satisfied: certifi>=2017.4.17 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from requests<3.0.0,>=2.13.0->-r requirements.txt (line 12))
Requirement already satisfied: idna<2.7,>=2.5 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from requests<3.0.0,>=2.13.0->-r requirements.txt (line 12))
Requirement already satisfied: wcwidth in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from ftfy<5.0.0,>=4.4.2->-r requirements.txt (line 14))
Collecting py>=1.4.33 (from pytest<4.0.0,>=3.0.6->-r requirements.txt (line 15))
  Downloading py-1.5.2-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 3.8MB/s 
Requirement already satisfied: setuptools in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from pytest<4.0.0,>=3.0.6->-r requirements.txt (line 15))
Collecting pbr>=0.11 (from mock<3.0.0,>=2.0.0->-r requirements.txt (line 16))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Requirement already satisfied: toolz>=0.8.0 in /home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->-r requirements.txt (line 6))
Building wheels for collected packages: html5lib
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: /home/n1k31t4/.cache/pip/wheels/d4/d1/0b/a6b6f9f204af55c9bb8c97eae2a78b690b7150a7b850bb9403
Successfully built html5lib
Installing collected packages: cython, py, pytest, pbr, mock, html5lib
  Found existing installation: html5lib 0.999999999
    Uninstalling html5lib-0.999999999:
      Successfully uninstalled html5lib-0.999999999
Successfully installed cython-0.26.1 html5lib-1.0b8 mock-2.0.0 pbr-3.1.1 py-1.5.2 pytest-3.2.5

```

### Here for the build command, including the error:
```
paCy$ python setup.py build_ext --inplace
Cythonizing sources
Processing attrs.pyx
Processing gold.pyx
Processing lexeme.pyx
Processing matcher.pyx
Processing morphology.pyx
Processing parts_of_speech.pyx
Processing pipeline.pyx
Processing strings.pyx
Processing symbols.pyx
Processing tokenizer.pyx
Processing typedefs.pyx
Processing vectors.pyx
Processing vocab.pyx
Processing _beam_utils.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                for j in range(beam.size):
                    state = StateClass.borrow(<StateC*>beam.at(j))
                    if state.is_final():
                        try:
                            if self.moves.is_gold_parse(state, self.golds[i]):
 #line 93                  beam._states[j].loss = 0.0
                                                      ^
------------------------------------------------------------

_beam_utils.pyx:93:55: Cannot assign type 'double' to 'int'
Traceback (most recent call last):
  File "/home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages/spaCy/bin/cythonize.py", line 157, in <module>
    run(args.root)
  File "/home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages/spaCy/bin/cythonize.py", line 148, in run
    process(base, filename, db)
  File "/home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages/spaCy/bin/cythonize.py", line 114, in process
    preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
  File "/home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages/spaCy/bin/cythonize.py", line 79, in preserve_cwd
    func(*args)
  File "/home/n1k31t4/anaconda3/envs/env-name/lib/python3.4/site-packages/spaCy/bin/cythonize.py", line 61, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 227, in <module>
    setup_package()
  File "setup.py", line 172, in setup_package
    generate_cython(root, 'spacy')
  File "setup.py", line 104, in generate_cython
    raise RuntimeError('Running cythonize failed')
RuntimeError: Running cythonize failed
```

**Comment by bdewilde** [comment] 2017-11-20 18:09
Not sure if this is related, but: I forked `spacy` then followed the instructions [here](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#getting-started) to compile from source. Worked fine. After fixing a bug in `span.pyx`, however, I tried to re-compile via `python setup.py build_ext --inplace` and hit a similar exception:

```
spaCy(fix-span-orth)$ python setup.py build_ext --inplace
Cythonizing sources
Processing span.pyx
Traceback (most recent call last):
  File "/Users/burtondewilde/.pyenv/versions/spacy2-bugfix/bin/cython", line 7, in <module>
    from Cython.Compiler.Main import setuptools_main
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 21, in <module>
    from . import Errors
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/Cython/Compiler/Errors.py", line 14, in <module>
    from ..Utils import open_new_file
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/Cython/Utils.py", line 18, in <module>
    import shutil
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/shutil.py", line 16, in <module>
    import bz2
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "__init__.pxd", line 155, in init spacy.tokens.token
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/envs/spacy2-bugfix/lib/python3.6/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/unittest/__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/unittest/case.py", line 6, in <module>
    import logging
  File "/Users/burtondewilde/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 209, in <module>
    _lock = threading.RLock()
AttributeError: module 'threading' has no attribute 'RLock'
Traceback (most recent call last):
  File "/Users/burtondewilde/Desktop/github/spaCy/bin/cythonize.py", line 157, in <module>
    run(args.root)
  File "/Users/burtondewilde/Desktop/github/spaCy/bin/cythonize.py", line 148, in run
    process(base, filename, db)
  File "/Users/burtondewilde/Desktop/github/spaCy/bin/cythonize.py", line 114, in process
    preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
  File "/Users/burtondewilde/Desktop/github/spaCy/bin/cythonize.py", line 79, in preserve_cwd
    func(*args)
  File "/Users/burtondewilde/Desktop/github/spaCy/bin/cythonize.py", line 61, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 227, in <module>
    setup_package()
  File "setup.py", line 172, in setup_package
    generate_cython(root, 'spacy')
  File "setup.py", line 104, in generate_cython
    raise RuntimeError('Running cythonize failed')
RuntimeError: Running cythonize failed
```

**Comment by honnibal** [comment] 2018-01-15 15:42
Hmm. The `loss` variable there is defined as a float32 within `thinc/extra/search.pxd`, so I'm not sure what's going on here. Possibly a different version of `thinc` was being drawn in for the header?

I don't love closing issues I couldn't reproduce, but I'm not sure there's anything to action here. Please reopen if problems persist.

**Closed by honnibal** 2018-01-15 15:42 UTC
Labels: bug
