### ISSUE TITLE
Can't add tokenizer exception

### ISSUE THREAD

**Issue by anastan96** [explosion/spaCy#3876] opened 2019-06-24 09:33 UTC
I am trying to add an exception at tokenizing some tokens. For a token like "7-year-old" spacy splits it into "7-year" and "old". 

I was trying to use from spacy.lang.en.tokenizer_exceptions import TOKENIZER_EXCEPTIONS and also  spacy.util which have a method update_exc(), but nothing changes. This is part of the code:

```
_exc = {}
 for a in range(0,100):
     for exp in ["-year-old", " years old"]:
         _exc["%d%s" % (a, exp)] = [
                 {ORTH: "%d" % a},
                 {ORTH: exp, LEMMA: "-year-old"}]
 TOKENIZER_EXCEPTIONS = _exc 
 BASE_EXCEPTIONS = {}
 update_exc(BASE_EXCEPTIONS, TOKENIZER_EXCEPTIONS)
```
I also find it a bit weird that the code analysis says `'spacy.lang.de.tokenizer_exceptions import TOKENIZER_EXCEPTIONS'` imported but not used and for this line, `TOKENIZER_EXCEPTIONS = _exc`, it says redefinition of unused `'TOKENIZER_EXCEPTIONS'`

* Operating System: Windows 10
* Python Version Used: 3.7.3 
* spaCy Version Used: 2.1.4

**Comment by BreakBB** [comment] 2019-06-24 11:12
I can only explain some parts of your question since I can reproduce your problem and don't know either how to get this right.

> I also find it a bit weird that the code analysis says 'spacy.lang.de.tokenizer_exceptions import TOKENIZER_EXCEPTIONS' imported but not used and for this line, TOKENIZER_EXCEPTIONS = _exc, it says redefinition of unused 'TOKENIZER_EXCEPTIONS'

This makes totally sense, since you import the variable `TOKENIZER_EXCEPTIONS` with it's inital values and simply overwrite them with `TOKENIZER_EXCEPTIONS = _exc`, before you ever use the variable.

> I was trying to use from spacy.lang.en.tokenizer_exceptions import TOKENIZER_EXCEPTIONS and also spacy.util which have a method update_exc(), but nothing changes.

`update_exc` simply combines the two expection dictionaries you hand into it, but does not add them to any `tokenizer`. As far as I can see it you have to add them to the language `Defaults`.

[The docs](https://spacy.io/usage/adding-languages#tokenizer-exceptions) say:

> When adding the tokenizer exceptions to the Defaults, you can use the update_exc helper function to merge them with the global base exceptions (including one-letter abbreviations and emoticons).

But for me the example code and your exceptions both doesn't work so there might be more to it.

**Comment by anastan96** [comment] 2019-06-24 13:35
>  This makes totally sense, since you import the variable TOKENIZER_EXCEPTIONS with it's inital values and simply overwrite them with TOKENIZER_EXCEPTIONS = _exc, before you ever use the variable.

I understand, but I just followed the example found in the spacy documentation: https://spacy.io/usage/adding-languages#tokenizer-exceptions
I also tried to change the name of the variable, but it doesn't change anything.
 
I'm new to NLP so I wasn't sure if this would work. 

Regarding to adding the exceptions to the tokenizer I found out that in order to make it work I need to give the Tokenizer all args:
```
custom_tokenizer = Tokenizer(vocab=nlp.vocab, rules=tokenizer_exceptions,
                             prefix_search=prefix_search,
                             suffix_search=suffixes_search,
                             infix_finditer=infix_re.finditer)
```

**Comment by BreakBB** [comment] 2019-06-25 06:20
> I understand, but I just followed the example found in the spacy documentation: https://spacy.io/usage/adding-languages#tokenizer-exceptions
I also tried to change the name of the variable, but it doesn't change anything.

This part of the docs are ment to be included in a [language subclass](https://spacy.io/usage/adding-languages#language-subclass), so the code is for a different context as you use it, as far as I can tell. Moreover there is no hint at [tokenizer exceptions](https://spacy.io/usage/adding-languages#tokenizer-exceptions) to include `spacy.lang.de.tokenizer_exceptions import TOKENIZER_EXCEPTIONS`. In the lanuage subclass section `TOKENIZER_EXCEPTIONS` is created as variable to be imported at some other point. However I totally understand your confusion and maybe the docs should be updated to hint for the usage of such exceptions.

> Regarding to adding the exceptions to the tokenizer I found out that in order to make it work I need to give the Tokenizer all args:

I am not sure if I understand you correctly, since your code is incomplete. Where are you taking the values for the other params from and does your tokenizer now work as expected?

**Comment by anastan96** [comment] 2019-06-25 09:15
Thanks for your explanation, I understand now.

> I am not sure if I understand you correctly, since your code is incomplete. Where are you taking the values for the other params from and does your tokenizer now work as expected?

I took it from the beginning, and I customised the tokenizer. I took care of the hyphens like this: 
```
nlp = spacy.load("en_core_web_sm")
nlp.tokenizer = self.create_custom_tokenizer(nlp)
doc = nlp(text)

def create_custom_tokenizer(self, nlp):
   infixes = nlp.Defaults.prefixes + (r"[./]", r"[-]~", r"(.'.)")
   infix_re = spacy.util.compile_infix_regex(infixes)
   return Tokenizer(nlp.vocab, infix_finditer=infix_re.finditer)
```

**Comment by BreakBB** [comment] 2019-06-25 10:26
Looks like your tokenizer is working now 🎉 If your issue is resolved, you should close it. If not feel free to ask or make clear what's missing for you.

**Closed** 2019-06-25 12:48 UTC
Labels: feat / tokenizer, usage
