### ISSUE TITLE
We want to enable Korean support for spaCy.

### ISSUE THREAD

**Issue by tylee33** [explosion/spaCy#929] opened 2017-03-27 06:09 UTC
## Your Environment

* Operating System: Ubunt16.04 or CentOS 7
* Python Version Used: 2.7 or 3.6
* spaCy Version Used: 1.7.3
* Environment Information: None

Thank you for your contribution to the spaCy.
However, when we try to add a Korean language model, we have a lot of trial and error 
because of lack of manuals.

So we want to provide us with the necessary guides to add language models.
There are a lot of problems applying the language explanation provided by spaCy.io.
For example: python training/init.py xx your_data_directory/my_data/word_freqs.txt my_data/clusters.txt my_data/word_vectors.bz2
I want to know the specific method of creating the file (word_freqs.txt and word_vectors.bz2, It is not English.default_vocab function not exist in word_freqs.py) and the internal structure of the file that are actually needed when executing the command.

I look forward to your kind reply.

**Comment by oroszgy** [comment] 2017-03-27 10:04
Hi, this is still WIP, but you can take a look at here (planning to do a PR soon):
https://github.com/oroszgy/spacy-dev-resources/tree/corpus_processing/wikimodel

It is supposed to create a vocabulary wtih word vectors and brown clusters from Wikipedia.

**Comment by tylee33** [comment] 2017-03-28 08:54
Dear oroszgy

Thank you for your kind reply.
I am wondering if the spaCy is an internal schedule for support of Korean language packs.

I wait for your reply.

**Comment by jaric** [comment] 2017-03-28 10:04
hi @oroszgy,

https://github.com/oroszgy/spacy-dev-resources/tree/corpus_processing/wikimodel is a 404 link?

**Comment by oroszgy** [comment] 2017-03-28 10:16
@jaric Just made some code cleanup, renamed the directory. Look around in the repo: https://github.com/oroszgy/spacy-dev-resources/tree/corpus_processing/

**Comment by tylee33** [comment] 2017-03-31 08:39
We proceeded to follow the guide you gave and achieved a great deal of accomplishment.

**Comment by oroszgy** [comment] 2017-03-31 09:20
@tylee33 The problem is that you first need to create a tokenizer in spacy, and only after then you can build the vocabulary.

**Comment by ines** [comment] 2017-03-31 12:28
@tylee33 Have you looked at the [adding a language](https://spacy.io/docs/usage/adding-languages#tokenizer-exceptions) documentation yet? Here are the main steps:
1. Create a `Language` subclass and implement it.
2. Define custom language data, like a stop list, tag map and tokenizer exceptions.
3. Build the vocabulary including word frequencies, Brown clusters and word vectors.

After you've completed steps 1 and 2, you'll be able to use the tokenizer in spaCy:

```python
from spacy.ko import Korean
nlp = Korean()
doc = nlp(u'안녕하세요')
```

You can then go ahead and build the vocabulary and train your own model. `data/ko/vocab/strings.json` will be part of the model data. See the [documentation on using your own models](https://spacy.io/docs/usage/models#own-models) for more info on how to package and load models.

Good luck and keep us updated!

P.S.: Feel free to join our [Gitter chat](https://gitter.im/explosion/spaCy) – there's a lot of discussion going on about training models for spaCy, and it's a good place to get fast help with questions specific to your model.

**Comment by tylee33** [comment] 2017-04-11 02:28
Please check that Hangul is selected in http://en.glyphwiki.org/wiki/Group:Hangul-GB12052 format.

**Comment by tylee33** [comment] 2017-04-12 01:32
I want to know how to construct the model internally.
The following commands do not show the sub-elements that make up the model.
Please give me a guide to construct the model.

python setup.py sdist
pip install ko_model_name-0.0.0.tar.gz

**Comment by tylee33** [comment] 2017-04-12 02:17
I think the installation is working properly, but the ko does not appear in the folder below, and the detailed components can not be confirmed.

root@ip-10-50-1-150:/usr/local/lib/python2.7/dist-packages/spacy/data# ls
en  __init__.py  __init__.pyc

**Comment by ines** [comment] 2017-04-13 10:59
@tylee33 Yes, it looks like packaging and installing has all worked correctly! 👍

If you install a model via pip, it will be placed in your `site-packages`, so you should be able to import it like a regular module, and then call its `load()` method:

```python
import ko_model_name
nlp = ko_model_name.load()
doc = nlp(u'안녕하세요')
```

If you want to be able to load the model via `spacy.load()`, you'll have to create a [shortcut link](https://spacy.io/docs/usage/cli#link) for it. This will create a symlink in `spacy/data` and lets you load the model as `spacy.load('ko')`.

```bash
# make model package 'ko_model_name' available as 'ko' shortcut
python -m spacy link ko_model_name ko
```

**Comment by ines** [comment] 2017-04-16 21:52
Closing this issue since it looks like it all worked.

Btw, we also just updated our docs and added a workflow on saving and loading models:
https://spacy.io/docs/usage/saving-loading The process of initialising, training, packaging and loading your own models should also work more smoothly now in v1.8.0.

**Closed by ines** 2017-04-16 21:52 UTC
Labels: docs, enhancement
