### ISSUE TITLE
Improving tokenization for languages that use period as an ordinal indicator

### ISSUE THREAD

**Issue by spyysalo** [explosion/spaCy#5044] opened 2020-02-21 09:43 UTC
## Feature description

Many languages (e.g. [German, Danish and Finnish](https://en.wikipedia.org/wiki/Ordinal_indicator#Representation_as_period)) use a period as an ordinal indicator. For these languages, expressions such as *17. Dezember* should preferably be tokenized so that the period is part of the ordinal.

These periods appear to be systematically separated by spaCy tokenization at least for German and Finnish:

```
>>> from spacy.lang.de import German
>>> [t.text for t in German()('Am 17. Dezember')]
['Am', '17', '.', 'Dezember']
>>> from spacy.lang.fi import Finnish
>>> [t.text for t in Finnish()('Vasta 1. tammikuuta')]
['Vasta', '1', '.', 'tammikuuta']
```

The ordinal is preserved as a single token at least for Danish, although the solution (https://github.com/explosion/spaCy/blob/master/spacy/lang/da/tokenizer_exceptions.py#L563) also introduces some errors:

```
>>> from spacy.lang.da import Danish
>>> [t.text for t in Danish()('Inden 3. maj')]
['Inden', '3.', 'maj']
>>> [t.text for t in Danish()('Mandag den 3. august kl. 12.')]
['Mandag', 'den', '3.', 'august', 'kl.', '12.']
```

Based on a brief discussion with @svlandeg , https://spacy.io/usage/linguistic-features#retokenization might offer a more consistent and principled solution.

**Comment by svlandeg** [comment] 2020-02-21 09:49
I'm not sure how we could properly fix this in the current setup. The Danish rule seems to be risky to include false positives like non-ordinal numbers at the end of a sentence. I'm not even sure we should have it there. But then if we don't, the parser will get these ordinal tokens split, and will suffer performance from it...

**Comment by spyysalo** [comment] 2020-02-21 09:57
Would it be difficult to reattach sentence-internal periods following digits after sentence splitting for relevant languages? (I understand this would be too late to help parsing, though.)
This should be reasonably easy to machine-learn (e.g. UD-based ML tokenizers don't seem to have much of an issue with these), but I take it ML-based tokenization isn't likely to happen soon.

**Comment by adrianeboyd** [comment] 2020-02-21 11:20
Aside from the speed, if we don't have rule-based tokenization, some of spacy's components get very difficult to use, like the `Matcher`. If I want to match `31.` and it's `['31', '.']` in some contexts and `['31.']` in others, it's going to be very frustrating. If the `PhraseMatcher` has to generate all possible tokenizations of a provided phrase (and all their attributes) in advance in order to search for matches, I think it's going to get way too complicated. (How would you even generate all the possibilities?)

I'm currently trying to update many of the tokenizers for languages that use UD training data and it's easy to see that there are lots of complicated cases (also plenty of inconsistencies in the data) and it's clear that the evaluation is going to suffer to some extent from the constraints of the rule-based tokenizer. Obviously it would be better if the tokenization lined up better with the training data, but I really don't see a good solution.

There's also no good way (yet) to have a `parser` require a previous component (beyond tokenization, which you're not allowed to omit) like a `date_retokenizer`. If you want, you could develop your own custom retokenizer and be careful to always include it in your pipeline before your parser model that's been trained on the corresponding gold tokenization.

Actually, there is also one more possibility, but it's still under development. The parser has a `--learn-tokens` option (originally intended for Chinese) that will learn how to merge tokens like `['31', '.']` together when they are one token in the training data. That might be a possibility for people interested in parser output, but it would still cause problems for the `Matcher`.

**Comment by svlandeg** [comment] 2020-02-21 13:57
I see your point with respect to the `Matcher`, @adrianeboyd, and that it might get confusing to users creating custom matching rules. But then again wouldn't it be useful if you could match specifically on "31." as one token, assuming that would then be an ordinal? I'm trying to think of use-cases where you'd want to match "31." both as an ordinal and as a number at the end of the sentence?

> Actually, there is also one more possibility, but it's still under development. The parser has a `--learn-tokens` option (originally intended for Chinese) that will learn how to merge tokens like `['31', '.']` together when they are one token in the training data. 

Ah, interesting, I wasn't aware of that!

**Comment by spyysalo** [comment] 2020-02-21 15:03
`--learn-tokens` sounds like the ideal solution! Would it be possible to deploy ML-based (re)tokenization also for languages other than Chinese?

(I'm not familiar with `Matcher`, but generally speaking I agree with @svlandeg that it would mostly be beneficial if it were possible to search for ordinals (as opposed to sentence-final cardinals) by matching e.g. "12." in Finnish (or German, Danish, etc.) text, where *12.* is equally distinct from *12* as *12th* is in English.)

**Comment by adrianeboyd** [comment] 2020-02-24 07:56
I suppose for the `Matcher` that matching on statistical tokenization isn't that much different from matching on statistical POS tags (although it is a whole additional layer for things to go wrong in in unexpected ways for users), but I think it's going to be very hard for the `PhraseMatcher` to work well.

I looked at the German tokenizer (which we use with training data from Tiger), and making `NN.` the default rather than `NN .` does drastically improve the overall tokenization accuracy, so it makes sense to change this. There's nothing "sacred" about the tokenizer settings for a particular language in spacy, since you usually need to make modifications for each training corpus. The tokenizer settings are saved within the model, so you can easily distribute models for the same language with different tokenizers that you customized locally while training.

Does Danish only do dates with `NN.` and not other ordinals like `65.`? The UD Danish-DDT corpus seems to hallucinate extra periods for abbreviations at the ends of sentences, which is also fun:

```
# text = Stakken blev tæt på 2 meter høj og vejede 43,5 kg..
```

(I'm assuming this is an artifact from the older treebank the data comes from, and I don't see any cases with ordinals in this position.)

I'm not sure that the `--learn-tokens` option is working as intended yet because I had trouble with Chinese, but it might be a good idea to make sure it works with this kind of case before trying to debug the Chinese case. It should 1) add a `subtoken` dependency between `31` and `.` when the gold parse has the token `31.`, 2) learn to predict `subtoken` dependencies alongside all the other labels, and 3) merge any tokens with `subtoken` dependencies right after parsing.

If you took this approach, it would be better for the tagger to be trained on the automatically retokenized parser output and for the tagger to require the parser in the pipeline before it, but that's also not easy currently.

**Comment by pbouda** [comment] 2020-03-10 15:02
@adrianeboyd Interesting, how can I change this to make `NN.` the default?

**Comment by adrianeboyd** [comment] 2020-03-23 18:27
@pbouda You remove `0-9` from this regex that splits off period as a suffix:

https://github.com/explosion/spaCy/blob/80e7e1347eb59b739503184fa4d69814f6f07954/spacy/lang/punctuation.py#L30-L31

See the recent modifications for German here:

https://github.com/explosion/spaCy/blob/80e7e1347eb59b739503184fa4d69814f6f07954/spacy/lang/de/punctuation.py

(With the caveat that I really shouldn't have done the imports like that, see #5185.)

**Comment by svlandeg** [comment] 2020-08-25 11:04
I'll tentavily close this issue as it looks like there are some workarounds possible (cf Adriane's advice) and there hasn't been any further discussion for some months.

**Closed by svlandeg** 2020-08-25 11:04 UTC
Labels: enhancement, feat / tokenizer, perf / accuracy
