### ISSUE TITLE
nlp pipeline doesn't work when 'merge_noun_chunks' is given as parameter

### ISSUE THREAD

**Issue by ereday** [explosion/spaCy#6097] opened 2020-09-21 11:08 UTC
## How to reproduce the behaviour

For many of the sentences in my dataset, I'm receiving the error below. I shared only one of them but I can provide many more if requested. I should also mention that I have tried this code snippet with many different spacy versions and unfortunately none of them have worked for me so far.

```
import spacy
nlp = spacy.load('de_core_news_lg')
nlp.add_pipe(nlp.create_pipe('merge_noun_chunks'))

text = 'Offenbar handelt es sich aber um ein Revanche gegen Deutschland, das zuvor den Bau von Ungarns Grenzzaun zu Serbien kritisiert hatte.'
doc = nlp(text)

```
Note that the code above works without any problem if I replace the word `Ungarns` with `Ungarn` in the sentence. 

**Error Log:**

```

Traceback (most recent call last):
  File "main.py", line 141, in find_subjects
    doc_sub = nlp2(sent.text)
  File "virtual-environments/spacy2.3/lib/python3.6/site-packages/spacy/language.py", line 449, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "virtual-environments/spacy2.3/lib/python3.6/site-packages/spacy/pipeline/functions.py", line 27, in merge_noun_chunks
    retokenizer.merge(np, attrs=attrs)
  File "_retokenize.pyx", line 62, in spacy.tokens._retokenize.Retokenizer.merge
ValueError: [E102] Can't merge non-disjoint spans. 'Ungarns' is already part of tokens to merge. If you want to find the longest non-overlapping spans, you can use the util.filter_spans helper:
https://spacy.io/api/top-level#util.filter_spans

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "virtual-environments/spacy2.3/lib/python3.6/site-packages/spacy/language.py", line 449, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "virtual-environments/spacy2.3/lib/python3.6/site-packages/spacy/pipeline/functions.py", line 27, in merge_noun_chunks
    retokenizer.merge(np, attrs=attrs)
  File "_retokenize.pyx", line 62, in spacy.tokens._retokenize.Retokenizer.merge
ValueError: [E102] Can't merge non-disjoint spans. 'Ungarns' is already part of tokens to merge. If you want to find the longest non-overlapping spans, you can use the util.filter_spans helper:
https://spacy.io/api/top-level#util.filter_spans
```

## Info about spaCy
* **spaCy version:** 2.3.2
* **Platform:** Linux-5.7.16-200.fc32.x86_64-x86_64-with-fedora-32-Thirty_Two
* **Python version:** 3.6.5

**Comment by adrianeboyd** [comment] 2020-09-21 11:56
Sorry, this is a bug in the German `noun_chunks` iterator that leads to overlapping spans. This is a duplicate of #6073, so I'll merge this issue with that one and close this for now. Thanks for the additional example!

**Closed by adrianeboyd** 2020-09-21 11:56 UTC
Labels: bug, duplicate, lang / de
