### ISSUE TITLE
Version pin prevents numpy 1.13 usage

### ISSUE THREAD

**Issue by zhiruiwang** [explosion/spaCy#1202] opened 2017-07-19 14:59 UTC
I try to install spacy from conda-forge after upgrade my numpy to 1.13.1, while the conda force to downgrade my numpy to 1.12. I wonder whether the spacy support numpy 1.13, or will there be a plan for that?

**Comment by honnibal** [comment] 2017-07-19 18:11
Hi,

This is purely a problem with the version pin --- there's no *actual* incompatibility with numpy 1.13. All we need is a pull request to the conda forge repo with the version pin and SHA updated. If you have a minute, would you mind doing it? Otherwise I can do it, if it's unfamiliar.

Thanks for pointing this out!

**Comment by zhiruiwang** [comment] 2017-07-20 00:45
Hi,
I'm not familiar with how to pull request to conda forge. If you have time, please do so. 
Thank you!

**Comment by zhiruiwang** [comment] 2017-07-27 01:52
Still no one is doing this?

**Comment by Erlemar** [comment] 2017-08-27 15:31
The problem is still actual.It would be great if it is fixed.

**Comment by marikgoldstein** [comment] 2017-10-08 20:13
Not quite used to conda forge but happy to submit a PR.

This is the file in question, right? 
spacy-feedstock/recipe/meta.yaml

**Comment by dataanalyst4lyfe** [comment] 2017-10-18 17:02
I'm still seeing this issue as well.

**Comment by ines** [comment] 2017-11-09 15:42
Should be fixed in the new version, v2.0. We're currently waiting to get it built for conda (it's just taking a bit longer because of Travis errors and the OSX backlogs 😓). 

Once the version is up, could you try again? [See here](https://spacy.io/usage/v2) for details on what's new in v2.0. If there are still problems with conda install and the new version, feel free to reopen.

**Closed by ines** 2017-11-09 15:42 UTC
Labels: conda, install

**Comment by marikgoldstein** [comment] 2017-11-09 15:43
Will do!
