### ISSUE TITLE
Inaccurate lemmatization in italian

### ISSUE THREAD

**Issue by luigibrancati** [explosion/spaCy#10359] opened 2022-02-23 15:02 UTC
## How to reproduce the behaviour

For the code
```
nlp_acc = spacy.load("it_core_news_lg")
print([t.lemma_ for t in nlp_acc("Il galleggiante rimane a galla")])
# EN: the buoy stays afloat
```
The output is
```
['il', 'galleggiante', 'rimare', 'a', 'galla']
# EN: the buoy rhymes afloat
```
The pipeline thinks that **rimane** is some conjugation of the verb **rimare**, which is wrong both based on the context and on the grammar (i.e. rimare never takes the form _rimane_).

This error happens as well for the light pipeline `it_core_news_sm`.

## Your Environment
- **spaCy version:** 3.2.2
- **Platform:** Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- **Python version:** 3.9.0
- **Pipelines:** it_core_news_sm (3.2.0), it_core_news_lg (3.2.0)

**Comment by kadarakos** [comment] 2022-02-24 14:09
Hey @luigibrancati,

Thanks for the detailed report! Just to make sure, the correct output would have been `rimanere` and not `rimare` right?

**Comment by luigibrancati** [comment] 2022-02-24 19:56
Hi @kadarakos,

You're welcome! Yes, `rimane` is 3rd person of present indicative tense for the verb `rimanere`.

**Comment by luigibrancati** [comment] 2022-02-24 19:57
I don't know how much this helps, but I've noticed that [TreeTagger](https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/), another lemmatizer I've tried, gives the same error!

**Comment by kadarakos** [comment] 2022-02-24 20:38
I investigated the issue a bit. The Italian model seems to run the part-of-speech based lookup lemmatizer:

```
In [1]: import spacy

In [2]: nlp_acc = spacy.load("it_core_news_lg")

In [3]: lemmatizer = nlp_acc.get_pipe('lemmatizer')

In [4]: lemmatizer.mode
Out[4]: 'pos_lookup'
```

The part-of-speech tagger correctly classifies "rimane" as a `VERB`:

```
In [9]: [t.pos_ for t in nlp_acc("Il galleggiante rimane a galla")]
Out[9]: ['DET', 'PROPN', 'VERB', 'ADP', 'NOUN']
```

so let's checkout the corresponding lookup table:

```
In [14]: lookup_table = lemmatizer.lookups.get_table('lemma_lookup_verb')

In [15]: lookup_table.get('rimango')
Out[15]: 'rimanere'

In [16]: lookup_table.get('rimani')
Out[16]: 'rimanere'

In [17]: lookup_table.get('rimane')
Out[17]: 'rimare'

In [18]: lookup_table.get('rimaniamo')
Out[18]: 'rimanere'

In [19]: lookup_table.get('rimanete')
Out[19]: 'rimanere'

In [20]: lookup_table.get('rimangono')
Out[20]: 'rimanere'
```

To me it seems like the issue is with the lookup table.

**Comment by luigibrancati** [comment] 2022-02-24 20:43
@kadarakos I agree with you, the issue seems to be with the lookup table itself. I didn't encounter any other error like this one, but next time I'll be sure to check the table!

**Comment by kadarakos** [comment] 2022-02-28 08:19
Hey @luigibrancati,

Thanks again for your report! The `rimane --> rimanere` fix in the lemmatizer lookup is merged:  https://github.com/explosion/spacy-lookups-data.

**Closed** 2022-02-28 09:34 UTC
Labels: lang / it, feat / lemmatizer, perf / accuracy
