### ISSUE TITLE
thinc error on parallel training of bots using spacy with using & in curl commands to send requests to rasa server.

### ISSUE THREAD

**Issue by shayan09** [explosion/spaCy#4745] opened 2019-12-02 23:12 UTC
## The following is the error:

```
[2019-12-02 18:06:03,375] ERROR in app: Exception on /train [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "predictor_app.py", line 73, in train_route
    interpreter_dict[model_name] = Interpreter.load(model_path[model_name])
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/model.py", line 304, in load
    skip_validation)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/model.py", line 331, in create
    model_metadata, **context)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/components.py", line 425, in load_component
    cached_component, **context)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/registry.py", line 172, in load_component_by_meta
    cached_component, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/utils/spacy_utils.py", line 114, in load
    nlp = spacy.load(model_name, disable=['parser'])
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 787, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, exclude=["vocab"])
  File "pipes.pyx", line 617, in spacy.pipeline.pipes.Tagger.from_disk
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "pipes.pyx", line 599, in spacy.pipeline.pipes.Tagger.from_disk.load_model
  File "pipes.pyx", line 512, in spacy.pipeline.pipes.Tagger.Model
  File "/usr/local/lib/python3.6/dist-packages/spacy/_ml.py", line 513, in build_tagger_model
    pretrained_vectors=pretrained_vectors,
  File "/usr/local/lib/python3.6/dist-packages/spacy/_ml.py", line 351, in Tok2Vec
    (norm | prefix | suffix | shape)
  File "/usr/local/lib/python3.6/dist-packages/thinc/check.py", line 129, in checker
    raise UndefinedOperatorError(op, instance, args[0], instance._operators)
thinc.exceptions.UndefinedOperatorError: 

  Undefined operator: |
  Called by (<thinc.neural._classes.hash_embed.HashEmbed object at 0x7fdbbc858cf8>, <thinc.neural._classes.hash_embed.HashEmbed object at 0x7fdbbc865e48>)
  Available: >>, +, |, *, 

  Traceback:
  |__ <lambda> [787] in /usr/local/lib/python3.6/dist-packages/spacy/language.py
  |____ from_disk [630] in /usr/local/lib/python3.6/dist-packages/spacy/util.py
  |_____ build_tagger_model [513] in /usr/local/lib/python3.6/dist-packages/spacy/_ml.py
         >>> pretrained_vectors=pretrained_vectors,

127.0.0.1 - - [02/Dec/2019 18:06:03] "POST /train HTTP/1.1" 500 -
```

## Environment
* Operating System: Ubuntu 18.04
* Python Version Used: 3.6.9
* spaCy Version Used: 2.1.4
* Environment Information: Using it with rasa nlu

I have sent the following curl commands to the Flask server:
```
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_1\", \"choices\": [{\"intent\": \"Thank\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Deny\"}, {\"intent\": \"Bye\"}, {\"intent\": \"Colors\"}, {\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done1" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_2\", \"choices\": [{\"intent\": \"Bye\"}, {\"intent\": \"Colors\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done2" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_3\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done3" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_4\", \"choices\": [{\"intent\": \"Thank\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Deny\"}, {\"intent\": \"Bye\"}, {\"intent\": \"Colors\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done4" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_5\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Thank\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done5" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_6\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Colors\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done6" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_7\", \"choices\": [{\"intent\": \"Thank\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Deny\"}, {\"intent\": \"Positive_feeling\"},{\"intent\": \"Negative_feeling\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done7" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_8\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Affirm\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done8" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_9\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Bye\"}], \"threshold\": 0.65}" localhost:5556/train && echo "done9" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_10\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Deny\"}], \"threshold\": 0.7}" localhost:5556/train && echo "done10" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_11\", \"choices\": [{\"intent\": \"Positive_feeling\"}, {\"intent\": \"Negative_feeling\"}, {\"intent\": \"Bye\"}, {\"intent\": \"Colors\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done11" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_12\", \"choices\": [{\"intent\": \"Bye\"}, {\"intent\": \"Thank\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done12" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_13\", \"choices\": [{\"intent\": \"Negative_feeling\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Deny\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done13" &
curl -X POST -H 'Content-Type: application/json' -d "{\"bot_id\": \"mybot_1\", \"message_id\": \"message_14\", \"choices\": [{\"intent\": \"Thank\"}, {\"intent\": \"Affirm\"}, {\"intent\": \"Colors\"}], \"threshold\": 0.0}" localhost:5556/train && echo "done14"
```

PS: I tried training 14 bots simultaneously out of which 11 were successful and the others returned the error. They work if the curl commands are sent sequentially, but not concurrently. Any idea why this would happen?

**Comment by adrianeboyd** [comment] 2019-12-03 07:14
Hi, this is a duplicate of #4349 and should be fixed in the next release of thinc.

**Comment by shayan09** [comment] 2019-12-05 17:52
@adrianeboyd I tried your PR on thinc and it works well. However, I get this warning on downloading the spaCy model:
```
/home/shayan/.virtualenvs/rasa_nlu/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: thinc.extra.search.Beam size changed, may indicate binary incompatibility. Expected 112 from C header, got 120 from PyObject
  return f(*args, **kwds)
```

**Comment by adrianeboyd** [comment] 2019-12-05 19:18
That's due to another patch in between. To avoid it, start with the last tagged release (v7.3.1) and then cherry-pick the commit for that PR.

**Comment by burakbigle** [comment] 2020-01-21 09:48
I would like to report the same issue, still ongoing for me.

```
thinc.exceptions.UndefinedOperatorError: 
Undefined operator: >>
  Called by (<thinc.neural._classes.function_layer.FunctionLayer object at 0x00000236CEBF6448>, <thinc.neural._classes.feed_forward.FeedForward object at 0x00000236CEA60908>)
  Available: 

  Traceback:
  ├─ from_disk [654] in C:\Users\Bigle Legal\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py
  ├─── <lambda> [936] in C:\Users\Bigle Legal\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\language.py
  └───── Tok2Vec [323] in C:\Users\Bigle Legal\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\_ml.py
         >>> return _legacy_tok2vec.Tok2Vec(width, embed_size, **kwargs
```

- Operating System: Windows 10
- Python Version Used: 3.7.4
- spaCy Version Used: 2.2.3
- thinc  Version Used: 7.3.1
- Environment Information: Only SpaCy with pure Python.

I am using the latest available thinc and Spacy versions. However, I get this error at random times. If I request the info from the server several times, It works. But it is quite unpredictable when will it work, or when this error will occur.  Is it because of my Python version? As far as I researched, this issue has been closed with "fixed" tag. Is it still an ongoing problem?

**Comment by svlandeg** [comment] 2020-02-06 15:29
This issue should be fixed from thinc version v7.4.0.dev1 upwards, cf https://github.com/explosion/thinc/pull/124, this is also the version to which spaCy's current `master` branch is pinned.

**Closed by svlandeg** 2020-02-06 15:29 UTC
Labels: bug, duplicate, 🔮 thinc

**Comment by gthb** [comment] 2020-02-13 13:26
> thinc version v7.4.0.dev1 upwards, cf [explosion/thinc#124](https://github.com/explosion/thinc/pull/124), this is also the version to which spaCy's current `master` branch is pinned.

No it's not, spaCy's current `master` branch is pinned to `thinc==7.4.0.dev0`.

But you probably meant “from thinc v7.4.0.dev0” upwards, as that release already contains explosion/thinc#124 https://github.com/explosion/thinc/compare/v7.3.1...v7.4.0.dev0 — correct?

**Comment by svlandeg** [comment] 2020-02-13 13:31
Yep, you're right. It's in any `thinc` release higher than 7.3.1, so it is already in `7.4.0.dev0` which is the version the spaCy master branch is using right now.

I got thrown off by the commit message [here](https://github.com/explosion/thinc/commit/b1a98d70fc52f04e49569d800a6a62bd994dc063#diff-f8a03c7d0f7c61b29c7eb5e20ac4ab09) :-)
