### ISSUE TITLE
make_doc becomes extremely slow after some upgrade of MacOs

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#7687] opened 2021-04-07 21:54 UTC
Spacy: 2.3.0
MacPro: BigSur 11.2.3

After some update of my MacOS, for various reasons I had to reinstall xcode command line tools, also used pyenv to install python 3.7.8, to make it co-exists with Python 3.8. 

Now the problem is that I ran the same program developed on my Spacy project, and the loading dictionary part becomes extremely slow. 10000 entries takes several minutes, which used to take seconds. No any error or warning messages.

`doc = Doc(self.vocab, words=words, spaces=spaces)`

To test that it is not due to tokenization issue, I hard coded the words and spaces list before calling the above line:
```
words = ['test']
spaces=[False]
```
It is the same problem.  I suspect some Mac system environment interact with some spacy Cython code and caused the degradation. But we have used Spacy for quite some time and this is the first time to observe this phenoninum. Strange. My gcc version:

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

 
```

I am thinking to reinstall my Mac and recompile spacy to see whether the issue go away. This way all the recent updates/upgrades to MacOS and development tools will be removed.  

Has anybody encountered similar issues?

**Comment by nidharap** [comment] 2021-04-07 23:40
I have the same problem. I actually have a previous venv on the same machine and it works just fine, but when I recreate the new environment and install requirements, the make_doc is extremely slow

**Comment by polm** [comment] 2021-04-08 05:04
That's pretty weird, I don't think we've had any reports of that before. @nidharap Could you post the output of `pip freeze` for both your environments so we can compare the versions? If it's not a version difference in spaCy, it could theoretically be something in a dependency.

**Comment by nidharap** [comment] 2021-04-08 05:08
@polm  Sure. As you said, my spacy versions are the same. It might be some dependency. 
pip freeze that works: 
anytree==2.8.0
appnope==0.1.2
argcomplete==1.10.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
azure-common==1.1.24
azure-core==1.8.0
azure-functions==1.3.0
azure-identity==1.4.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.0
azure-keyvault-secrets==4.2.0
azure-nspkg==3.0.2
azure-servicebus==7.0.0
azure-storage-blob==12.3.2
backcall==0.2.0
beautifulsoup4==4.8.0
bleach==3.3.0
blis==0.4.1
bs4==0.0.1
cachetools==4.2.1
catalogue==1.0.0
certifi==2020.6.20
cffi==1.14.5
chardet==3.0.4
click==7.1.2
contextvars==2.4
cryptography==3.4.6
cymem==2.0.5
dataclasses==0.8
decorator==4.4.1
defusedxml==0.7.1
dill==0.3.3
docutils==0.15.2
en-core-web-sm==2.3.1
entrypoints==0.3
filelock==3.0.12
future==0.18.2
fuzzywuzzy==0.18.0
google-api-core==1.26.1
google-auth==1.27.1
googleapis-common-protos==1.53.0
ibm-cloud-sdk-core==1.5.1
ibm-cos-sdk==2.7.0
ibm-cos-sdk-core==2.7.0
ibm-cos-sdk-s3transfer==2.7.0
ibm-watson==4.6.0
idna==2.9
imbalanced-learn==0.5.0
immutables==0.15
importlib-metadata==3.7.2
ipykernel==5.5.0
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
isodate==0.6.0
jedi==0.18.0
jellyfish==0.6.1
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonpickle==1.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.3.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
MarkupSafe==1.1.1
mistune==0.8.4
msal==1.10.0
msal-extensions==0.2.2
msrest==0.6.21
murmurhash==1.0.5
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5
nltk==3.4.5
notebook==6.3.0
numpy==1.19.2
oauthlib==3.0.1
opencensus==0.7.12
opencensus-context==0.1.2
opencensus-ext-azure==1.0.5
opencv-python==4.4.0.44
packaging==20.9
pandarallel==1.4.8
pandas==1.1.3
pandocfilters==1.4.3
parso==0.8.1
pdfminer==20191125
pdfminer.six==20201018
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.2
plac==1.1.3
plotly==4.14.3
ply==3.11
portalocker==1.7.1
preshed==3.0.5
probableparsing==0.0.1
prometheus-client==0.9.0
prompt-toolkit==3.0.18
protobuf==3.15.6
psutil==5.7.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodome==3.9.7
pydantic==1.6.1
Pygments==2.8.1
PyJWT==1.7.1
pyparsing==2.4.7
pyPdf==1.13
PyPDF2==1.26.0
PyPDF4==1.27.0
pyrsistent==0.17.3
python-crfsuite==0.9.7
python-dateutil==2.8.1
pytz==2020.1
pyzmq==22.0.3
qtconsole==5.0.3
QtPy==1.9.0
regex==2020.11.13
requests==2.24.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
sacremoses==0.0.43
scikit-learn==0.22.1
scikit-video==1.1.11
scipy==1.5.4
Send2Trash==1.5.0
six==1.15.0
sortedcontainers==2.3.0
soupsieve==2.0.1
spacy==2.3.2
srsly==1.0.5
terminado==0.9.3
testpath==0.4.4
textblob==0.15.3
thinc==7.4.1
tokenizers==0.10.1
torch==1.8.1
tornado==6.1
tqdm==4.59.0
traitlets==4.3.3
transformers==4.3.2
typing-extensions==3.7.4.3
uamqp==1.2.15
Unidecode==1.1.1
urllib3==1.25.9
us==2.0.2
usaddress==0.5.10
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.48.0
widgetsnbextension==3.5.1
xlrd==1.2.0
zipp==3.4.1


pip freeze that does not:
argcomplete==1.10.0
azure-common==1.1.24
azure-core==1.8.0
azure-functions==1.3.0
azure-identity==1.4.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.0
azure-keyvault-secrets==4.2.0
azure-nspkg==3.0.2
azure-servicebus==7.0.0
azure-storage-blob==12.3.2
beautifulsoup4==4.8.0
blis==0.4.1
bs4==0.0.1
cachetools==4.2.1
catalogue==1.0.0
certifi==2020.6.20
cffi==1.14.5
chardet==3.0.4
contextvars==2.4
cryptography==3.4.7
cymem==2.0.5
dataclasses==0.8
decorator==4.4.1
dill==0.3.3
docutils==0.15.2
en-core-web-sm==2.3.1
future==0.18.2
fuzzywuzzy==0.18.0
google-api-core==1.26.3
google-auth==1.28.0
googleapis-common-protos==1.53.0
ibm-cloud-sdk-core==1.5.1
ibm-cos-sdk==2.7.0
ibm-cos-sdk-core==2.7.0
ibm-cos-sdk-s3transfer==2.7.0
ibm-watson==4.6.0
idna==2.9
imbalanced-learn==0.5.0
immutables==0.15
importlib-metadata==3.10.0
isodate==0.6.0
jellyfish==0.6.1
jmespath==0.10.0
joblib==1.0.1
jsonpickle==1.2
msal==1.10.0
msal-extensions==0.2.2
msrest==0.6.21
murmurhash==1.0.5
networkx==2.5
nltk==3.4.5
numpy==1.19.2
oauthlib==3.0.1
opencensus==0.7.12
opencensus-context==0.1.2
opencensus-ext-azure==1.0.5
opencv-python==4.4.0.44
packaging==20.9
pandarallel==1.4.8
pandas==1.1.3
pdfminer==20191125
pdfminer.six==20201018
pickleshare==0.7.5
Pillow==8.2.0
plac==1.1.3
ply==3.11
portalocker==1.7.1
preshed==3.0.5
probableparsing==0.0.1
protobuf==3.15.7
psutil==5.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodome==3.9.7
pydantic==1.6.1
PyJWT==1.7.1
pyparsing==2.4.7
pyPdf==1.13
PyPDF2==1.26.0
PyPDF4==1.27.0
python-crfsuite==0.9.7
python-dateutil==2.8.1
pytz==2020.1
regex==2020.11.13
requests==2.24.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
scikit-learn==0.22.1
scikit-video==1.1.11
scipy==1.5.4
six==1.15.0
sortedcontainers==2.3.0
soupsieve==2.0.1
spacy==2.3.2
srsly==1.0.5
textblob==0.15.3
thinc==7.4.1
tqdm==4.60.0
typing-extensions==3.7.4.3
uamqp==1.3.0
Unidecode==1.1.1
urllib3==1.25.9
us==2.0.2
usaddress==0.5.10
wasabi==0.8.2
websocket-client==0.48.0
xlrd==1.2.0
zipp==3.4.1

**Comment by nidharap** [comment] 2021-04-08 05:10
> @nidharap are you sure it's due to make_doc? I debugged and found it's because of that. I have ran spacy on Mac, Windows, Linux, and created numerous virtual environments at different times, and didn't have this problem. Only today this happened first time. It's likely my mac is the latest Big Sur 11.2.3, and installed Xcode command line tools several times due to some other problems in installing multiple Python versions.
> 
> How did you fix your slowness?

I am pretty sure it is make_doc. I did the same, debug through to get to that point and I see a delay

**Comment by polm** [comment] 2021-04-08 05:45
Thanks for the env details! I did a diff on them and didn't see anything that would obviously be a potential cause of slowdown like this... Assuming you used wheels for install I have a hard time imagining what could cause this. 

It might take a while, but compiling spaCy from scratch is worth a shot if you have the environment for it.

**Comment by honnibal** [comment] 2021-04-08 08:00
This sounds extremely strange to me. To be clear, you're using an x86 Macbook right, not the new M1?

Could you try using the [`py-spy`](https://github.com/benfred/py-spy) or [`perf`](https://perf.wiki.kernel.org/index.php/Main_Page) utilities to understand something about what's going wrong? `py-spy` is probably best. You'll need to tell it to profile the native calls as well, so that we can see which bits of the underlying machinery are taking longer.

**Comment by lingvisa** [comment] 2021-04-08 21:42
@honnibal I used py-spy to generate two screenshots. Could you please take a look to see whether any clue can be seen? Yes, I am using MacBook X86 intel core i9.
1) The 1st:  sudo py-spy top -- python tools/wbnlp_api.py
<img width="1514" alt="Screen Shot 2021-04-08 at 2 35 05 PM" src="https://user-images.githubusercontent.com/7905135/114099783-3c4b5700-9878-11eb-8aa9-7ce4478974d3.png">

2) The 2nd: sudo py-spy record -o profile.svg -- python tools/wbnlp_api.py
<img width="1324" alt="Screen Shot 2021-04-08 at 2 40 52 PM" src="https://user-images.githubusercontent.com/7905135/114099939-70bf1300-9878-11eb-99b2-2077ce54fe97.png">

Please note that I am not using Spacy as is, but with minor changes in __init__.py in language class and recompile it. It has been good for a long time run on different environments.

**Comment by lingvisa** [comment] 2021-04-08 21:49
Add --native doesn't change too much:

`sudo py-spy top -- python tools/wbnlp_api.py --native`

![Uploading Screen Shot 2021-04-08 at 2.49.49 PM.png…]()

**Comment by lingvisa** [comment] 2021-04-08 22:03
Add one stacktrace:
<img width="1318" alt="Screen Shot 2021-04-08 at 3 03 01 PM" src="https://user-images.githubusercontent.com/7905135/114102093-94378d00-987b-11eb-8e98-f0424ba8ce50.png">

**Comment by lingvisa** [comment] 2021-04-09 21:55
I took another screen shot taken from "a normal run" of the code, which was created in another earlier environment on the same machine. This environment works as expected. By comparing the two profilings, it looks like those functions below slow down the program:
```
  getmodule
 call_with_frames_removed
get (import_lib_metadata) 
```
 All those are not spacy/my own code, but the python interpreter's code base.

@polm @honnibal Any observations or comments on the profiling reports and the potential cause of it? 
![Uploading Screen Shot 2021-04-09 at 2.54.46 PM.png…]()

**Comment by benfred** [comment] 2021-04-09 22:40
py-spy doesn't have native unwind support on OSX =( the native flags you specified in the 'top' commandline is being passed to the python program rather than to py-spy (py-spy will error out if passed ``--native``` on OSX).

**Comment by lingvisa** [comment] 2021-04-09 22:51
@benfred Do you have sense of what might be the issue of the code by the profilings? I am clueless.

**Comment by polm** [comment] 2021-04-10 05:01
Uh, did you close the issue because you solved the problem? If so it'd be great if you could share the solution here for other people affected.

**Comment by lingvisa** [comment] 2021-04-10 05:18
I accidentally closed the issue? I didn't intend to do that, and I can't find the 'reopen' button. Can you reopen it if you can?
 But eventually,  I may already find a solution, though not exactly knowing the cause.

It turns out that my Linux copy has the same issue, when I recompiling it in another virtual environment on the same machine. After doing many trials, code debugging, I 'pip freeze' those dependencies from the previous virtual environment that has been working well into a new requirements.txt and then used this requirements.txt to create a new virtual environment, then recompiled my project, including spacy. It worked, and the speed is back to normal. 

I need to find out exactly what dependency diffs that caused the huge slowing down of the make_doc function in Spacy. Based on the two comparative profiles above I listed above, some python low level code caused the issue due to some dependencies. The exact cause is yet to be known.

**Comment by polm** [comment] 2021-04-10 05:28
If you could post the output of `pip freeze` for both environments that would be helpful.

**Comment by adrianeboyd** [comment] 2021-04-12 07:09
I would be curious: what version of python in each env and what version of `importlib-metadata`, if it's installed as a separate package?

**Comment by lingvisa** [comment] 2021-04-12 17:40
After some more digging, I can confirm that the trouble maker is the 'importlib-metadata' versions. In one environment in which importlib-medata 3.7.3 is installed, the speed is normal, but in another environment, importlib-metadata 3.10.0 is installed, the speed is abnormal. In both cases, I didn't list importlib-metadata in my requirements.txt and they were installed automatically due to other dependencies. These two environments install different dependencies, so the version could be different.

I haven't specified importlib-metadata in my requirements.txt in the past and it has worked.  The sudden appearance of this speed issue is likely due to the changing nature of pip itself, when 'pip install --upgrade pip'. For example, I didnt' get this warning in the past, but now has seen it:

`warning: /Users/congminmin/nlp/wb-nlp-tool/spaCy-wb/spacy/vocab.pxd:29:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables`

The attached requirements.txt is what I am using. If you remove 'importlib-metadata==3.7.3' and let 3.10.0 be installed automatically on my Mac and Linux as well, the issue can be reproduced in my project. I didn't test the original spacy without any modification. I had minor tweak on Spacy in my project, and the problem can be reproduced as described. So the solution for me is to specify the importlib-metadata's version spcifically in requirement.txt.

**Comment by lingvisa** [comment] 2021-04-12 17:42
[requirements.txt](https://github.com/explosion/spaCy/files/6298705/requirements.txt)

**Comment by adrianeboyd** [comment] 2021-04-12 17:59
Okay, we should push the new version of `catalogue` that restricts the version of `importlib-metadata`. See also #7628.

We merged the change in `catalogue` because of an unrelated test failure (and I was honestly hoping not to have to restrict it because it will probably lead to dependency conflicts with other packages), but this is too many reports of performance regressions, and there are so many recent changes and releases that I haven't managed to track down exactly what's going. (It's something about how it iterates over entry points, I think.)

This will only restrict the upper version for python 3.6-3.7. If you've installed it because of some other package in python 3.8+, I don't think there's much we can do other than adding some notes to the docs.

The `cpdef` warning is separate and only related to cython. We should work on getting the code compatible with cython 3 at some point, though.

**Comment by lingvisa** [comment] 2021-04-12 18:19
It's good to find out the cause and double confirmed.

**Comment by svlandeg** [comment] 2021-04-19 16:13
This is being addressed on our end (https://github.com/explosion/catalogue/pull/18) and there's a clear way to work around this, so I think we can mark this as resolved & closed? (if not, let me know)

**Closed** 2021-04-27 00:06 UTC
Labels: osx, perf / speed, resolved
