### ISSUE TITLE
Assert on legal input

### ISSUE THREAD

**Issue by luang008** [explosion/spaCy#391] opened 2016-05-20 21:32 UTC
Hello!
Just want to report something unexpected to me. I will be very grateful if anyone would let me know what's this assert for because this input looks fine to me.

Code

```
text = u"Lol Pitt Civil Engineering students do senior design projects on this problem"
nlp = spacy.en.English()
nlp.matcher = None
doc = nlp(text)
print (doc.ents)
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 118, in <module>
    print (docents)

  File "spacy/tokens/doc.pyx", line 199, in spacy.tokens.doc.Doc.ents.__get__ (spacy/tokens/doc.cpp:7191)
AssertionError
``` 

I am at version 0.101.0.

**Comment by gtoos** [comment] 2016-05-24 10:03
We are facing the same issue.

**Comment by honnibal** [comment] 2016-05-24 11:35
Thanks for the report, and sorry for the delay. Will try to get to this today.

**Comment by gauss256** [comment] 2016-07-30 15:00
Here are several more examples where `doc.ents` results in an AssertionError.

[enc_asserts.txt](https://github.com/spacy-io/spaCy/files/391932/enc_asserts.txt)

**Comment by honnibal** [comment] 2016-10-23 14:13
I regret that I'm only dealing with this now...

I can't reproduce this issue, on either 0.101.0 or 1.0. Thoughts?

**Comment by honnibal** [comment] 2016-10-24 12:07
Tentatively closing this — please reopen if the problem's still there.

**Closed by honnibal** 2016-10-24 12:07 UTC
Labels: bug
