### ISSUE TITLE
is there a smaller english Glove less than 1M vectors

### ISSUE THREAD

**Issue by hartsantler** [explosion/spaCy#708] opened 2016-12-25 21:37 UTC
The default setup of spaCy uses en_glove_cc_300_1m_vectors, which is pretty large:
- 774MB  data/en_glove_cc_300_1m_vectors/vocab/vec.bin
- 202MB  data/en-1.1.0/vocab/vec.bin
- 80MB  data/en-1.1.0/vocab/lexemes.bin

Is there anything smaller?  For testing, and quick dev cycles, i would rather have faster loading and less accuracy.  My netbook only has 2GB of ram, and spaCy with the default english model needs about 1.8GB of ram, which forces me to close every other window so it can run without crashing.

**Comment by kootenpv** [comment] 2016-12-31 12:57
The load time is also an issue for me while developing. I indeed think that a simple "dev" switch somewhere would be a huge benefit.

**Comment by honnibal** [comment] 2017-01-01 23:55
Working on a good solution to this.

In the meantime: have you tried parsing and serializing your test documents? You could then load a dummy pipeline that just deserialises the documents, and looks up the text in a hash table. This would prevent you from having to load the parser and NER models, saving you some load time.

**Comment by kootenpv** [comment] 2017-01-02 08:08
@honnibal I'm often using it interactively :) 

But indeed, I also have some dataset with 100k docs. The problem is that I always want to do a little bit of a different preprocessing (I'm slowly realising most of it is possible in spaCy). In some cases loading the model takes longer than the processing that I do, which is of course perfect for production :) 

It's fantastic to hear you're working on a solution.

**Comment by honnibal** [comment] 2017-01-02 09:47
Well, the serializer is lossless — you get the same thing back from `Doc(vocab).from_bytes(serialized)` as you do from `doc = nlp(text)`. So, unless your processing is changing the text before giving it to spaCy, you should be able to cache and reuse the bytes. You could also set up a redis service to ensure no work is repeated. The serializer is very space efficient — the serialized form takes up about the same amount of space as the original string.

**Comment by kootenpv** [comment] 2017-01-02 10:00
I indeed meant preprocessing *before* spacy (e.g. contractions / resolving some entities to a common form). But in fact, I have no problem waiting 1 minute for parsing the docs a couple of times, it is when exposing it on a webpage, the integration of spacy as backend, that you'd want it to load faster (without caring at all whether you really get correct parses).

**Comment by mattmacy** [comment] 2017-01-09 07:49
@hartsantler I'm doing an experiment doing k-mediod using cosine similarity for cluster membership, using the centroid as the vector for all members as a means of compression of the vectors for less common words. This would reduce the total number of word vectors for the first 1 million vectors in common crawl down to 20k-80k, keeping the first ~10k as is (as suggested in a github issue by @honnibal himself). Intuitively it makes sense that one could use "fuzzier" vectors for infrequently used words, but I have no idea how well it will work in practice.

**Comment by mattmacy** [comment] 2017-01-30 07:19
@hartsantler clustering didn't quite deliver as I'd hoped. However, I do have a pull request in that should reduce the load time to ~2s on a slow laptop. Watch https://github.com/explosion/spaCy/pull/788

**Comment by ines** [comment] 2017-03-18 20:45
We just pushed a new release that also comes with a smaller model (including word vectors) that should take significantly less time to load (~50MB, about 2% less accurate than the larger model).

The small model is now the default model, so in 1.7.0, you can simply do:

```bash
python -m spacy download en # download small model (50MB)
python -m spacy download en_core_web_md # download medium model (1GB)
```

* [Release notes](https://github.com/explosion/spaCy/releases) for 1.7.0
* [Models documentation](https://spacy.io/docs/usage/models)
* [Command line interface documentation](https://spacy.io/docs/usage/cli)

**Closed by ines** 2017-03-18 20:45 UTC
Labels: performance, v2
