### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by lakchchayam** [explosion/spaCy#8820] opened 2021-07-28 05:49 UTC
![image](https://user-images.githubusercontent.com/49754403/127270438-4caf10cb-b056-43aa-b2f2-d1361e14aab8.png)

**Comment by polm** [comment] 2021-07-28 05:57
You need to run `spacy download en_core_web_sm`. 

Since this is not a bug report, moving to Discussions.

**Closed** 2021-07-28 05:57 UTC
