### ISSUE TITLE
Hang on anaconda install with windows (possible solution?)

### ISSUE THREAD

**Issue by johnfwhitesell** [explosion/spaCy#1981] opened 2018-02-13 16:48 UTC
When I tried to install spaCy on my windows PC, it hung during the anaconda install process.  The install proceeded to the y/n prompt to continue with the install but after this point, it just hung.  Installing the html5lib into python ("conda install -c anaconda html5lib") seemed to solve this problem.  However before both installing html5lib and spaCy I had to first delete the contents of my "Anaconda3\pkgs\.trash" folder.

TBH I'm quite a bit over my head here so I can only speculate on why this worked but maybe someone will find this helpful with installing or figuring out what the problem is.

## Your Environment
* **spaCy version:** 2.0.7
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.3
Anaconda version: conda 4.4.10

**Comment by ines** [comment] 2018-03-27 21:13
Thanks for the report and sharing your solution! This is pretty strange indeed – it's also possible that the issue is now fixed in the latest release. I remember having to adjust something regarding the `html5lib` dependency when we uploaded spaCy to conda.

In any case, we're definitely going to drop the dependency with the next minor version, `v2.1.0`. (Ironically, spaCy doesn't even use it – it's mostly there to ensure compatibility of `six`, which we'll also be dropping.)

**Closed by ines** 2018-03-27 21:13 UTC
Labels: conda, install
