### ISSUE TITLE
Custom pipeline component not executing

### ISSUE THREAD

**Issue by kevinrosenberg21** [explosion/spaCy#1885] opened 2018-01-24 16:45 UTC
## Info about spaCy

* **Platform:** Linux-4.13.0-26-generic-x86_64-with-debian-stretch-sid
* **spaCy version:** 2.0.5
* **Python version:** 3.5.2
* **Models:** en, es

Hi,

I'm trying to implement a custom pipeline component that sets the doc as a single sentence, from a blank Spanish Language.
```

import spacy

nlp = spacy.blank('es')
```

The component is below
```

def sbd(doc):
    print("EXECUTING SBD!!!!!!!!!!!!!!!!!!!!")
    doc[0].is_sent_start = True
    for i in range(1, len(doc)):
        doc[i].is_sent_start = False
    if len(list(doc.sents)) == 1:
        print("There's a single sentence")
    else:
        print("Something went wrong")
    return doc
```

I then add it

`nlp.add_pipe(sbd, first=True)`

Save it to disk, load it, and execute it on a text
```
nlp.to_disk('./model/v13-single-sentence')
nlp = spacy.load('./model/v13-single-sentence')
doc1 = nlp(txt4)
```
After executing nlp on txt4, however, nothing is printed and len(list(doc1.sents)) is not 1 like it should.

My main goal is to use that component just before NER and parsing, but since it wasn't working I reduced the problem to the simplest state I could. 

Is this a bug or am I doing something wrong?

Thank you, and regards.

**Comment by ines** [comment] 2018-01-24 16:55
I think the problem here is that spaCy doesn't actually serialize the pipeline components when you save out the model. This is by design – otherwise, spaCy would have to serialize and execute arbitrary code when loading a model and calling a loaded pipeline, which is potentially very problematic.

So you'll either have to re-add the pipeline component after loading the model, or ship the code with your model. You can do this by wrapping the model as a Python package (using the `package` command), and adding the custom component to the package's `__init__.py` ([see here](https://spacy.io/usage/training#models-custom) for more details). You could also consider wrapping your component as a Python package and making your models depend on it.

**Comment by kevinrosenberg21** [comment] 2018-01-24 18:53
@ines Thank you for your answer, it's executing now! I'm not sure if I should open a new thread for this, but now instead of changing the sentence boundaries to take the whole document as a sentence it throws two different errors.

If I only add my custom component I get this error:

> ValueError: Sentence boundary detection requires the dependency parse, which requires a statistical model to be installed and loaded.

If I add the parser pipeline

```
nlp = spacy.blank('es')
parser = nlp.create_pipe('parser')
nlp.add_pipe(parser, last=True)
def custom_sbd(doc):
    print("EXECUTING SBD!!!!!!!!!!!!!!!!!!!!")
    doc[0].sent_start = True
    for i in range(1, len(doc)):
        doc[i].sent_start = False
    return doc
nlp.begin_training()
nlp.add_pipe(custom_sbd, first=True)
```
I get the same error. 

If I change the order for it to parse first, the error changes to 

> Refusing to write to token.sent_start if its document is parsed, because this may cause inconsistent state.

So if it throws an error requiring the dependency parse if it's not present or it executes after, and a different error when the dependency parse is executed first, what's the appropriate way to do it?

Thank you!

**Comment by ines** [comment] 2018-01-25 13:21
Thanks for bringing this up – and sorry this is a little confusing. I'm pretty sure the first problem you describe is already fixed on `master`. spaCy should definitely respect custom sentence boundaries, even in pipelines with no dependency parser.

If you want to use your custom SBD component without a parser, a very simple solution would be to set `doc.is_parsed = True` in your custom component. So [when `Doc.sents` checks for the dependency parse](https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L523), it looks at `is_parsed` and won't complain.

If you want to use your component with the parser, make sure to add it *before* the parser. The parser should always respect already set sentence boundaries from previous processing steps.

**Closed** 2018-01-25 13:39 UTC
Labels: usage
