### ISSUE TITLE
PyInstaller ModuleNotFoundError: No module named 'srsly.msgpack.util'

### ISSUE THREAD

**Issue by Zast996** [explosion/spaCy#6534] opened 2020-12-09 08:34 UTC
I'm facing this problem when I try to execute a file.exe which uses a py script that includes spacy.
I tried to use the solutions from #2514, so:
- conda update --all
- conda install -c conda-forge spacy
- pip uninstall msgpack-python -> pip/conda install msgpack 
- hiddenimport srsly.msgpack.util (for this one, the error becomes No module named cymem and so on if I continue to use hiddenimport)

## How to reproduce the behaviour
command: pyinstaller --onefile  script.py
```
58 INFO: PyInstaller: 4.1
58 INFO: Python: 3.8.5 (conda)
59 INFO: Platform: Windows-10-10.0.19041-SP0
61 INFO: wrote D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\spacy_to_BERT_dataset.spec
64 INFO: UPX is not available.
66 INFO: Extending PYTHONPATH with paths
['D:\\User\\sergi\\Desktop\\Annotators\\Spacy_NER_Annotator',
 'D:\\User\\sergi\\Desktop\\Annotators\\Spacy_NER_Annotator']
73 INFO: checking Analysis
74 INFO: Building Analysis because Analysis-00.toc is non existent
75 INFO: Initializing module dependency graph...
76 INFO: Caching module graph hooks...
88 INFO: Analyzing base_library.zip ...
2148 INFO: Processing pre-find module path hook distutils from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2149 INFO: distutils: retargeting to non-venv dir 'd:\\anaconda\\envs\\annotator\\lib'
4539 INFO: Caching module dependency graph...
4811 INFO: running Analysis Analysis-00.toc
4825 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\anaconda\envs\annotator\python.exe
5053 INFO: Analyzing D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\spacy_to_BERT_dataset.py
5713 INFO: Processing pre-find module path hook site from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
5713 INFO: site: retargeting to fake-dir 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\fake-modules'
10622 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
11478 INFO: Processing pre-safe import module hook six.moves from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
12801 INFO: Processing module hooks...
12801 INFO: Loading module hook 'hook-certifi.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12806 INFO: Loading module hook 'hook-cryptography.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13010 INFO: Loading module hook 'hook-jsonschema.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13028 INFO: Loading module hook 'hook-pycparser.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13028 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13150 INFO: Loading module hook 'hook-difflib.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13153 INFO: Excluding import of doctest from module difflib
13153 INFO: Loading module hook 'hook-distutils.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13155 INFO: Loading module hook 'hook-distutils.util.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13157 INFO: Excluding import of lib2to3.refactor from module distutils.util
13158 INFO: Loading module hook 'hook-encodings.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13223 INFO: Loading module hook 'hook-heapq.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13226 INFO: Excluding import of doctest from module heapq
13226 INFO: Loading module hook 'hook-importlib_metadata.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13227 INFO: Loading module hook 'hook-lib2to3.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13259 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13262 INFO: Excluding import of test.support from module multiprocessing.util
13262 INFO: Excluding import of test from module multiprocessing.util
13263 INFO: Loading module hook 'hook-numpy.core.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13356 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
13359 INFO: Loading module hook 'hook-numpy.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13360 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13362 INFO: Excluding import of pytest from module numpy._pytesttester
13363 INFO: Loading module hook 'hook-pickle.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13365 INFO: Excluding import of argparse from module pickle
13365 INFO: Loading module hook 'hook-pkg_resources.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
13650 INFO: Processing pre-safe import module hook win32com from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
13830 WARNING: Hidden import "pkg_resources.py2_warn" not found!
13831 WARNING: Hidden import "pkg_resources.markers" not found!
13839 INFO: Excluding import of __main__ from module pkg_resources
13840 INFO: Loading module hook 'hook-setuptools.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14325 INFO: Import to be excluded not found: 'setuptools.py27compat'
14326 INFO: Import to be excluded not found: 'setuptools.py33compat'
14328 INFO: Loading module hook 'hook-sysconfig.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14333 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14334 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14335 INFO: Loading module hook 'hook-xml.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14336 INFO: Loading module hook 'hook-_tkinter.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
14447 INFO: checking Tree
14447 INFO: Building Tree because Tree-00.toc is non existent
14449 INFO: Building Tree Tree-00.toc
14516 INFO: checking Tree
14517 INFO: Building Tree because Tree-01.toc is non existent
14518 INFO: Building Tree Tree-01.toc
14592 INFO: checking Tree
14592 INFO: Building Tree because Tree-02.toc is non existent
14594 INFO: Building Tree Tree-02.toc
14604 INFO: Loading module hook 'hook-pythoncom.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
14890 INFO: Loading module hook 'hook-pywintypes.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15172 INFO: Loading module hook 'hook-win32com.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15460 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks'...
15464 INFO: Excluding import of numpy from module setuptools.msvc
15506 INFO: Looking for ctypes DLLs
15580 INFO: Analyzing run-time hooks ...
15588 INFO: Including run-time hook 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
15592 INFO: Including run-time hook 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
15594 INFO: Including run-time hook 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
15595 INFO: Including run-time hook 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
15599 INFO: Including run-time hook 'd:\\anaconda\\envs\\annotator\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_certifi.py'
15614 INFO: Looking for dynamic libraries
15668 WARNING: lib not found: impi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_intelmpi_lp64.dll
15734 WARNING: lib not found: msmpi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_msmpi_ilp64.dll
15749 WARNING: lib not found: impi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_intelmpi_ilp64.dll
15865 WARNING: lib not found: mpich2mpi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_mpich2_ilp64.dll
15998 WARNING: lib not found: mpich2mpi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_mpich2_lp64.dll
16151 WARNING: lib not found: msmpi.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_blacs_msmpi_lp64.dll
16309 WARNING: lib not found: pgf90rtl.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_pgi_thread.dll
16312 WARNING: lib not found: pgc14.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_pgi_thread.dll
16316 WARNING: lib not found: pgf90.dll dependency of d:\anaconda\envs\annotator\Library\bin\mkl_pgi_thread.dll
17120 INFO: Looking for eggs
17121 INFO: Using Python library d:\anaconda\envs\annotator\python38.dll
17123 INFO: Found binding redirects:
[]
17135 INFO: Warnings written to D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\build\spacy_to_BERT_dataset\warn-spacy_to_BERT_dataset.txt
17352 INFO: Graph cross-reference written to D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\build\spacy_to_BERT_dataset\xref-spacy_to_BERT_dataset.html
17390 INFO: checking PYZ
17390 INFO: Building PYZ because PYZ-00.toc is non existent
17392 INFO: Building PYZ (ZlibArchive) D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\build\spacy_to_BERT_dataset\PYZ-00.pyz
19048 INFO: Building PYZ (ZlibArchive) D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\build\spacy_to_BERT_dataset\PYZ-00.pyz completed successfully.
19079 INFO: checking PKG
19079 INFO: Building PKG because PKG-00.toc is non existent
19079 INFO: Building PKG (CArchive) PKG-00.pkg
107848 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
107858 INFO: Bootloader d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
107858 INFO: checking EXE
107858 INFO: Building EXE because EXE-00.toc is non existent
107859 INFO: Building EXE from EXE-00.toc
107859 INFO: Appending archive to EXE D:\User\sergi\Desktop\Annotators\Spacy_NER_Annotator\dist\spacy_to_BERT_dataset.exe
132146 INFO: Building EXE from EXE-00.toc completed successfully.
```
When I try to execute the .exe:

```
Traceback (most recent call last):
  File "spacy_to_BERT_dataset.py", line 4, in <module>
    import spacy
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "spacy\__init__.py", line 10, in <module>
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "thinc\neural\__init__.py", line 4, in <module>
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "thinc\neural\_classes\model.py", line 7, in <module>
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "srsly\__init__.py", line 6, in <module>
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "srsly\_msgpack_api.py", line 6, in <module>
  File "d:\anaconda\envs\annotator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "srsly\msgpack\__init__.py", line 6, in <module>
  File "srsly\msgpack\_packer.pyx", line 7, in init srsly.msgpack._packer
ModuleNotFoundError: No module named 'srsly.msgpack.util'
[7520] Failed to execute script
```

## My Environment
* Operating System: Windows 10
* Python Version Used: Python 3.8.5
* spaCy Version Used: 2.3.4
* Environment Information: Conda env

**Comment by adrianeboyd** [comment] 2020-12-09 09:28
Hi, this is a duplicate of #6473, please try the suggestions in the linked StackOverflow answer.

**Closed** 2020-12-09 09:28 UTC
Labels: duplicate, install
