### ISSUE TITLE
nlp.pipe doesn't take n_thread into account

### ISSUE THREAD

**Issue by MarcSzafraniec** [explosion/spaCy#2075] opened 2018-03-08 15:33 UTC
Hello, I have the latest version of SpaCy, and in nlp.pipe n_thread is not taken into account, and seems to be stuck at -1. And indeed, when we look here https://github.com/explosion/spaCy/blob/master/spacy/pipeline.pyx (line 99), n_thread is an argument of the function but is never used. 

This problem should be easily solved, but it crucial to some...

**Comment by MarcSzafraniec** [comment] 2018-03-09 10:31
And even using `doc = nlp(text)` in a simple loop, one text after another, leads to multithreading. Do anyone has an idea to avoid that?

**Comment by honnibal** [comment] 2018-03-27 23:21
@MarcSzafraniec The multi-threading changed significantly in v2: Because we're now using neural network models, the main bottleneck is in the matrix multiplications, which we've so far been accessing via numpy, which accesses them via whatever BLAS library it's linked to.

v2.1 is changing this by shipping our own matrix multiplication function within Thinc, which will be set to single-threading. This will let us once again multi-thread the outer parser loop --- or likely even better, use multi-processing on the whole pipeline.

In the meantime, you can disable multi-threading from numpy using an environment variable. If numpy has been linked to OpenBLAS, `OPENBLAS_NUM_THREADS` should work. If it's linked to MKL (which will happen if you install via conda), the environment variable is different -- I don't immediately remember it.

**Comment by saroufimc1** [comment] 2018-05-12 00:09
Are you saying that now multi-threading is not working?

**Comment by korbonits** [comment] 2018-05-17 19:54
Compiling numpy with OpenBLAS totally worked for me -- and I didn't even need to set the threads to 1

**Comment by honnibal** [comment] 2018-07-06 13:15
@saroufimc1 Right now the `n_threads` argument doesn't really do what you'd expect (and not what it did in v1), so in a sense yes it's not working properly.

The problem is that numpy tries to multi-thread the matrix multiplications, which is too fine-grained a unit of work for us to get much benefit from it. In v1, I spent ages steadily working through the parsing loop so that I could release the global iterpreter lock around the whole parsing process. Now that the parsing algorithm is changed, that work would need to be re-done.

I'm now thinking that this is probably the wrong approach. In v1 we really had to use multi-threading rather than multi-processing, because the models were pretty large. In v2, the models are small, so I think multi-processing seems like a smarter option.

Fundamentally the workload for spaCy is embarrassingly parallel: each text is processed in isolation. So, the first thing I've done is remove the harmful low-level threading that numpy is doing, and made the matrix multiplications single-threaded. This lets the user parallelise the outer loops, without each process spinning up a bunch of wasteful threads.

**Comment by odedfos** [comment] 2018-08-16 13:55
Any update on this?

**Comment by mlucas-NU** [comment] 2018-08-21 14:32
Would love an update on this as well. At the very least, this file should be removed or a warning should be added to master that it doesn't work with current releases.

https://github.com/explosion/spaCy/blob/master/examples/pipeline/multi_processing.py

**Comment by honnibal** [comment] 2018-09-12 14:15
@mlucas-NU That multi-processing example should still work. You just need to make sure numpy isn't also launching threads, as described above.

**Comment by randomgambit** [comment] 2018-11-01 12:51
guys I am using 

`for parsed_doc in nlp.pipe(iter(unique_news.headline), batch_size=10000, n_threads = 20):`

Is it correct to say that the code above does NOT perform parallization of the parsing? I am confused here. Thanks!

**Comment by randomgambit** [comment] 2018-12-20 17:40
@honnibal closed because solved?!

**Comment by honnibal** [comment] 2018-12-20 17:43
Closed in error, sorry!

**Comment by honnibal** [comment] 2019-02-21 11:33
The newest v2.1 version (installable via `spacy-nightly`) now notes the `n_threads` argument as deprecated. The docs have been updated accordingly.

**Closed by honnibal** 2019-02-21 11:33 UTC
Labels: enhancement, usage
