### ISSUE TITLE
Given same input en_core_web_trf sometime predicts all entities and sometime it misses few

### ISSUE THREAD

**Issue by kaushikepi** [explosion/spaCy#11160] opened 2022-07-19 11:01 UTC
I have been using the `en_core_web_trf` NER model to predict all the `PERSON` entities from a document. 

## Issue
Observed that given the same input to the model it sometimes predicts all the `PERSON` entities from the document but sometimes It misses a few of the `PERSON` entities.

Why there is so much variance in prediction?

## Your Environment

* Operating System: Linux
* Python Version Used: `3.6.13`
* spaCy Version Used:  `spacy==3.0.5`, `spacy-transformers==1.0.4`, `cupy-cuda101`, `en_core_web_trf`

**Comment by rmitsch** [comment] 2022-07-19 13:05
Hi @kaushikepi, could you provide a minimal, reproducible example?

**Comment by kaushikepi** [comment] 2022-07-19 19:23
This is the API which I have created to extract PERSON and GPE entities from given document
```
"""spaCy Transformer based PERSON & LOCATION(cities and states) entity information extraction API."""
import time
from http import HTTPStatus
from typing import Any, Dict, List

import sentry_sdk
import spacy
import torch
from fastapi import FastAPI, Request
from pydantic import BaseModel
from spacy.language import Language
from spacy.tokens import Doc
from thinc.api import require_gpu, set_gpu_allocator

sentry_sdk.init(
    "https://62f8fdc12624420e9eabc1d8f4274dcb@o308926.ingest.sentry.io/5921256",
)

app = FastAPI(
    title="NPI - Made with Transformers",
    description="Predict provider namse given a text input from a medical chart",
    version="0.1",
)

if spacy.prefer_gpu():
    print("\n\033[92m" + "✔ Using GPU" + "\033[0m\n")
    set_gpu_allocator("pytorch")
    require_gpu(0)
else:
    print("\n\033[91m" + "✘ NOT Using GPU!" + "\033[0m\n")

torch.set_num_threads(1)
nlp_trf = spacy.load(
    "en_core_web_trf", exclude=["tagger", "parser", "attribute_ruler", "lemmatizer"]
)


@Language.component("remove_trf_data")
def remove_trf_data(doc: Doc) -> Doc:
    """
    Remove transformer tensors after being provessed by pipeline.

    Parameters
    ----------
    doc : Doc
        spaCy Doc object pf Medical Record pages.

    Returns
    -------
    Doc
        spaCy Doc object with flushed transformer tensor.
    """
    doc._.trf_data = None
    torch.cuda.empty_cache()
    return doc


nlp_trf.add_pipe("remove_trf_data")


class RecordRequest(BaseModel):
    """Element wise request data validation check."""

    page_no: str
    page_text: str


class RecordRequestIn(BaseModel):
    """Request data validation check."""

    values: List[RecordRequest]


class RecordResponseOut(BaseModel):
    """Response data validation check."""

    entities: Dict[str, Dict[str, List[tuple]]]
    time_taken: str


@app.get("/", tags=["General"])
def _index(request: Request) -> Dict[str, Any]:
    """Health check."""
    response: Dict[str, Any] = {
        "message": HTTPStatus.OK.phrase,
        "status-code": HTTPStatus.OK,
        "nlp_pipeline": nlp_trf.pipe_names,
        "data": {},
    }

    return response


@app.post("/entities", response_model=RecordResponseOut)
def extract_per_entities(body: RecordRequestIn) -> Dict[str, Any]:
    """Extract PERSON, CITY & STATE entity information from request batch of pages.

    Parameters
    ----------
    body : RecordRequestIn
        Request data type for information extraction.

    Returns
    -------
    Dict[str, Any]
        Page-wise PERSON, CITY & STATE entity information for request batch of Medical record.
    """
    start_time = time.time()

    records = body.values
    chart_info_pagewise = {}

    page_ids = [doc.page_no for doc in records]
    texts = [doc.page_text for doc in records]

    for doc_id, spacy_doc in zip(page_ids, nlp_trf.pipe(texts)):
        pagewise_entities, cities_entities, state_entities = [], [], []
        for ent in spacy_doc.ents:
            if ent.label_ == "PERSON":
                pagewise_entities.append(
                    (ent.text, ent.start, ent.end, ent.start_char, ent.end_char)
                )
            elif ent.label_ == "GPE":
                if len(ent.text) == 2:
                    state_entities.append(
                        (ent.text, ent.start, ent.end, ent.start_char, ent.end_char)
                    )
                else:
                    cities_entities.append(
                        (ent.text, ent.start, ent.end, ent.start_char, ent.end_char)
                    )

        chart_info_pagewise[doc_id] = {
            "PERSON": pagewise_entities,
            "CITIES": cities_entities,
            "STATES": state_entities,
        }

    response = {"entities": chart_info_pagewise, "time_taken": str(time.time() - start_time)}
    return response

```

**Comment by kaushikepi** [comment] 2022-07-19 19:25
Docker image for API deployment on GPU instance
```
FROM nvidia/cuda:10.1-devel-ubuntu18.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub

# Install base packages.
RUN apt-get update --fix-missing && apt-get install -y \
    bzip2 \
    ca-certificates \
    python3-dev \
    python3-pip \
    gcc \
    libc-dev \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libevent-dev \
    libgl1-mesa-glx \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# Tell nvidia-docker the driver spec that we need as well as to
# use all available devices, which are mounted at /usr/local/nvidia.
# The LABEL supports an older version of nvidia-docker, the env
# variables a newer one.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
LABEL com.nvidia.volumes.needed="nvidia_driver"

#Install spacy and its dependencies
RUN pip3 install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install --upgrade pip && \
    pip3 install -U setuptools wheel && \
    pip3 install spacy==3.0.5 spacy-transformers==1.0.4 cupy-cuda101 sentry-sdk==1.3.0 && \
    python3 -m spacy download en_core_web_trf

#Install server packages
RUN pip3 install fastapi uvicorn pydantic

WORKDIR /app
COPY ./app /app

EXPOSE 5000

ENTRYPOINT ["uvicorn"]
CMD ["api:app", "--host", "0.0.0.0", "--timeout-keep-alive", "300", "--workers", "4" ,"--port", "5000"]
```

**Comment by kaushikepi** [comment] 2022-07-19 19:29
@rmitsch I can't share with you the exact input document.
So the above API is used in production for entity extraction. Given the same input, it always predicts the same entities when pinged from the local system but when the same given the same input in the production environment  it sometimes predicts the same entities which are predicted when pinged from local but sometime misses few entities .

**Comment by polm** [comment] 2022-07-20 06:21
Thank you for the extensive code samples. I understand that you have this in an API, but it looks like you are just doing a basic call to the pipeline, so could you test this with something simpler like the below code?

```
import spacy

nlp = spacy.load("en_core_web_trf")
doc = nlp(... text ...)
for ent in doc.ents:
    print(ent)
```

Note that inference should be reproducible in the same environment, but if there are environment differences (hardware, OS, Python version, etc.) there can be differences in predictions. They should be relatively uncommon and not always better or worse. It sounds like you are seeing differences between different environments. Here are some things to check:

1. is the OS the same between environments?
2. CUDA versions (this looks the same)
3. Python versions
4. All Python libraries (`pip freeze` output)
5. Hardware differences

Not all of these are equally likely to make a difference, but because this kind of issue can be hard to troubleshoot the more info available the better.

I understand you can't share your data, but could you use sentences from WIkipedia or something to find differences? Without an example we can reproduce it's very hard for us to do anything about this.

> Given the same input, it always predicts the same entities when pinged from the local system but when the same doc is given as input in the production environment it sometimes predicts the same entities which are predicted when pinged from the local system environment but sometimes miss a few entities.

Just to be very clear about this - the server behaves differently depeneding on whether it's running in production or locally, not based on the location of the request, right? I can't imagine the location of the request making a difference for any reason internal to spaCy.

**Comment by polm** [comment] 2022-07-20 06:25
Also, you might want to check that you're sending exactly the same text from different environments. You can check this by logging `hash(doc.text)`.

**Comment by kaushikepi** [comment] 2022-07-25 11:38
@polm @rmitsch 
Here is an example:
#### First Image
<img width="318" alt="image" src="https://user-images.githubusercontent.com/59639615/180768388-d1720792-ed63-41bd-89b3-57e2546c9116.png">

#### Second Image
<img width="335" alt="image" src="https://user-images.githubusercontent.com/59639615/180768429-b5ed6a9b-2c64-47ee-97e5-7a72ab7875d9.png">

So in the first Image, the PERSON entity is `CLAIRE E MOORE` which is correctly extracted by the spacy NER model but in the second image it predicts the `MOORE` token as a GPE entity which you can see in the second image's `location` key where `MOORE` has been classified as a GPE entity because MOORE is a city in Cleveland County, Oklahoma, United States

**Comment by polm** [comment] 2022-08-09 09:14
With only the info we have here unfortunately here we are unfortunately unable to debug this problem. I'll close this for now but if you have more information please feel free to follow up.

**Closed by polm** 2022-08-09 09:14 UTC
Labels: feat / ner, more-info-needed, perf / accuracy
