### ISSUE TITLE
[Lemmatisation] : french - some strange error

### ISSUE THREAD

**Issue by puli83** [explosion/spaCy#2659] opened 2018-08-11 16:11 UTC
Hi, 

it's not a big problem to explain.
I lemmatize with spacy this sentence " Logiquement, l' ASSÉ veut présenter les candidats aux prochaines élections."

ROOT of this sentence is "présenter", which is a VERB in his infinitive form. Why I get "poster" as lemma? This is strange. Treetagger correctly lemmatize this sentence.

Do you have any idea about what it is happening?

## Your Environment

* Operating System: Windows 7 64 bit
* Python Version Used: 3.6.6
* spaCy Version Used: 2.0.11
* Environment Information: the model used fr_core_news_md

**Comment by ines** [comment] 2018-08-14 15:43
It's possible that these problems are caused by the lookup tables – for some languages, spaCy currently ships with more complex, rule-based lemmatizers. All other languages are currently covered by lookup tables, which aren't as reliable, and sometimes also contain mistakes. You can find a few similar discussions [in the `feat/lemmatizer` tag](https://github.com/explosion/spaCy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22feat+%2F+lemmatizer%22).

If you've come across a mistake that can be fixed by updating the lookup table, you can always submit a PR to [`fr/lemmatizer.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/fr/lemmatizer.py). We'd also love to transition all lemmatizers over to a rule-based approach in the future (like English).

**Comment by ines** [comment] 2018-08-14 16:04
Merging this with #2668!

**Closed by ines** 2018-08-14 16:04 UTC
Labels: feat / lemmatizer, lang / fr, performance
